### ISSUE TITLE
Bug: Cannot divide by 0

### ISSUE THREAD

**Issue by wyhaya** [ClementTsang/bottom#1]
https://github.com/ClementTsang/bottom/blob/e00b2bdd6633a3d36bb841c9525ea24e61c642b7/src/convert_data.rs#L187-L190

`data.mem_total_in_mb` :
Sometimes it is `0`, So the result is `NaN`.

https://github.com/ClementTsang/bottom/blob/e00b2bdd6633a3d36bb841c9525ea24e61c642b7/src/main.rs#L197-L200

Calling `update_swap_data_points` in `Event::Update` will cause the program to quit

**Comment by ClementTsang** [comment]
Ah, I see.  Thanks, totally missed that.

**Comment by ClementTsang** [comment]
https://github.com/ClementTsang/bottom/commit/22330011dd8959ebe46144fe93ca2e25a71bde7b should hopefully fix this.
