### ISSUE TITLE
[Feature] Filter idle processes

### ISSUE THREAD

**Issue by lutzky** [ClementTsang/bottom#1012]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

In `top`, the `i` key filters "idle" processes. It's somewhat helpful, when the load average is going up, to see which processes are driving it (they might not be high-CPU ones).

I'm doing some research as I file this FR (including filing https://github.com/GuillaumeGomez/sysinfo/issues/928), to try and see what `top` does.

So apparently "hide idle" [used to mean](https://github.com/mmalecki/procps/blob/fe4c4a7314f32907b9f558ad0d8b8d0ff1cc76be/top.c#L3231) "show everything but `[SZT]`, but ["nowadays seems to mean"](https://github.com/mmalecki/procps/blob/fe4c4a7314f32907b9f558ad0d8b8d0ff1cc76be/top.c#L3231) "show everything that has used any CPU". I'm not sure whether or not that counts `D` uninterruptable sleep, though.

So, I *think* I'm achieving what I mean ("show only processes which drive the load average") by filtering for `state = Idle || cpu > 0`. (Edit: After https://github.com/GuillaumeGomez/sysinfo/pull/929, this would be `state = UninterruptableDiskSleep || cpu > 0`)

1. Does this match your understanding?
2. Does it make sense to create a builtin shortcut for this?
3. [bonus] Does it make sense to create configurable filter shortcuts?

**Comment by ClementTsang** [comment]
1. I think your search would make sense, yes.
2. Hmm... maybe? I'm looking at user-customizable keybindings and shortcuts, so I could maybe look into something like that.
3. Going off the previous answer, shortcuts to maybe load a certain query might be something I could consider.

**Comment by ClementTsang** [comment]
Gonna close this since the main part (supporting idle state, especially in searches) should work now as of bottom 0.9.0. The other parts I'll probably handle with other issues/features.
