### ISSUE TITLE
[Bug] Network activity values are 10x to big

### ISSUE THREAD

**Issue by LostInCompilation** [ClementTsang/bottom#1049]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

All values of the network activity are exactly 10 times to high. Everything is multiplied by 10.
The real values on the image would be:
RX: 230kb/s
TX: 23.1mb/s

Device: MacBook Pro 2021 with M1 Pro

<img width="931" alt="Screenshot 2023-03-06 at 14 41 58" src="https://user-images.githubusercontent.com/12819635/223126970-443f3a5f-4359-4821-921e-736135c738fa.png">

### What operating system and version are you using?

macOS 13.2.1

### What architecture are you using?

arm64

### What terminal(s) are you running `bottom` on?

Hyper with zsh

### What version of `bottom` are you running?

0.8.0

### How did you install `bottom`?

Homebrew

### How can we reproduce this?

Default config and install. Just opened btm.

**Comment by ClementTsang** [comment]
Do you have another source of data for me to compare with? e.g. htop

**Comment by LostInCompilation** [comment]
Transmit:
<img width="1159" alt="Screenshot 2023-03-06 at 15 35 34" src="https://user-images.githubusercontent.com/12819635/223141942-86b39b45-f182-4611-a5aa-c7916596a09d.png">


Receive:
<img width="1153" alt="Screenshot 2023-03-06 at 15 37 31" src="https://user-images.githubusercontent.com/12819635/223141985-13dc1ccb-7421-4bbc-a8a4-d5fcbc9b0056.png">

**Comment by LostInCompilation** [comment]
Transmit:
<img width="1159" alt="Screenshot 2023-03-06 at 15 35 34" src="https://user-images.githubusercontent.com/12819635/223142692-927ca981-7399-496d-b176-838c81af2a55.png">

Receive:
<img width="1153" alt="Screenshot 2023-03-06 at 15 37 31" src="https://user-images.githubusercontent.com/12819635/223142740-7e637aa9-7834-4276-8193-b10b794ac32b.png">

**Comment by ClementTsang** [comment]
Hmm, checking on my own MBP, it seems to match Activity Monitor?

Note that by default the unit used by the network widget is bits, not bytes. If I multiply 188 KB it's 1.5Mb, and 25.8 MB is 206 Mb, for example, which seems to be in the ballpark of what btm is reporting in your second image.

**Comment by ClementTsang** [comment]
You can use `--network_use_bytes` if that'll make comparing easier.

**Comment by LostInCompilation** [comment]
Yeah it was showing bits, not bytes.
However this is very misleading. Mb is megabyte, not megabits. The units should be changed to Mbit/s Kbit/s.
It is not standard to have Mb for bits and MB for bytes.

**Comment by ClementTsang** [comment]
Uhhhh... B for byte and b for bit are standard convention...

**Comment by LostInCompilation** [comment]
Yep I mixed up something.
But as a suggestion Mbit/s would be more clear.

**Comment by ClementTsang** [comment]
Sure, I can consider making that an option in the future if it's apparently confusing for some people.

**Comment by LostInCompilation** [comment]
The thing is Mb and MB are mostly used both for Mega byte, even though one of them is wrongly used as such. I got conditioned hardly by these errors to view Mb and MB as the same. Since Mbit is used for bit almost everywhere.

**Comment by jackloomen** [comment]
bottom (0.8.0_1 -> 0.9.1_1)  update made network stats non functional, permanently stay at 0.

**Comment by ClementTsang** [comment]
@jackloomen Please file a new issue, this is not related.
