### ISSUE TITLE
[Bug] cargo install error :reference to packed field is unaligned

### ISSUE THREAD

**Issue by lost22git** [ClementTsang/bottom#1056]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### cargo install error msg
```
error[E0793]: reference to packed field is unaligned
*tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)
error: could not compile `ntapi` due to 2 previous errors
```

### What operating system and version are you using?

win11

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

windows terminal

### What version of `bottom` are you running?

latest

### How did you install `bottom`?

cargo 

### How can we reproduce this?

cargo install bottom

**Comment by ClementTsang** [comment]
Hmmm, interesting. What version of Rust are you using? I'm guessing it might be due to some warning that's been upgraded to an error in recent versions of Rust.

**Comment by ClementTsang** [comment]
I guess for now a workaround is using the pre-built binaries? There's a winget package and MSI installer.

**Comment by ClementTsang** [comment]
Ah. Are you using nightly or beta? I can run `cargo install bottom` fine on stable (1.68), though I definitely do need to fix this for the future.

**Comment by lost22git** [comment]
@ClementTsang  it works after switching to stable channel, thanks ;-)

**Comment by ClementTsang** [comment]
NP.

Just as an extra update, this is already fixed in the current master branch, as we only rely on ntapi 0.4.0, which reports no issues when I try checking with beta/nightly (`cargo +beta check`). Trying this with 0.3.7 causes the errors above.

I'll likely do a 0.8.1/0.9.0 update within the next few weeks.

**Comment by ClementTsang** [comment]
@SHarkGANGS I think you need to bring this up in the appropriate repo, that's an issue the maintainer will need to handle.

**Comment by SHarkGANGS** [comment]
> 
I made a mistake, here is the command that ends with an error -
**spl-token-cli**

**Comment by ClementTsang** [comment]
Yeah, definitely bring that up in the appropriate repo, as it doesn't seem to relate to bottom here. As a workaround though, you can probably install using an older version of Rust.

**Comment by SHarkGANGS** [comment]
> Да, определенно поднимите это в соответствующем репозитории, так как здесь, похоже, это не относится к дну. Однако в качестве обходного пути вы, вероятно, можете установить, используя более старую версию Rust.

Can you suggest a windows installer startup command ?
I run (rustup-init.exe) the installer file as an administrator, select the number 1
Where is the repository where you can discuss this problem, I do not understand !

**Comment by ClementTsang** [comment]
You are installing another program that is **not** bottom, from the looks of it. This repo is for the program bottom. So if the issue is not about bottom, I cannot help you much.

**Comment by ClementTsang** [comment]
This is the sugar-cli repo: https://github.com/metaplex-foundation/sugar

Please use that instead.

**Comment by SHarkGANGS** [comment]
> This is the sugar-cli repo: https://github.com/metaplex-foundation/sugar
> 
> Please use that instead.

**### Honor and respect !**
