### ISSUE TITLE
[Packaging] Build musl-linked debian packages

### ISSUE THREAD

**Issue by ethanhs** [ClementTsang/bottom#1060]
### Checklist

- [X] I have read the above text.

### Describe the issue

Currently [Debian packages in the releases link to glibc](https://github.com/ClementTsang/bottom/blob/7f4e7629213d55723616d2cbfc0699c942e07017/.github/workflows/build_releases.yml#L289). However, this makes them less portable. Ideally, statically linked musl packages would be much more portable between debian/ubuntu versions. I personally would love to see this so I can include bottom in https://apt.cli.rs, my Rust CLI tools apt repo :)

**Comment by ClementTsang** [comment]
Sure, I can look into adding them into the build list.

**Comment by ClementTsang** [comment]
Added musl build targets to the deployment job. They should show up in the nightly builds shortly, and whenever I deploy 0.8.1/0.9.0, they should show up there too.
