### ISSUE TITLE
[Bug] Keystrokes are doubled

### ISSUE THREAD

**Issue by brian6932** [ClementTsang/bottom#1065]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

All keystrokes are doubled (sent twice), most noticeable when using `/`

### What operating system and version are you using?

Windows 10

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

alacritty 0.11.0 (d23330a)

### What version of `bottom` are you running?

bottom 0.8.1-nightly-61fec230

### How did you install `bottom`?

Personal scoop package in `scoop/versions`, uses latest successful artifact

### How can we reproduce this?

No particular steps taken, I just launched the most recent nightly ver

### Additional information

config
```toml
[flags]
group_processes = true
regex = true
mem_as_value = true
```

**Comment by ClementTsang** [comment]
Interesting, I can reproduce this. Let me bisect and see where this is coming up, as I didn't have issues on my Windows 11 environment not too long ago.

**Comment by ClementTsang** [comment]
Well that was easy to guess, bumping the crosstern version in commit f02bd21948913966c6c8f78c3f51938aa9e045c8 was the problem.

Will either revert or see what I messed up and try to get that out ASAP.

**Comment by ClementTsang** [comment]
Was taking a look in the changelogs - I think it's maybe this:

> Add key release event for windows.

For now I'll just revert crossterm to solve the issue, which seems to work for me.

**Comment by ClementTsang** [comment]
Merged revert, should hopefully work for you now. Nightly build will be out at the usual time in a few hours if you don't mind waiting.
