### ISSUE TITLE
[Windows] Disks widget shows `\\?\Volume{drive ID}` instead of drive names

### ISSUE THREAD

**Issue by Scripter17** [ClementTsang/bottom#1075]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

Basically just what's in the title

### What operating system and version are you using?

Windows 10 22H2

### What architecture are you using?

x86

### What terminal(s) are you running `bottom` on?

Regular command prompt (cmd.exe)

### What version of `bottom` are you running?

0.8.0

### How did you install `bottom`?

Through cargo

### How can we reproduce this?

1. Open bottom on windows
2. Look at the disks widget

**Comment by ClementTsang** [comment]
That's not really a bug, it's currently intentional behaviour, though I can look to changing it.

**Comment by Scripter17** [comment]
...So the intended behaviour is to... sort alphabetically by drive ID instead of what the drive is named...

I can understand this being a "I can't be bothered to fix this" problem because it's the exact kind of obvious feature windows would make hard (at least without spawning a `wmic` process each time you want to get the disk info) but this does at all not look like intended behaviour.

I'm really am sorry if I'm coming off as rude but I am just baffled

**Comment by ClementTsang** [comment]
The original and intended behaviour was sorting by disk name, yes. And the returned name for a drive on Windows was this weird name, which it has been for years.

I'm fine with changing it but it isn't a bug, and it's behaviour I'm considering intended for now.

**Comment by ClementTsang** [comment]
Looks like https://github.com/ClementTsang/bottom/pull/1064 will end up changing this, though currently the behaviour for some drives is that it'll just return a blank name now.

**Comment by ClementTsang** [comment]
New behaviour is that it'll return whatever `sysinfo` returns, which generally seems to match whatever it is named in File Explorer. For drives with no name, for now, I instead return `No Name`, as I'm not sure if leaving it blank would cause confusion.
