### ISSUE TITLE
Failed systemd units?

### ISSUE THREAD

**Issue by swsnr** [ClementTsang/bottom#1088]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

I think on Linux failed systemd units (i.e. what `systemctl --failed` shows) would be a helpful metric (perhaps just as a simple counter).

Would you be open for a corresponding merge request?

**Comment by ClementTsang** [comment]
It could be interesting, design shouldn't be that hard either. Do you happen to know if there's a library way of getting this data?

And yeah, I would be happy to get any PRs.

**Comment by ClementTsang** [comment]
That would definitely be possible to do, though currently we only have one main configurable refresh rate for data, so it might be worth introducing a second one for something like this if we need it.

**Comment by swsnr** [comment]
Realistically I'll not find time for this so I might just as well close this.
