### ISSUE TITLE
CPU Use%

### ISSUE THREAD

**Issue by darksilentcore** [ClementTsang/bottom#1122]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

An Idea.
Add feature to hide CPU Use% Table in CPU Section
Thanks

**Comment by ClementTsang** [comment]
Gonna close this and roll it up with a more general issue (#1125).
