### ISSUE TITLE
Failed to initialize logger (always creats `debug.log` in cwd) in release target

### ISSUE THREAD

**Issue by hasezoey** [ClementTsang/bottom#1131]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Manjaro 22.1.0 / ubutnu server 22.04

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

Konsole (KDE)

### What version of `bottom` are you running?

4cdedffaeee01190a054498dce21b5003496a71e

### How did you install `bottom`?

git clone and self-compile

### Describe the issue

Since running a git pull, btm fails to initialize the logger when in a directory without write permissions, and in directories with write permission it always creates a empty `debug.log` file when build for the release target

### What is the expected behaviour?

no file to be created by default

### What is the actual behaviour?

a file being created / tried to be created

### How can we reproduce this?

1. clone repository at mentioned commit
2. compile it (in release target)
3. try to run it in a directory without write-permissions
4. try to run it in a directory with write-permissions

### Additional information

compiled with `cargo build --release`

git bisect seems to tell that 20902e87b97091bf7d524cdec42a87bd8e145d74 is the problematic commit, because it removes the `debug_assertions` from `init_logger`

also it seems like the file is always just empty

**Comment by ClementTsang** [comment]
Thanks, will handle this in a bit.

**Comment by ClementTsang** [comment]
For now though, you can work around this by just building it with the logging feature disabled (`cargo build --features deploy`).

**Comment by ClementTsang** [comment]
As for why it's empty, it's mainly because I only use it for local debug logging while developing, usually the logs are commented out.

**Comment by ClementTsang** [comment]
PR linked should fix it for now by just not hard-erroring (it'll still print a warning though). I'll also do another PR later that adjusts the default features so the logging code doesn't run at all by default.
