### ISSUE TITLE
New release needed on crates.io

### ISSUE THREAD

**Issue by lesleyrs** [ClementTsang/bottom#1137]
### Checklist

- [X] I have read the above text.

### Describe the issue

`cargo install bottom --locked` fails on windows because of older winapi, but latest master works.

**Comment by ClementTsang** [comment]
Thanks for the heads up, will aim to do so in the next few days.

**Comment by ClementTsang** [comment]
Should hopefully be able to do so after I fix one more bug (#1140).

**Comment by ClementTsang** [comment]
[Just released 0.9.0](https://github.com/ClementTsang/bottom/releases/tag/0.9.0), let me know if there are any issues. Tested installing on my Windows VM and it seems fine.
