### ISSUE TITLE
incorrect sorting order of cpu core in temperature panel

### ISSUE THREAD

**Issue by futuretech6** [ClementTsang/bottom#1146]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Ubuntu 20.04.6 LTS

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

Windows Terminal 1.16.10262.0

### What version of `bottom` are you running?

0.9.0

### How did you install `bottom`?

cargo install bottom

### Describe the issue

The "sorted by sensors" field of temperature panel has incorrect order of cpu core

### What is the expected behaviour?

```
Core 0
Core 1
Core 2
Core 3
...
Core 9
Core 10
Core 11
...
Core 19
Core 20
Core 21
...
```

### What is the actual behaviour?

```
Core 0
Core 1
Core 10
Core 11
...
Core 19
Core 2
Core 20
...
Core 3
```

### How can we reproduce this?

Run `btm`

**Comment by ClementTsang** [comment]
Hmm. This isn't technically a bug in the sense that it's correct lexicographic sorting - I'm just sorting by string value.

Might be worth adding something to sort numbers differently but atm this isn't a bug. Going to close for now but I might add a flag to take this into consideration if it isn't too hard.
