### ISSUE TITLE
Winget package is old (Jan 2023)

### ISSUE THREAD

**Issue by hl2guide** [ClementTsang/bottom#1154]
### Checklist

- [X] I have read the above text.

### Describe the issue

If you install using winget you get older version.

![1](https://github.com/ClementTsang/bottom/assets/17044982/6f58db33-dcb5-49d9-b227-5841cf6c0b0c)

**Comment by ClementTsang** [comment]
The issue template you use mentions:

> Furthermore, outside of:
> 
> - crates.io
> - Chocolatey
> - Binary releases on GitHub
> 
> I do not maintain any other distribution channel. Preferably, you should contact the package maintainers first where appropriate for help for distribution-related issues (e.g. package has issues installing, is outdated, etc.)

I do *not* maintain the Winget package. I believe it is automatically updated by another package maintainer.

**Comment by ClementTsang** [comment]
You can also file an issue here (or if you would prefer someone else do it, let me know): https://github.com/microsoft/winget-pkgs/issues

**Comment by ClementTsang** [comment]
Filed the issue for you: https://github.com/microsoft/winget-pkgs/issues/106780
