### ISSUE TITLE
Enable option to choose with processes column to initially sort by

### ISSUE THREAD

**Issue by arozbiz** [ClementTsang/bottom#1229]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

It would be great if the user could choose with column to initially sort on in the processes widget. Specifically, I'd like to be able to have the default/initial sort be on the mem% rather than cpu% column.

**Comment by ClementTsang** [comment]
Looks like a duplicate of https://github.com/ClementTsang/bottom/issues/810

**Comment by arozbiz** [comment]
Apologies!
