### ISSUE TITLE
Increase size of the "Charge %" bar in the battery widget

### ISSUE THREAD

**Issue by FreezyLemon** [ClementTsang/bottom#1238]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

The battery widget currently seems to be split 50/50, with the left side being  labels for the information shown on the right side:

![image of the battery widget](https://github.com/ClementTsang/bottom/assets/13467374/89afdcff-d5fd-4564-95e2-448205415c57)

I'm not sure how easy "breaking" this column-based layout is, but IMO it would make sense to give the "Charge %" bar more horizontal space.

Otherwise, maybe give the bar its own line?

```
Charge %
[||||||||||                         37%]

Rate                  12.34W
State                 Discharging
To empty              3h 17m 12s
Health %              97.00%
```

**Comment by ClementTsang** [comment]
Hm, could look at that.
