### ISSUE TITLE
Nitpick: Remove redundant percentage signs (%)

### ISSUE THREAD

**Issue by FreezyLemon** [ClementTsang/bottom#1239]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

This is a minor UI suggestion, but it seems like a small improvement to me. So here goes:

There are some places in the UI that duplicate the percentage sign. For example, the "Processes" widget shows it in the table header, and in the actual values too:
![Image of the "Processes" widget](https://github.com/ClementTsang/bottom/assets/13467374/21c10ada-e4c3-4c24-8bae-8c2c5195623f)

Other places that I could find:
- Battery widget: "Charge %" and "Health %":
![Image of the "Battery" widget](https://github.com/ClementTsang/bottom/assets/13467374/e2a28efa-518a-43c6-af62-efce2394443b)
- CPU legend: "Use%"
![Image of the "CPU" widget, including the CPU legend](https://github.com/ClementTsang/bottom/assets/13467374/38a61065-afa9-4b10-80e4-3c4742e9c5a8)

Other applications like top and btop++ generally put the "unit" (in this case, the percentage sign) into the header and don't show them for values:
btop:
![image](https://github.com/ClementTsang/bottom/assets/13467374/9299b766-7ea9-4a7a-aa0e-55d8476ed24b)

top:
![image](https://github.com/ClementTsang/bottom/assets/13467374/3139be4e-8e5b-4a03-99b2-b5f136813401)

I'd argue that this would make sense for the table-like data (Processes, CPU), but maybe the battery widget should show "Health" and "Charge" and include the "%" on the value side.

**Comment by ClementTsang** [comment]
I could see myself changing the battery ones, not so sure about the others.

**Comment by ClementTsang** [comment]
As for the others I might add more customization per-widget at some point so that could maybe fall under there?

**Comment by ClementTsang** [comment]
Alright, for now, I'm going to change it for the battery widget and CPU widget as I agree they look a bit redundant/unnecessary there.

I'm a bit more hesitant for the processes widget since I personally differentiate between, say, `Mem` and `Mem%` as two different things, but I might be up for changing that later. As mentioned above, I might make it so that some things are more configurable by the user regarding columns/widgets in the future though so I might consider lumping a change like that there.

**Comment by Bellavene** [comment]
Great suggestion, I would even remove them from the processes list, so it will be faster to focus on actual numbers. There is already a % sign on the description of the columns.
