### ISSUE TITLE
[Windows] Bottom does not close process handles after they are killed.

### ISSUE THREAD

**Issue by JABirchall** [ClementTsang/bottom#1242]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Windows 10 22H2 19045.3086

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running bottom on?

Running from NuShell in Windows Terminal - With admin privilages

### What version of bottom are you running?

0.9.3

### How did you install bottom?

winget

### Describe the issue

Bottom is not closing the process handle after killing the process causing a [handle leak](https://www.deleaker.com/blog/2021/12/29/handle-leaks/).

https://github.com/ClementTsang/bottom/blob/7240661aabb188485ee4024ba9c8b92ad0052b5c/src/app/process_killer.rs#L20C1-L38C2

![WindowsTerminal_giONXigXSl](https://github.com/ClementTsang/bottom/assets/3427459/8f96df07-d1f5-4022-aca6-1f817338777f)

Prior to opening notepad
```
Handle type summary:
  ALPC Port       : 3
  Desktop         : 1
  Directory       : 3
  EtwRegistration : 86
  Event           : 22
  File            : 16
  IoCompletion    : 4
  IRTimer         : 6
  Key             : 52
  Mutant          : 45
  Process         : 171
  Section         : 2
  Semaphore       : 10
  Thread          : 5
  TpWorkerFactory : 3
  WaitCompletionPacket: 9
  WindowStation   : 2
Total handles: 440
```
After opening notepad
```
Handle type summary:
  ALPC Port       : 3
  Desktop         : 1
  Directory       : 3
  EtwRegistration : 86
  Event           : 22
  File            : 16
  IoCompletion    : 4
  IRTimer         : 6
  Key             : 52
  Mutant          : 45
  Process         : 173
  Section         : 2
  Semaphore       : 10
  Thread          : 5
  TpWorkerFactory : 3
  WaitCompletionPacket: 9
  WindowStation   : 2
Total handles: 442
```
These handles remain unchanged after killing notepad in bottom.

### What is the expected behaviour?

The handle to be closed for windows to clean up the process.

### What is the actual behaviour?

Handle is kept open by bottom leading to a leak

### How can we reproduce this?

Download sysinternals handles tool here: https://learn.microsoft.com/en-us/sysinternals/downloads/handle

Run `btm`
Run `handle -s -p {btm_pid}`
Run a process
Run `handle -s -p {btm_pid}` # Notice the total and process handle count increase
Kill the process in btm
Run `handle -s -p {btm_pid}` # The total and process handles does not decrease pointing to the handle being kept open.

You can also run `handle -a -p {btm_pid}` and observe reported non-existing process handles.

![](https://i.imgur.com/rTs7J3E.png)

**Comment by ClementTsang** [comment]
Also noted, will look at this when I have some time.

**Comment by ClementTsang** [comment]
Should be fixed in master now. Thanks for catching this!
