### ISSUE TITLE
About 0.9.3 release

### ISSUE THREAD

**Issue by chenrui333** [ClementTsang/bottom#1262]
👋 while [upgrading rust to 1.71.0](https://github.com/Homebrew/homebrew-core/pull/136514), we found that bottom 0.9.3 checksum got changed, raise this issue to confirm if there was a re-reg for the 0.9.3 release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/137181

**Comment by ClementTsang** [comment]
0.9.3 was built a few weeks ago using Rust 1.70.0, so not sure if that's causing issues.

There were also a few deployment runs of 0.9.3 for various reasons [see here](https://github.com/ClementTsang/bottom/actions/workflows/deployment.yml) so I'm not sure if that might have caused some issues.

**Comment by chenrui333** [comment]
no worries, just to raise some awareness. :)

**Comment by ClementTsang** [comment]
Appreciated, thanks for the heads up!
