### ISSUE TITLE
Process Widget - Add a parameter to start with grouping mode

### ISSUE THREAD

**Issue by varaskkar** [ClementTsang/bottom#1275]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

Hello!

Whenever I start Bottom, I go to the processes widget and hit the Tab key to activate the grouping mode.
Would it be possible to add a parameter to start Bottom already with that option?

Something like that "btm --grouping_processes"

**Comment by ClementTsang** [comment]
Does `btm -g` work?

**Comment by varaskkar** [comment]
Yes, it works great, thank you a million times! I didn't know that the -g parameter already did it.

As it is already solved, I proceed to close the task :)
