### ISSUE TITLE
Command Line Widget

### ISSUE THREAD

**Issue by wcuny** [ClementTsang/bottom#1294]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

I currently have btm setup in my .zshrc file to run whenever I open my terminal. I think it would be cool to have everything still open and viewable while using the functionality of the terminal. I am proposing an option that allows the user to have a widget or section of the program that just acts as a normal terminal/command line.

**Comment by ClementTsang** [comment]
I don't really think that's in scope for this project at the moment, sorry.

As an alternative I would just start up bottom within a `tmux` window/pane.
