### ISSUE TITLE
[Linux] Implement .desktop file?

### ISSUE THREAD

**Issue by ZerdoX-x** [ClementTsang/bottom#1295]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

I would like to have a `.desktop` file provided by bottom.
I know that bottom is a CLI tool, but it doesn't mean user's should not have ability to launch it using their app launcher.

As workaround I create it manually and put it in `$XDG_DATA_HOME/applications/` with following contents:
```
[Desktop Entry]
Name=Bottom
Comment=Yet another cross-platform graphical process/system monitor.
Exec=btm
Terminal=true
```
It's very minimal and maybe even not xdg specs compliant.

As an example of valid `.desktop` file implementation I can provide well-known neovim, which is also used from terminal: [neovim/runtime/nvim.desktop](https://github.com/neovim/neovim/blob/d27214331815324ea5762b5aa22996b9019085c6/runtime/nvim.desktop)

I can spend some time and contribute myself since the only thing to do is create file with correct settings, and maintainers for each package would update their package to pick up the file. But I have a question: Is it ok if desktop entry won't have any icon? I don't really know how this will show up in gnome and other DEs (plasma, xfce, etc) since I use app launcher which doesn't even support icons. Or maybe we can come up with some icon? Afaik bottom doesn't have any icons or logos.

Thank you for this awesome tool!

**Comment by ClementTsang** [comment]
I don't mind doing what neovim has and just including a desktop file in the repo.

Also no bottom has no icon or logo.

**Comment by ZerdoX-x** [comment]
@ClementTsang thank you for the fast response. I'll try to research how different DE's display desktop entries without icons. Probably I will send screenshots and we will think of that.

> the only way I currently imagine it being used is either a user manually copies it over, or a package maintainer makes it part of the install procedure

Yes, it's always handled by package of each package manager. Personally I use Gentoo and here is example for emerge way handling alacritty's desktop entry: https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-terms/alacritty/alacritty-0.12.2.ebuild#n334

This feature is very common and useful on linux, to have ability to launch gui applications. If you are not familiar with linux, you can think of window's desktop shortcut or start menu entry.

**Comment by ZerdoX-x** [comment]
<details>
<summary>This is how missing icons look like in DEs</summary>

Gnome
![image](https://github.com/ClementTsang/bottom/assets/49815452/86ff9df7-5b21-48c4-8a74-03c02978f6aa)

XFCE
![image](https://github.com/ClementTsang/bottom/assets/49815452/efca55ea-1f26-479f-9f0d-63cfd6802447)

KDE Plasma
![image](https://github.com/ClementTsang/bottom/assets/49815452/b70f58b9-0246-4d01-af10-9822973127c3)

Cinnamon
![image](https://github.com/ClementTsang/bottom/assets/49815452/f94f5fbe-ebc8-4a4a-b294-ee5f01243a91)

</details>

These are most popular and some of the others have similar icons. I guess it fine? Also while searching these images  I found lots of other iconless desktop shortcuts.
I think if user really won't like it, he would find a way to mask it, change icon or deal with it any other way on his side.

If that's ok, I'll try to find some time this week to read specs about desktop shortcuts and implement one for bottom. Where do you think it belongs to? `/assets/`, `/src/` or other place? Package maintainers should easily find it and also I think `.desktop` file should also be placed in linux tars on [bottom/releases](https://github.com/ClementTsang/bottom/releases) page

**Comment by ClementTsang** [comment]
I'll probably just handle this later today, looks easy enough.

**Comment by ZerdoX-x** [comment]
@ClementTsang forgot to mention `.deb` and `.rpm` installation files, maybe it's worth placing `.desktop` here too, I am not sure and don't know if they support this.
Thank you and yes, looking at the diff of the PR I can tell that you would handle it much better than me because it involves CI.
