### ISSUE TITLE
Add parameter to sort processes by memory

### ISSUE THREAD

**Issue by varaskkar** [ClementTsang/bottom#1303]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

Hello!

Every time I open bottom, I have the habit of pressing the 'm' key in the processes section to sort them by memory.
It is an option that I would find useful and would automate this step.

**Comment by ClementTsang** [comment]
Duplicate of #810, but yeah I'll look at adding it.

**Comment by varaskkar** [comment]
Glad to hear that =) and sorry for being duplicated, since there's the original issue I close this one
