### ISSUE TITLE
Left/Right in a process tree should collapse/expand the tree branches

### ISSUE THREAD

**Issue by nyurik** [ClementTsang/bottom#1304]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

Many tree viewers have a convention of opening/closing tree branches when the user hits left/right arrow keys. Please add for consistency. Thanks!

**Comment by ClementTsang** [comment]
Hm, I was originally planning on defaulting left/right in the process widget to deal with #433.

**Comment by nyurik** [comment]
I did a first pass of implementing it in #1306 -- I think toggle on + and - is a bit confusing too, so I changed it as well.

The horizontal scrolling might be good, just probably not as common for the tree view?   Perhaps ctrl+left/right?

**Comment by ClementTsang** [comment]
Closing this in favour of https://github.com/ClementTsang/bottom/issues/454 which is more general.

**Comment by nyurik** [comment]
@ClementTsang thanks for implementing the custom bindings, but please consider [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) (common in Rust) -- which is the most obvious tree behavior?

**Comment by ClementTsang** [comment]
Honestly, the first tool I think of with trees and processes that is similar to this use case is htop... which doesn't do what you describe either.

That said yes, I can consider it, as I'm aware many other programs do act like this.
