### ISSUE TITLE
Please upgrade dependency on toml_edit to branch v0.21

### ISSUE THREAD

**Issue by jonassmedegaard** [ClementTsang/bottom#1319]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for this feature/feature request.

### Describe the feature request

For the packaging of bottom in Debian, it would be quite helpful if code could migrate to use `toml_edit` v0.21.

I Debian we strive to reduce the number of concurrent library versions, and [at the moment](https://bugs.debian.org/1053955) bottom is holding back a general shift of toml_edit from v0.19 to v0.21.

**Comment by ClementTsang** [comment]
Noted, will do in a bit. Thanks for the heads up!

**Comment by jonassmedegaard** [comment]
thanks for the swift response!
