### ISSUE TITLE
Incorrect --help text about gruvbox

### ISSUE THREAD

**Issue by ShalokShalom** [ClementTsang/bottom#1340]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

NixOS

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running bottom on?

Konsole

### Are you using ZFS?

No

### What version of bottom are you running?

0.9.1

### How did you install bottom?

NixOS repos

### Describe the issue

The help text for the gruvbox theme says its a light theme. 

### What is the expected behaviour?

Text says dark theme

### What is the actual behaviour?

![Screenshot_20231129_221139](https://github.com/ClementTsang/bottom/assets/6344099/6f2c9896-8ba4-4617-9fa0-24de4315d17a)

### How can we reproduce this?

btm --help

### Additional information

Have a good day 👍🏻 

(Curious: Why do you ask, if someone has ZFS as their file system? How is that relevant?)

**Comment by ClementTsang** [comment]
The description is copy-pasted from gruvbox's own description:

> Designed as a bright theme with pastel 'retro groove' colors and light/dark mode switching in the way of [solarized](http://ethanschoonover.com/solarized). The main focus when developing gruvbox is to keep colors easily distinguishable, contrast enough and still pleasant for the eyes.

I don't really think this is an issue, but I can remove the word "bright" if you think that's confusing.

As for why do I ask for ZFS, it's because of https://github.com/ClementTsang/bottom/issues/1297. I might change that to just ask for file systems in general.
