### ISSUE TITLE
Allow for selecting the average CPU by default when starting bottom

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#1350]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for similar feature requests.

### Describe the feature request

Add a config field approximately as such:

```toml
[cpu]
default_average = true
```

**Comment by ShalokShalom** [comment]
Wonderful, thanks!
