### ISSUE TITLE
Nightly builds aren't being generated nightly

### ISSUE THREAD

**Issue by sbutcher** [ClementTsang/bottom#1351]
### Checklist

- [X] I have read and understood the above text.

### Describe the issue

It seems nightly builds aren't being triggered.

> Latest nightly release generated off of the main branch at 00:00 UTC daily

As of writing, the last nightly build was 3 weeks ago, but there have been commits to main since then.

![image](https://github.com/ClementTsang/bottom/assets/4619907/82f9db16-b4c7-4dc0-85d8-3700bfb44a77)

**Comment by ClementTsang** [comment]
Gah, seems like something broke with the job. Thanks for the heads up.

**Comment by ClementTsang** [comment]
Note to self: related to https://github.com/actions/checkout/issues/1474 most likely. Solution is I guess use checkout v3 for that container specifically.
