### ISSUE TITLE
Use thinner indicators in bar graphs.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ClementTsang/bottom#1354]
1.	### **Checklist**
	
	- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for similar feature requests.
	
	
1.	### **Describe the feature request**
	
	https://github.com/sqshq/sampler#sampler-visualization-for-any-shell-command:
	
	> ![image](https://user-images.githubusercontent.com/6069066/56404396-70b14d00-6234-11e9-93cd-54461bf40c96.gif)

	*I wanted to provide a screenshot like the undermentioned for the sake of consistency and verification, but I'm not going to bother with https://github.com/sqshq/sampler/issues/66#issuecomment-1849044614 for this.*
	
	...versus https://github.com/ClementTsang/bottom.git:
	
	> ![20231210T182820GMT](https://github.com/ClementTsang/bottom/assets/42837531/ba87f3e3-7e12-41d5-97ae-bd6f78b37a2f)

**Comment by ClementTsang** [comment]
Sorry, but I'm not sure what you're proposing here.

If you're talking about the graphs, the "thinness" of the lines is down to what font you use. For example, this is what it looks like for me:

![image](https://github.com/ClementTsang/bottom/assets/34804052/b62564ee-cc98-429c-8d63-7852348e27ee)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ClementTsang/bottom/issues/1354#issuecomment-1849069184

I use `monospace` as my font, which appears to map to ``

<details>

<blockQuote>

```.log
RokeJulianLockhart@s1e8h4:~> fc-match -s monospace
SourceCodePro-Regular.otf: "Source Code Pro" "Regular"
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
DejaVuSansMono-Bold.ttf: "DejaVu Sans Mono" "Bold"
n022003l.pfb: "Nimbus Mono L" "Regular"
luximr.ttf: "Luxi Mono" "Regular"
FreeMono.ttf: "FreeMono" "Regular"
cour.pfa: "Courier" "Regular"
FreeSans.ttf: "FreeSans" "Regular"
FreeSerif.ttf: "FreeSerif" "Regular"
SourceSans3-Regular.otf: "Source Sans 3" "Regular"
OpenSans-Regular.ttf: "Open Sans" "Regular"
DejaVuMathTeXGyre.ttf: "DejaVu Math TeX Gyre" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSerif.ttf: "DejaVu Serif" "Book"
Roboto-Regular.ttf: "Roboto" "Regular"
NotoSans-DisplayRegular.ttf: "Noto Sans" "Display Regular"
NotoSansCJKjp-Regular.otf: "Noto Sans CJK JP" "Regular"
NotoSansSymbols2-Regular.ttf: "Noto Sans Symbols2" "Regular"
NotoSansMath-Regular.ttf: "Noto Sans Math" "Regular"
Carlito-Regular.ttf: "Carlito" "Regular"
STIXGeneral-Regular.otf: "STIXGeneral" "Regular"
SyrCOMKharput.otf: "Serto Kharput" "Regular"
clacon.ttf: "Classic Console" "Regular"
s050000l.pfb: "Standard Symbols L" "Regular"
gallant12x22.ttf: "gallant12x22" "Medium"
DejaVuSerif-Italic.ttf: "DejaVu Serif" "Italic"
LiberationSerif-Italic.ttf: "Liberation Serif" "Italic"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
8x13.pcf.gz: "Misc Fixed" "Regular"
12x13ja.pcf.gz: "Misc Fixed Wide" "ja"
6x12.pcf.gz: "Misc Fixed" "SemiCondensed"
6x13.pcf.gz: "Misc Fixed" "SemiCondensed"
b14.pcf.gz: "Efont Biwidth" "Regular"
9x15.pcf.gz: "Misc Fixed" "Regular"
b16.pcf.gz: "Efont Biwidth" "Regular"
cu12.pcf.gz: "MUTT ClearlyU Wide" "Regular"
cu-alt12.pcf.gz: "MUTT ClearlyU Alternate Glyphs Wide" "Regular"
cu-pua12.pcf.gz: "MUTT ClearlyU PUA" "Regular"
MUTT-ClearlyU-Arabic-Extra-Regular.otb: "MUTT ClearlyU Arabic Extra" "Regular"
10x20.pcf.gz: "Misc Fixed" "Regular"
Arabic-Newspaper-Regular.otb: "Arabic Newspaper" "Regular"
NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"
```

</blockQuote>

</details>

...so might https://github.com/adobe-fonts/source-code-pro/issues/186#issue-287348320 or https://github.com/adobe-fonts/source-code-pro/issues/247#issue-651084465 be a solution? Or should I request something slightly different?

**Comment by ClementTsang** [comment]
> Or should I request something slightly different?

bottom will use whatever font _you_ use, it doesn't ship with a font, so there isn't anything I can do here as far as I'm aware. If you don't like how your font in your terminal looks with the braille symbols used to draw graphs, then the most I can suggest is also looking at `--dot_marker` as an alternative, or use another font for those symbols specifically.

I personally use Symbola for the braille symbols, using kitty's options to map that font for just those symbols.

The discussion in https://github.com/ClementTsang/bottom/issues/338 might be helpful as well.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ClementTsang/bottom/issues/1354#issuecomment-1849105084

That's why I asked you about the aforementioned issues, @ClementTsang — should I be requesting that my font add absent fonts if they render in the manner aforedepicted, or is something else occurring? 
I'm not an expert in Unicode, you see.

**Comment by ClementTsang** [comment]
I guess? I don't use source code so I have no idea what feature request structure they have there.

**Comment by RokeJulianLockhart** [comment]
Thank you. I'll do that.

**Comment by goyalyashpal** [comment]
> this is what it looks like for me
> @ ClementTsang at https://github.com/ClementTsang/bottom/issues/1354#issuecomment-1849069184

 hi!  yes, something like that is what i also want the line plot in bottom to look like.  and that's what it did as well several months ago.

but last month, i installed my system afresh last month, and now `btm` uses these ugly braille.

- This is what it looked like [GOOD]:
    this is not same as the `--dot_marker` flag which is even more ugly than braille.

    <img src="https://github.com/user-attachments/assets/8aed2208-21f0-4f8c-a6f9-36edaa6d5e2c" width=600px />


- This is what it looks like now with braille [BAD] :

    <img src="https://github.com/user-attachments/assets/7a110192-a615-40f5-a788-32ff22fff0d3" width=600px />

- and then with `--dot_marker` [UGLY]:

    <img src="https://github.com/user-attachments/assets/d3d7ed9e-db0c-43db-9729-b7c384da261c" width=400px />
