### ISSUE TITLE
use of unstable library feature 'matches_macro'

### ISSUE THREAD

**Issue by andys8** [ClementTsang/bottom#136]
## Describe the bug

Can't checkout the repository and install.

```
   Compiling bottom v0.3.0 (/home/as/Dev/repository/bottom)
error[E0658]: use of unstable library feature 'matches_macro'
   --> src/app.rs:233:9
    |
233 |         matches!(
    |         ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `bottom v0.3.0 (/home/as/Dev/repository/bottom)`, intermediate artifacts can be found at `/home/as/Dev/repository/bottom/target`

Caused by:
  could not compile `bottom`.

To learn more, run the command again with --verbose.
```

It looks like this is a nightly feature and I'm likely using a stable compiler. Could be a beginner mistake.

## To reproduce

_Steps on how to reproduce the behaviour:_

1. Checkout repository
2. `cargo install --path .`

## Platform

_If relevant, please provide information on:_

**Operating System:** Mint 19.3 tricia (debian)

**Terminal:** st

**Shell:** fish 3.1

**Any other relevant information (more details are always good!):**

cargo 1.41.0

**Comment by ClementTsang** [comment]
Hmm, this feature was merged into stable a while ago in [1.4.2](https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#matches).

Could you see if updating via `rustup update stable` and then building works?  If for any reason that fails let me know...

**Comment by andys8** [comment]
It was stabilized in 1.42.0 and I'm was/am using 1.41.0. That explains it. Thanks.

**Comment by ClementTsang** [comment]
Haha, no worries!
