### ISSUE TITLE
json schema support

### ISSUE THREAD

**Issue by Freed-Wu** [ClementTsang/bottom#1382]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for similar feature requests.

### Describe the feature request

Can `~/.config/bottom/bottom.toml` have a [json schema](https://json-schema.org/) and been published in [schemastore](https://www.schemastore.org/json/)? Like [alacritty](https://github.com/alacritty/alacritty)?

![Screenshot from 2024-01-11 17-31-20](https://github.com/ClementTsang/bottom/assets/32936898/2d4d2226-2259-4e6d-b164-7db6b2ef34cd)

**Comment by ClementTsang** [comment]
Hm, didn't know it supported TOML, interesting. I don't have any immediate knowledge on how to tackle this though so if anyone wants to take a swing at an initial implementation, feel free.

**Comment by Freed-Wu** [comment]
This is a reference: <https://github.com/cmhughes/latexindent.pl/issues/206>

The steps are following:

1. Create a json schema
2. Add its URL to schemastore.
