### ISSUE TITLE
Make ctrl+c behave like Esc (just like vim)

### ISSUE THREAD

**Issue by debnath-d** [ClementTsang/bottom#1397]
Currently ctrl+c exits the program, which is unexpected from a vim/neovim user perspective. I would expect ctrl+c to behave the same as Escape. Please make it the default. I would change the shortcut for myself, but currently even that is not possible (https://github.com/ClementTsang/bottom/issues/454).

**Comment by ClementTsang** [comment]
I'm not interested in changing the default behaviour, sorry. As for rebinding, yes, I'm looking into that.
