### ISSUE TITLE
Add option to generate shell completions

### ISSUE THREAD

**Issue by shilangyu** [ClementTsang/bottom#140]
## Describe the feature request

Shell completions are useful for knowing all available flags without having to constantly run `--help`

## Additional context/details

Clap already [provides generators](https://github.com/clap-rs/clap/tree/master/clap_generate) for most popular shells (Fish, Zsh, Bash, Powershell, ...) so it should be just a matter of integrating it into bottom once clap releases it.

I am willing to send a PR with this after discussing the details. 

:)

**Comment by ClementTsang** [comment]
Sure, this seems like a good idea.

**Comment by shilangyu** [comment]
I can implement it now. Would you prefer a build time or runtime generation?

Examples of how others have done it:
- [Hyperfine](https://github.com/sharkdp/hyperfine) provides the completions in the release tab (generated at build time in `build.rs`)
- [Deno](https://github.com/denoland/deno) provides a CLI flag to generate them. Example: `deno completions fish > /my/fish/dir/deno.fish`
