### ISSUE TITLE
Network RX speed being displayed as ten times the actual value

### ISSUE THREAD

**Issue by PythonGermany** [ClementTsang/bottom#1427]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Manjaro Linux 22.1.2

### What architecture are you using?

x86_64/AMD64

### What terminal(s) are you running bottom on that are experiencing the problem?

foot version: 1.16.2 +pgo +ime +graphemes -assertions

### What filesystem(s) are you using?

ext4

### What version of bottom are you running?

0.9.6

### How did you install bottom?

arch official repo and cargo

### Describe the issue

The displayed network RX speed is ten times the actual value.

### What is the expected behaviour?

The network RX speed being at ~7-9mb/s 

### What is the actual behaviour?

The displayed network RX speed is at 77.1mb/s:
![image](https://github.com/ClementTsang/bottom/assets/97847597/81cb92e6-5b5c-4d7c-ab0d-803a9ea6988b)

### How can we reproduce this?

I just installed the program ran it without any configuration changes

**Comment by ClementTsang** [comment]
:wave: Just to be sure, is the value you're looking at to compare with bottom in bytes or bits? The screenshot you're sending of bottom is showing network activity in _bits_ at the moment, and byte = bit x 8. Just clarifying as I've had a similar question before and 10x is pretty close to the 8x of converting between bits and bytes.

If so bottom defaults to bits by default for network activity, you can change it with `--network_use_bytes`.

**Comment by PythonGermany** [comment]
Oh yes, you're right. I compared it to megabytes per second. I didn't realize that the default value is in bits. I missed it when looking at the CLI help information. I am sorry, my mistake.
