### ISSUE TITLE
Wrong Swap Information on Windows11

### ISSUE THREAD

**Issue by Yikai-Liao** [ClementTsang/bottom#1433]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Windows 11

### What architecture are you using?

x86_64/AMD64

### What terminal(s) are you running bottom on that are experiencing the problem?

windows terminal with PowerShell 7.4.1

### What filesystem(s) are you using?

NTFS

### What version of bottom are you running?

0.9.6

### How did you install bottom?

cargo install bottom

### Describe the issue

`bottom` don't show the correct swap memory information on my windows11 laptop.

![image](https://github.com/ClementTsang/bottom/assets/110762732/8aee8811-c7ea-4c93-8977-4f2c50c0162e)

The used SWP memory shown in bottom is the equal to the committed memory shown in the windows task manager, where the committed memory should be the sum of used RAM and SWP. 

### What is the expected behaviour?

I expect the used SWP shown in btm equal to the cached memory shown in windows task manager.

### What is the actual behaviour?

`bottom` actually shows the committed memory in SWP on Windows 11

### How can we reproduce this?

just run bottom on Windows11 and check the windows task manager at the same time.I

**Comment by ClementTsang** [comment]
Ah yeah, I think this is known behaviour that I wanted to clarify/fix - see https://github.com/ClementTsang/bottom/issues/1052
