### ISSUE TITLE
on the top or bottom there should be some basic stats like uptime,users, as the 'top' has

### ISSUE THREAD

**Issue by mrlee14** [ClementTsang/bottom#1435]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for similar feature requests.

### Describe the feature request

Status bars bottom and top perhaps to show some more sys data...

**Comment by ClementTsang** [comment]
Kinda a dupe of https://github.com/ClementTsang/bottom/issues/235, gonna close this for now.
