### ISSUE TITLE
bcachefs support for disks widget

### ISSUE THREAD

**Issue by nrdxp** [ClementTsang/bottom#1437]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for similar feature requests.

### Describe the feature request

I have a server where I have been experimenting with the newly merged bcachefs filesystem, but I noticed that when opening bottom, there is absolutely nothing displayed in the "disks" widget as there usually is for other filesystems.

Would be nice to see ongoing disk io, similar to other multi-device filesystems like zfs

**Comment by ClementTsang** [comment]
Hm, I think this is fixed by #1373.
