### ISSUE TITLE
Request to make small release that includes the desktop file in master

### ISSUE THREAD

**Issue by colbs255** [ClementTsang/bottom#1448]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for similar feature requests.

### Describe the feature request

Hi,
This is a super minor issue, but I was wondering if we could make a small bottom release that includes the desktop file in master? Then it can be cleanly included in package repos like nix.

**Comment by ClementTsang** [comment]
You mean add the `.desktop` file to the most recent stable version releases? Like https://github.com/ClementTsang/bottom/releases/tag/0.9.6? Or did you mean like start to bundle the `.desktop` file along with the binary?

**Comment by ClementTsang** [comment]
Added the `bottom.desktop` file to the 0.9.6 release.
