### ISSUE TITLE
Ahash v0.8.3 is yanked in registry `crates-io`

### ISSUE THREAD

**Issue by eliotalanfoss** [ClementTsang/bottom#1449]
### Checklist

- [X] I have read and understood the above text.

### Describe the issue

When installing bottom using `cargo install bottom --locked` I get a the following warning:
```
warning: package `ahash v0.8.3` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```
Is there some way to update the Cargo.lock file to not use a yanked version of ahash?

**Comment by ClementTsang** [comment]
You can omit `--locked` if you prefer that, though I cannot guarantee it will as tested (though it should be fine).
