### ISSUE TITLE
Homebrew Formula linked to master, not main

### ISSUE THREAD

**Issue by TheSkyentist** [ClementTsang/bottom#1454]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

macOS 14.4.1

### What architecture are you using?

arm64

### What terminal(s) are you running bottom on that are experiencing the problem?

kitty 0.34.1

### What filesystem(s) are you using?

APFS

### What version of bottom are you running?

HEAD

### How did you install bottom?

Homebrew

### Describe the issue

Installing from HEAD with homebrew fails. Homebrew formula is linked to build from GitHub master branch, which does not exist. I'm not sure if I should PR against Homebrew, or if this is on the maintainer of this code to address. 

https://github.com/Homebrew/homebrew-core/blob/1c3325ef76a6f8fc58158a5569d47c64e280d60b/Formula/b/bottom.rb#L7

### What is the expected behaviour?

Code should build from source after cloning from HEAD. 

### What is the actual behaviour?

`fatal: Remote branch master not found in upstream origin`

### How can we reproduce this?

`brew install bottom --HEAD`

**Comment by ClementTsang** [comment]
I don't control the homebrew distribution so yeah, probably better off reporting there.

**Comment by ClementTsang** [comment]
Ended up just doing a PR there, hopefully that'll address the issue once merged.

**Comment by ClementTsang** [comment]
Closing this as the PR upstream is getting merged in a sec. Thanks for the heads-up!

**Comment by TheSkyentist** [comment]
I can confirm that installing from HEAD with homebrew works as expected, thanks!
