### ISSUE TITLE
Disk columns

### ISSUE THREAD

**Issue by gepbird** [ClementTsang/bottom#1480]
### Checklist

- [X] I've looked through [the documentation](https://clementtsang.github.io/bottom/nightly/) and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue+label%3Afeature) for similar feature requests.

### Describe the feature request

Similarly to how we can customize `processes.column`, there could be `disks.columns`.

I'm trying to create a layout where I allocate a smaller space to the disk widget, but I only see the first 3 column: Disk, Mount and Used. It would be nice if I could change it to Mount, Used% and R/s for example.

**Comment by ClementTsang** [comment]
Huh, I thought I had added that, but I guess not. Yeah, that should be easy to do.
