### ISSUE TITLE
Disk widget not working on macOS

### ISSUE THREAD

**Issue by smacintyre** [ClementTsang/bottom#151]
## Describe the bug

The "Disk" widget does not show anything. This is a fresh install with all default options.

<img width="1562" alt="Screen Shot 2563-05-10 at 23 55 04" src="https://user-images.githubusercontent.com/361689/81505506-d7127d00-9319-11ea-9d06-118f780c51c8.png">

## To reproduce

1. `brew tap clementtsang/bottom`
2. `brew install bottom`
3. `btm`

## Platform

**Operating System:** macOS Catalina 10.15.5 Beta (19F83c)

**Terminal:** iTerm2 3.3.9

**Shell:** fish, version 3.1.2

**bottom version (use `btm -V`):** bottom 0.4.1

**Comment by ClementTsang** [comment]
Hmm, I'll take a look.
