### ISSUE TITLE
RUSTSEC-2024-0019: Vulnerability in mio

### ISSUE THREAD

**Issue by bowlofeggs** [ClementTsang/bottom#1521]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What version of bottom are you running?

0.9.7

### How did you install bottom?

Gentoo ebuild (but this affects Windows only).

### Describe the issue

I noticed that the latest 0.9.7 release of bottom is using `mio-0.8.8`, which has this RUSTSEC: https://rustsec.org/advisories/RUSTSEC-2024-0019

According to that post, only Windows is affected, but I do see that the Readme says Windows is supported.

This is already fixed on main, so will be fixed on the next release from main automatically (or there could be a `0.9.8` if you prefer).

### What is the expected behaviour?

mio should be on 0.8.11 or newer.

### What is the actual behaviour?

It's on 0.8.8.

### How can we reproduce this?

`cargo tree -i mio`

**Comment by ClementTsang** [comment]
Thanks for the heads up, should be fixed when I release 0.10.0.
