### ISSUE TITLE
Help message is distorted

### ISSUE THREAD

**Issue by Dialga** [ClementTsang/bottom#1525]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Arch Linux x86_64

### What architecture are you using?

x86_64/AMD64

### What terminal(s) are you running bottom on that are experiencing the problem?

alacritty, konsole, rio

### What filesystem(s) are you using?

Other (please specify in the Additional Information area at the end)"

### What version of bottom are you running?

0.10.0

### How did you install bottom?

Arch repos

### Describe the issue

Help message is distorted, misaligned.

### What is the expected behaviour?

Help message that is clearly formatted, not broken up on every second line.

### What is the actual behaviour?

![image](https://github.com/user-attachments/assets/23abda9c-401c-4e00-a3af-a5bd57974c37)
![image](https://github.com/user-attachments/assets/d0429a3e-7f6a-446d-9183-697084375007)

### How can we reproduce this?

`btm -h` on Arch Linux.

**Comment by ClementTsang** [comment]
Hm, I'll take a look at this after work.

**Comment by ClementTsang** [comment]
Actually, found the problem - I can fix this pretty quickly.
