### ISSUE TITLE
debian installer downloads "Not Found"

### ISSUE THREAD

**Issue by Alpha-404** [ClementTsang/bottom#1549]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Ubuntu 24.04 LTS

### What architecture are you using?

x86_64/AMD64

### What filesystem(s) are you using?

ext4

### What version of bottom are you running?

not installed

### How did you install bottom?

curl -LO https://github.com/ClementTsang/bottom/releases/download/0.10.2/bottom_0.10.2_amd64.deb
sudo dpkg -i bottom_0.10.2_amd64.deb

### Describe the issue

curl downloads "Not Found"

### What is the expected behaviour?

downloads actual file

### What is the actual behaviour?

downloads file saying "Not Found"

### How can we reproduce this?

Run curl -LO https://github.com/ClementTsang/bottom/releases/download/0.10.2/bottom_0.10.2_amd64.deb
from the readme

**Comment by ClementTsang** [comment]
Bleh, seems like the link has a `-1` added to it now: https://github.com/ClementTsang/bottom/releases/download/0.10.2/bottom_0.10.2-1_amd64.deb

Will fix the README in a sec.

**Comment by ClementTsang** [comment]
Should be fixed, thanks for the heads up!
