### ISSUE TITLE
No GPU temps (Nvidia) after updating to 0.10

### ISSUE THREAD

**Issue by t-kowalewski** [ClementTsang/bottom#1554]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

EndeavourOS - 6.6.44-3 LTS

### What architecture are you using?

x86_64/AMD64

### What terminal(s) are you running bottom on that are experiencing the problem?

Konsole 24.05.2

### What filesystem(s) are you using?

ext4

### What version of bottom are you running?

0.10.2

### How did you install bottom?

official Arch repo

### Describe the issue

bottom stopped displaying GPU temperature after updating it from version 0.9.6
Used GPU - mobile Nvidia GTX 660m
![bottom](https://github.com/user-attachments/assets/68659a6a-8bf9-496e-ac51-3452366a3d5d)

### What is the expected behaviour?

bottom showing GPU temperature in according section

### What is the actual behaviour?

bottom doesn't display GPU temps

### How can we reproduce this?

Run bottom on an Arch-based system with discrete mobile GPU from Nvidia

**Comment by ClementTsang** [comment]
Hmm, I can't easily troubleshoot this but I'll take a look.

**Comment by ClementTsang** [comment]
Some quick things to check first:

- If you expand the temperature table (`e`) does it show up on the list?

> mobile

Hm, if you make the dGPU do some work, does it show up? Just curious as there _is_ some code to purposely avoid checking temperatures of asleep devices to avoid constantly waking them up - in that case, it will just be given a temperature of "N/A".

**Comment by t-kowalewski** [comment]
Thanks for the reply. No, unfortunately extended view doesn't show it either.
![btm](https://github.com/user-attachments/assets/7778b672-96c2-4812-b42e-1e0bb1c51ce6)
Granted, it's a pretty old GPU running on legacy drivers, but the sensor still outputs the information as expected. Just not in bottom :/
![nvidia-smi](https://github.com/user-attachments/assets/04541fe2-8622-4f61-afe6-0810f48597d6)

**Comment by ClementTsang** [comment]
Hm, weird. I did bump `nvml-wrapper` in between updates so it's possible something changed between versions, I'll see if I can figure it out. Thanks for the extra info.

**Comment by ClementTsang** [comment]
Also, was it properly showing a temperature reading in 0.9.6 (e.g. not just "N/A" or something empty)? And if so, could you show it? Thanks.

**Comment by shurizzle** [comment]
The "issue" (apparently, it’s intended behavior) was introduced by commit e4a6e751ec60f0f2363e0a3493a4f15c1ddc1d85 (issue #1276). By default, all GPU information is disabled, so you need to enable it using the `enable_gpu` flag. Perhaps it would be better to enable it by default?

**Comment by ClementTsang** [comment]
🤦 yeah that would do it, I forgot we had a change that bundled that all together. I had thought we had changed it to enable GPU info by default, but I guess that slipped through the cracks and I misremembered. I'll look into changing that.
