### ISSUE TITLE
Improve CPU table/display

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#156]
## Describe the feature request

_Why should we consider this feature request? Describe why, and/or how you think this feature will solve the issue, or overall improve the application:_

As mentioned in https://github.com/ClementTsang/bottom/issues/132, it's hard to use the CPU chart with many cores.

Seems like it's worth doing a bit of an overhaul with the CPU display.  Admittedly, the current design is a bit of an afterthought.

Ideas:

- [ ] ~~Bring in `--basic`'s bar to give a better indication of usage within the legend section.  Option to disable is needed.  Test if it looks good at all.  Maybe will do, maybe won't.~~ Not really a fan of how it might look

- [x] ~~Redo the whole "hiding cores" thing.  It's a bit dumb and unintuitive.  Not sure what to make it into though, but something to show specific cores easily, and hide others is something I could see being useful.~~

    Removed the entire "hiding cores" thing, use below as a solution.  May come up with something better.

- [x] Currently thinking of making scrolling through an entry *only* show that entry, so it's obvious what line is what core and be clear.

- [ ] Searching by core, perhaps?  Or some way of instantly jumping to a core - something like vim line jumping (don't we love just using vim commands)?

- [ ] Adding a "multi-graph" solution - inspired by, of all things, Windows task manager.  This would hopefully be an easier way to see multiple core performance at once.

- [ ] Considering a simple multi-core visualization as well to quickly show usage.  Again, idea "inspired" by Windows task manager

## Additional context/details

_Provide any additional context or details here. What needs to be done, why, etc:_

**Comment by mfarrugi** [comment]
For what it's worth, seeing the total cpu usage and/or the Use% of each core is more relevant (so worth more space!) than the graph when there are many cores. The graph ends up being noise when not zoomed in.

**Comment by qaako** [comment]
> For what it's worth, seeing the total cpu usage and/or the Use% of each core is more relevant (so worth more space!) than the graph when there are many cores. The graph ends up being noise when not zoomed in.

i agree, is there a way to just show cpu usage and hide the graph? sorry to bump, i love this app and would love to know. I cant see % value of cpu usage in windowed mode... too many widgets taking up space so only the useless graph shows, and the % cpu usage disapppears

**Comment by ClementTsang** [comment]
That isn't a feature atm, sorry. Feel free to open a new issue for that.

**Comment by ClementTsang** [comment]
Opened one to move discussion to if needed: https://github.com/ClementTsang/bottom/issues/1520
