### ISSUE TITLE
The config option "theme" doesn't work

### ISSUE THREAD

**Issue by dtcyganok** [ClementTsang/bottom#1571]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

Arch Linux 6.10.6

### What architecture are you using?

x86_64/AMD64

### What terminal(s) are you running bottom on that are experiencing the problem?

kitty 0.36.1

### What filesystem(s) are you using?

ext4

### What version of bottom are you running?

0.10.2

### How did you install bottom?

From official Arch Linux repos

### Describe the issue

After v0.10.2 has been released the config option `color` stopped working, but the new presumptive option `theme` doesn't work either.

### What is the expected behaviour?

Bottom respects the config option `theme`.

### What is the actual behaviour?

Bottom doesn't respect the config option `theme`.

### How can we reproduce this?

Edit `~/.config/bottom/bottom.toml`:

```toml
[flags]
theme = "nord-light"
```

Then run bottom and you will see that the running instance has the default theme.

**Comment by ClementTsang** [comment]
`theme` is no longer under `[flags]`. You have to place it under `[styles]`. For example,

```toml
[flags]
# Your other flag options

[styles]
theme = "nord-light"
```

Could you try that and report back?

**Comment by dtcyganok** [comment]
It works perfectly! Thanks!

I would say it wasn't obvious, and I did see such an example in the documentation.
It would be nice to have a configuration file description.

**Comment by ClementTsang** [comment]
Yeah, looks like I forgot to update a few places. Sorry for the inconvenience.
