### ISSUE TITLE
centos7 does not show the Internet speed

### ISSUE THREAD

**Issue by JFallen** [ClementTsang/bottom#1626]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

centos7.9

### What architecture are you using?

x86

### What terminal(s) are you running bottom on that are experiencing the problem?

centos7.9

### (Optional) What filesystem(s) are you using?

ext4

### What version of bottom are you running?

0.10.2

### How did you install bottom?

bottom_x86_64-unknown-linux-musl.tar.gz

### Describe the issue

The network is not showing the speed
![image](https://github.com/user-attachments/assets/fe6c26c1-e6bf-42e3-aeb1-141febd9cd1c)

### What is the expected behaviour?

Display the network speed

### What is the actual behaviour?

The Internet speed is not displayed

### How can we reproduce this?

justt run btm in the centos7.9

**Comment by ClementTsang** [comment]
The legend is automatically hidden if there isn't enough room to display it, so could you try opening btm in a larger window, or expand the network widget with the `e` key when selected, to make sure it isn't just that?

**Comment by JFallen** [comment]
i expand the window,the speed showed up  ,thank you
