### ISSUE TITLE
GPU% in processes always shows 0% on NixOS

### ISSUE THREAD

**Issue by gepbird** [ClementTsang/bottom#1629]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

NixOS (nixpkgs-unstable)

### What architecture are you using?

x86_64/AMD64

### What terminal(s) are you running bottom on that are experiencing the problem?

xfce4-terminal

### (Optional) What filesystem(s) are you using?

Btrfs

### What version of bottom are you running?

0.10.2

### How did you install bottom?

Installed 0.10.2 with `nix shell nixpkgs/nixos-unstable#bottom`.
Also compiled on [main](https://github.com/ClementTsang/bottom/commit/196d6d18c6f2e43f6fd68990b8eae5f7ec1f20a6) with rustc 1.82.0.

### Describe the issue

Bottom shows 0% GPU% and GMem% usage for each process when some applications are using the GPU.

### What is the expected behaviour?

Show the correct values, or somehow let the user know that there was an issue getting these values.

### What is the actual behaviour?

Shows 0% for each process's GPU% and GMem%.

### How can we reproduce this?

1. Create `bottom-gpu-issue.toml` config file:
```toml
[flags]
enable_gpu = true

[processes]
columns = ["name", "cpu%", "gmem%", "gpu%"]
 ```
2. Run `btm --config_location=./bottom-gpu-issue.toml`

### Additional information

`nvtop` correctly displays GPU values for each processes.
GPU: GeForce GTX 1050 Ti
I'm running xorg.

**Comment by gepbird** [comment]
This explains the issue https://github.com/ClementTsang/bottom/blob/main/src/data_collection/processes/linux.rs#L267

**Comment by ClementTsang** [comment]
Gah, thanks for catching that. Will fix.

**Comment by ClementTsang** [comment]
Hmm. That _should_ be set elsewhere, however: https://github.com/ClementTsang/bottom/blob/main/src/data_collection/nvidia.rs#L117

**Comment by jamartin9** [comment]
Tested the default config (with gpu proccess columns and `process_memory_as_value`) on main using kde wayland with nvidia driver v550.120 on a gtx980.

The same processes were in the list when sorted by `gmem > 0` as nvtop and nvidia-smi. (percentage for either could be less than 1%)

nvidia gpu process utilization can be [inconsistent](https://github.com/Syllo/nvtop/blob/0316ce19581c3d8543cf6aa312d1569c56ca754f/src/extract_gpuinfo_nvidia.c#L703) at times but both are using the same process utilization stats from nvml...

**Comment by gepbird** [comment]
@jamartin9 Big thanks for trying to help, no need to apologize :)

Both with the default nix package and building bottom from source, I see the GPU columns (is there a separate widget for GPU or that's just a typo?). However it's all zeros, here's a comparison with nvtop:

![2024-11-30_08-54](https://github.com/user-attachments/assets/2e056276-e246-428d-8a13-bf5867bc4848)


<details><summary>Config used: bottom-gpu-issue.toml</summary>

```toml
[flags]
enable_gpu = true

[processes]
columns = ["name", "cpu%", "gmem%", "gpu%"]

[[row]]
  [[row.child]]
  type="process"
```

 I will try with adding zenith library soon.

**Comment by gepbird** [comment]
@jamartin9 

Oooh zenith is not a library but another resource monitor, I feel silly now. It works though, I'll try the same thing with bottom, again huge thanks for your research!

![2024-11-30_18-27](https://github.com/user-attachments/assets/7cb8ca43-8d84-4d4c-bca3-e099bea88106)

**Comment by gepbird** [comment]
GPU features work when running bottom with this environment variable: `LD_LIBRARY_PATH=/run/opengl-driver/lib`

![2024-11-30_19-13](https://github.com/user-attachments/assets/f4e9bd85-9dbf-4381-995f-e22f57551ce1)

Turns out it was a nix specific issue, I will make a PR upstream soon.

**Comment by magnusrodseth** [comment]
@gepbird Could you provide an update on when this might be merged? I’m encountering the same issue on my MacBook Pro, **not using NixOS**. Despite running a process that I know utilizes the GPU, both `gmem%` and `gpu%` consistently show 0.

**Comment by magnusrodseth** [comment]
@gepbird I do not use the Nix package manager, nor do I use NixOS.

**Comment by gepbird** [comment]
@ClementTsang @jamartin9 any idea why it doesn't work on darwin for @magnusrodseth?

**Comment by jamartin9** [comment]
> @jamartin9 any idea why it doesn't work on darwin 
> MacBook Pro

The **Nvidia** GPU library we are using (NVML) **only** supports **Windows**/**Linux** according to the [API docs](https://docs.nvidia.com/deploy/nvml-api/nvml-api-reference.html).
There is a PR for **AMD** but it is **Linux only** atm.
There is **no** support for integrated **Intel** GPUs.
There is **no** support for **M1** integrated GPUs. 

I do not have access to Apple hardware or EGPUs to assist.

**Comment by magnusrodseth** [comment]
@gepbird @jamartin9 I understand - it's all good. Nevertheless, great CLI tool ❤️ 

For future reference:
* `btm` installed using `brew`
* Version: `0.10.2`
