### ISSUE TITLE
bottom 0.10.2 - bottom.toml theme doesn't set theme & gruvbox-light theme looks wrong

### ISSUE THREAD

**Issue by SpreadiesInSpace** [ClementTsang/bottom#1631]
### Checklist

- [X] I've looked through the [troubleshooting docs](https://clementtsang.github.io/bottom/nightly/troubleshooting), [the known problems list](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### What operating system and version are you using?

LMDE 6

### What terminal(s) are you running bottom on that are experiencing the problem?

gnome-terminal 3.46.8

### What version of bottom are you running?

0.10.2

### How did you install bottom?

installed bottom through .deb package from releases

### Describe the issue

When configuring bottom.toml for 0.10.2, the theme value doesn't set the theme.

Version 0.10.2's gruvbox-light theme uses light colors, so it looks wrong on light themed terminals.

### What is the expected behaviour?

Setting theme in bottom.toml should change the theme accordingly. In version 0.9.5, the color value was used to set the theme, and it worked correctly back then.

Gruvbox-light should use darker colors to complement a light themed terminal. Version 0.9.5 had the correct looking gruvbox-light theme.

### What is the actual behaviour?

After setting the theme in bottom.toml to anything other than default for 0.10.2, btm still uses default theme.

When specifying btm --theme gruvbox-light for 0.10.2 the theme still uses light colors, so you can't read anything when the terminal uses a light theme.

### How can we reproduce this?

Already specified above.

**Comment by ClementTsang** [comment]
Hm, that looks like a bug, think I forgot to set the border colours when refactoring. Will look into and fix.
