### ISSUE TITLE
Add a way to display memory values rather than percentage

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#169]
## Describe the feature request

_Why should we consider this feature request? Describe why, and/or how you think this feature will solve the issue, or overall improve the application:_

See https://github.com/ClementTsang/bottom/issues/19#issuecomment-631586511 for original idea.

This change shouldn't be hard at all to just simply do, but the main issue will be how to integrate it into the process table.  Do we just slap in a new field (the easy way out)?  Make it toggleable with mem%?  Or eventually, just make it entirely user-controllable if we design the process bar to be more customizable?

**Comment by tommywalkie** [comment]
For educational purposes, I was trying to make it available as a flag for consistency on a fork, kinda similar to the temperature data type.
https://github.com/ClementTsang/bottom/blob/3ffa437af396407aa647d90bc925fa79e885a83e/src/main.rs#L72-L76

**Comment by ClementTsang** [comment]
Hmm.  I was thinking of just doing that initially, but I was also thinking it might be better to be able to toggle it within the application.
