### ISSUE TITLE
Add battery flag option to config file

### ISSUE THREAD

**Issue by forrest-keller** [ClementTsang/bottom#174]
## Describe the feature request

The `--battery` flag should be an option in the config file.

**Comment by ClementTsang** [comment]
It actually already is one, I just seem to have forgotten to document it in the README... I'll fix that real quick.

**Comment by ClementTsang** [comment]
"Fixed" by commit 777a5fb9f21444a6b13102c5db0aef45c07d2c34.  Closing unless there's an issue with it (option works fine for me on the current release version).
