### ISSUE TITLE
Can't switch panels on Linux virtual terminals

### ISSUE THREAD

**Issue by DianaNites** [ClementTsang/bottom#180]
## Describe the bug

On a bare linux text virtual terminal, `btm` runs and looks fine but it's impossible to switch to any of the other panels using `ctrl` or `shift` arrow keys, nothing happens.

## To reproduce

_Steps on how to reproduce the behaviour:_

1. Go to a text VT
2. Run `btm`
3. Attempt to select/switch to any other panel using the appropriate hotkeys.

## Platform

_If relevant, please provide information on:_

**Operating System:** Linux, kernel 5.7.12-arch1-1

**Terminal:** Kernel VT

**Shell:** Fish, and Bash.

**bottom version (use `btm -V`):** 0.4.5

**Comment by ClementTsang** [comment]
Hmm, do HJKL not work either, as a temporary workaround for now?

I'll take a look at this in a bit and see if I can replicate.

**Comment by ClementTsang** [comment]
Alright, I seem to be able to replicate this running off of an Arch VM.  `HJKL` is a current workaround for me in this case so see if that works, I'll see if I can do anything in regards to this.

**Comment by ClementTsang** [comment]
Took a peek w/ debug logs, it seems that, at least for the issue on my side, the library I'm using to interface with the terminal cannot detect modifier keys along with arrow keys in this situation.  However, it *can* detect modifier keys with letter keys, hence why `HJKL` still work.

I don't really know if I can fix this problem.  I'll dig a bit deeper but it might be a problem I can't really fix here, especially when it works fine on terminal emulators.

**Comment by DianaNites** [comment]
Oh I didn't notice those were an option at first. HJKL work, but are extremely confusing and non-intuitive to use, I have no idea what key is supposed to work in what direction.

**Comment by ClementTsang** [comment]
Sorry about that, it's supposed to emulate Vim controls.  H is left, J is down, K is up, L is left.

**Comment by ClementTsang** [comment]
Just so I'm more clear on your situation, are you trying to run this on Arch's built in default console?

**Comment by DianaNites** [comment]
> My assumption so far has been just the default Linux console you get if you were to, say, run Arch w/o any DE/WM?

Yes thats correct. I'll note that it's not normal usage for me though, I was using bottom as part of an (unsuccessful) attempt to repair a frozen desktop, and at the time I only really wanted the process list, which is the default selection and worked fine anyway, lol.

HJKL should be fine as a workaround, I just didn't notice at the time.

> I could do something like WASD + some modifier

That could be nice, i'd find it more intuitive for sure

**Comment by ClementTsang** [comment]
Alright, I'll add that as an alternative.  Thanks for the feedback!
