### ISSUE TITLE
Build fail on aarch64

### ISSUE THREAD

**Issue by ggardet** [ClementTsang/bottom#191]
## Describe the bug
While trying to build for aarch64, I get the following error:
```
[  359s] error[E0308]: mismatched types
[  359s]   --> /home/abuild/rpmbuild/BUILD/bottom-0.4.3/vendor/heim-host/src/sys/linux/users/other.rs:79:25
[  359s]    |
[  359s] 79 |             session_id: entry.ut_session,
[  359s]    |                         ^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
[  359s] 
[  359s] error: aborting due to previous error
[  359s] 
[  359s] For more information about this error, try `rustc --explain E0308`.
[  359s] error: could not compile `heim-host`.
```

## To reproduce
Try to build for aarch64.

## Platform

**Operating System:**
openSUSE Tumbleweed - aarch64

**Terminal:**

**Shell:**

**bottom version (use `btm -V`):**
0.4.3

**Any other relevant information (more details are always good!):**

**Comment by Titaniumtown** [comment]
I get the exact same error.

**Comment by ClementTsang** [comment]
@ggardet @Titaniumtown could you try cloning the master branch and see if you can get it to build?  I've gotten it to build now on a Raspberry Pi 4 and an Opensuse Tumbleweed Aarch64 VM.

Note it's not perfect yet (for example, disk read/s and write/s doesn't work yet, I have to implement that myself), but it should at least compile and mostly work from testing it a bit.

**Comment by ggardet** [comment]
It complains about `anyhow` missing:
```
 error: no matching package named `anyhow` found
```
Is it a new dependency?

**Comment by ClementTsang** [comment]
@ggardet I'm using it for error handling, yes.

**Comment by ggardet** [comment]
> @ggardet I'm using it for error handling, yes.

I am not good enough in rust packaging to add it to the vendor archive to build it in Open Build Service.
But if you have it built on openSUSE Tumbleweed aarch64, that's fine then.

**Comment by ClementTsang** [comment]
Going to close this for now, since while I'm still not officially supporting ARM builds *yet*, it should build correctly now, and I run Travis checks to ensure it will.  Feel free to re-open or create a new issue if it fails again, or doesn't properly work.
