### ISSUE TITLE
Show process user

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#236]
## Describe the feature request

_Why should we consider this feature request? Describe why, and/or how you think this feature will solve the issue, or overall improve the application:_

Show who owns the process in the processes widget.

## Additional context/details

_Provide any additional context or details here. What needs to be done, why, etc:_

**Comment by mfarrugi** [comment]
This jumped out at me as missing, a lot of my top usage is to answer "who is drowning this machine?".
