### ISSUE TITLE
Feature request: Sending arbitrary signals to processes

### ISSUE THREAD

**Issue by LlinksRechts** [ClementTsang/bottom#251]
### Describe the feature request

Most of the time, killing a process is sufficient, but sometimes, at least the differentiation between `kill -15` and `kill -9` is important; therefore, I propose replacing the 'Confirm kill process' menu with a selection of 1-64 (or cancel) for the different signals, maybe with 15 (sigterm) preselected. A similar approach can be found in the `htop` tool.

### Additional context/details

I am aware that windows does not really have the concept of 'kill signals'; therefore, either make this a unix only feature, or try to emulate kill signals using different windows messages (https://stackoverflow.com/a/140394/3999297), which would at least enable a differentiation between 'ask nicely' and 'force'. In any case, there would probably have to be a distinction between windows and unix though.

**Comment by ClementTsang** [comment]
Would definitely like to add this in the future.
