### ISSUE TITLE
Installation with nix

### ISSUE THREAD

**Issue by andys8** [ClementTsang/bottom#254]
### Describe the feature request

It would be nice, if `bottom` can be installed with `nix`.

https://nixos.org

### Additional context/details

I would prefer this installation method, maybe others too.
I hope I can help with adding the package.

Here is an example, of a `cargo` based application for nix.
https://github.com/NixOS/nixpkgs/blob/dd2ecd07120fc82687e504fce2f91065847e69f2/pkgs/tools/security/bitwarden_rs/default.nix

**Comment by andys8** [comment]
I added it to my setup like this: https://github.com/andys8/dotfiles/blob/9f76e55c3ffec24eb0436825cc79d118a74686da/nix/bottom.nix

Adding it to would look similar: https://github.com/NixOS/nixpkgs

**Comment by ClementTsang** [comment]
@andys8 does https://github.com/NixOS/nixpkgs/pull/99126 resolve this request?

**Comment by andys8** [comment]
Looking very good!
