### ISSUE TITLE
Outdated dependencies don't compile on latest Rust

### ISSUE THREAD

**Issue by danielzgtg** [ClementTsang/bottom#271]
### Describe the bug

Our outdated version of the transitive dependency crate `uom` doesn't compile (iliekturtles/uom#210) on the latest Rust nightly. The direct dependencies should be updated so that the `uom` crate's version is raised up to "0.30.0"

I know that `bottom` only supports stable, but the fix is just incrementing a few numbers and the underlying cause in rustc is going to be permanent, which means `bottom` will need to be updated later anyway.

### To reproduce

1. Run `cargo install bottom`
2. Observe that it errors

### bottom version (use `btm -V`)

```
Command 'btm' not found, did you mean:

  command 'etm' from deb etm (3.2.30-1)
  command 'tm' from deb libtm-perl (1.56-10)
  command 'bhm' from deb postal (0.75build1)
  command 'ttm' from deb ttm (4.12+ds-2)
  command 'b2m' from deb xemacs21-bin (21.4.24-9)
  command 'bpm' from deb bpm-tools (0.3-4)
  command 'bti' from deb bti (034-4build1)
  command 'bts' from deb devscripts (2.20.2ubuntu2)
  command 'bam' from deb bam (0.5.1-2)
  command 'btt' from deb blktrace (1.2.0-5)

Try: sudo apt install <deb name>
```

### Platform

**Operating system and OS version:** Ubuntu 20.04.1 LTS

**Terminal (i.e. urxvt, kitty, etc.):** Konsole

**Shell (i.e. zsh, bash, etc.):** bash

_If relevant, please provide information on:_

**System info (RAM, SWAP, etc.):** 16 GiB

**Rust version (if building yourself):** `rustc 1.49.0-nightly (31530e5d1 2020-10-20)`

**Comment by ClementTsang** [comment]
Thanks for the heads-up, I'll fix this in a bit.

**Comment by ClementTsang** [comment]
Just FYI though, I don't directly use uom, the libraries I use do.

**Comment by ClementTsang** [comment]
I've updated one of the libraries that depend on uom (battery), but it seems I might have to wait for another (heim) to release an update that includes this commit that updates uom: https://github.com/heim-rs/heim/commit/e22e23570c8fcc66a922ca9252f3f6643032ba79
