### ISSUE TITLE
Battery status not working on Windows

### ISSUE THREAD

**Issue by rashil2000** [ClementTsang/bottom#273]
### Describe the bug

Battery status is not showing up on Windows 10, whether running as administrator or otherwise. It just displays 'No data found for this battery'. I only have a single battery. 

### To reproduce

Run `btm` with the `--battery` flag. 

### bottom version (use `btm -V`)
0.4.7

### Platform

**Operating system and OS version: Windows 10.0.19042**

**Terminal (i.e. urxvt, kitty, etc.): ConHost, Windows Terminal**

**Shell (i.e. zsh, bash, etc.): PowerShell, CMD**

## Additional context

I use [Starship](https://github.com/starship/starship) (also written in Rust), and battery works fine there. Starship also uses the 'battery' crate (although it's the latest version 0.7.7). So I don't think the issue is with Rust or that crate.

**Comment by ClementTsang** [comment]
Thanks for the heads up, I'll take a look.

**Comment by ClementTsang** [comment]
Tried on two different laptops and they both seem to work fine... not sure what's not working on your end.

**Comment by ClementTsang** [comment]
If possible, could you try cloning the current master branch and see if there are issues there?  If there are, could you also run:

```bash
cargo run -- --debug
```

and paste the debug file you generate?

**Comment by rashil2000** [comment]
For building, which Rust toolchain should I use? The GNU one or the MSVC one? Could you tell me the exact details on how to get Rust up and running on Windows (so that I can exactly replicate how you build it)?

**Comment by ClementTsang** [comment]
Pretty sure both should work, though I currently use MSVC for release builds.

Installing Rust on Windows: https://www.rust-lang.org/tools/install

Then install stable (I forget if they do this by default):
`rustup install stable`

Then run:
`cargo run -- --debug`
in the cloned repo directory.

**Comment by rashil2000** [comment]
Here's the `bottom_debug.log` file https://www.pastiebin.com/5f99aace898db

**Comment by ClementTsang** [comment]
Hmm, well if it's fixed on master then I think it's fine?  I aim to push 0.5.0 out soon anyways.
