### ISSUE TITLE
Contents of RAM widget are shown outside its borders

### ISSUE THREAD

**Issue by ShrykeWindgrace** [ClementTsang/bottom#276]
### Describe the bug
The graphs from the default RAM widget are partially outside the borders of its widget and overlap with the temperature widget.

### Screenshot
![image](https://user-images.githubusercontent.com/6421233/97182866-59dea580-179d-11eb-8ac0-1f6d10a34af5.png)

### bottom version (use `btm -V`)
```bash
$ btm -V
bottom 0.4.7
```

### bottom config file (if one is used)
NA

### Installation method
`nix-shell -p bottom`, then `btm`

### Platform
Ubuntu-18 with nix-as-package-manager; Konsole + tmux + zsh, tmux panel is maximized

**Comment by ClementTsang** [comment]
Cool, I can replicate this with that exact setup.  I'll look into it now.

**Comment by ClementTsang** [comment]
@ShrykeWindgrace for now, it seems like the dots option (`-m`) works fine for me.

![image](https://user-images.githubusercontent.com/34804052/97947225-a0627000-1d5a-11eb-8384-ed903d44b673.png)

**Comment by ClementTsang** [comment]
Seems to be an issue with tui-rs:
![image](https://user-images.githubusercontent.com/34804052/97951241-83806980-1d67-11eb-8fd9-c97ede563b13.png)

I'll report it upstream.

**Comment by ShrykeWindgrace** [comment]
Hi!

Thank you for your thorough investigation! Unfortunately, I no longer have physical access to my linux machine thanks to a lockdown.
- when I ssh to my machine (win10 + conEmu + gitBash), both Braille and dot rendering of the chart work fine
- if I ssh there with mobaXterm (if I understand correctly, that's a `ssh -X` with some bells and whistles), `btm -m` seems to do the trick in Konsole
- I also tested with `tilix` and `alacritty` as emulators, `btm` seems to work fine, too.

On a side note, which version of Konsole did you test? Mine was rather outdated (17.12.3). I re-tested with a more recent 20.08.2, Braille rendering seems ok. However, this version itself has other problems, but they seem to be outside the scope of this  issue.

**Comment by ClementTsang** [comment]
> Which version of Konsole did you test?

Whatever was the newest yesterday via `apt-get install Konsole` on Ubuntu 18.04.  Seems to be 4:17.12.3-1ubuntu1?
