### ISSUE TITLE
Feature request: Add network interface filter

### ISSUE THREAD

**Issue by aofei** [ClementTsang/bottom#279]
### Describe the feature request

Add a `network_names` (string slice, the default is empty, and empty means all) configuration item to specify the network interfaces that need to be calculated by `btm`.

Usage:

```toml
network_names = ["eth0", "eth1"]
```

### Additional context/details

At present, `btm` takes all network interfaces into consideration in traffic calculation. Of course, there's nothing wrong with it. But we must admit that there're some flaws in doing so. For example, there may be some network interfaces that people want to ignore, such as those created by `docker`. So it seems reasonable to add a network interface filter.

https://github.com/ClementTsang/bottom/blob/0c21cba1899c97b8fb74130e620fa811abe15f0f/src/app/data_harvester/network.rs#L33-L37

**Comment by ClementTsang** [comment]
Yep, that sounds good.  I plan on eventually allowing the ability to display per interface so this would tie nicely into that.
