### ISSUE TITLE
Compilation error when running either `cargo +nightly install bottom --locked` or `yay -S bottom`

### ISSUE THREAD

**Issue by KSXGitHub** [ClementTsang/bottom#280]
### Describe the bug

I tried to build bottom from source on GitHub CI, but it fails to compile: [logs](https://gist.github.com/KSXGitHub/8caaf8f51dae8593a7af8f2fc7b6d6b5)

**Comment by ClementTsang** [comment]
It's broken on newest nightly due to uom.  See https://github.com/ClementTsang/bottom/issues/271.
