### ISSUE TITLE
Basic view shows 0% average CPU usage

### ISSUE THREAD

**Issue by ReagentX** [ClementTsang/bottom#288]
### Describe the bug

`btm -b` shows 0% for average CPU usage, even though cores show usage.

### To reproduce

1. Run `btm -b`

<img width="842" alt="image" src="https://user-images.githubusercontent.com/1920666/97930818-3fc33b00-1d3a-11eb-9f52-5c45f117dc37.png">

### bottom version (use `btm -V`)

`bottom 0.4.7`

### bottom config file (if one is used)

N/A

### Installation method

`brew`

**Operating system and OS version:**

- macOS 10.15.7 (19H2)
- alacritty 0.5.0 (a6681e3)
- zsh 5.7.1 (x86_64-apple-darwin19.0)

**Comment by ClementTsang** [comment]
Huh.

Didn't expect that to be a problem.  I'll look into it.
