### ISSUE TITLE
Cannot compile v0.2.1: cannot find derive macro Deserialize in this scope

### ISSUE THREAD

**Issue by joeydumont** [ClementTsang/bottom#30]
## Describe the bug

`cargo install bottom` leads to a compilation error where Deserialize is not in scope. Maybe a missing feature?

```
   Compiling bottom v0.2.1
error: cannot find derive macro `Deserialize` in this scope
  --> /home/dumontj/.cargo/registry/src/github.com-1ecc6299db9ec823/bottom-0.2.1/src/main.rs:59:19
   |
59 | #[derive(Default, Deserialize)]
   |                   ^^^^^^^^^^^

error: cannot find derive macro `Deserialize` in this scope
  --> /home/dumontj/.cargo/registry/src/github.com-1ecc6299db9ec823/bottom-0.2.1/src/main.rs:65:19
   |
65 | #[derive(Default, Deserialize)]
   |                   ^^^^^^^^^^^

error: cannot find derive macro `Deserialize` in this scope
  --> /home/dumontj/.cargo/registry/src/github.com-1ecc6299db9ec823/bottom-0.2.1/src/main.rs:82:19
   |
82 | #[derive(Default, Deserialize)]
   |                   ^^^^^^^^^^^

error[E0277]: the trait bound `Config: serde::de::Deserialize<'_>` is not satisfied
   --> /home/dumontj/.cargo/registry/src/github.com-1ecc6299db9ec823/bottom-0.2.1/src/main.rs:432:6
    |
432 |         Ok(toml::from_str(config_str.as_str())?)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::de::Deserialize<'_>` is not implemented for `Config`
    | 
   ::: /home/dumontj/.cargo/registry/src/github.com-1ecc6299db9ec823/toml-0.5.6/src/de.rs:77:8
    |
77  |     T: de::Deserialize<'de>,
    |        -------------------- required by this bound in `toml::de::from_str`

error: aborting due to 4 previous errors
```

## To reproduce

Steps on how to reproduce the behaviour:

1. cargo install bottom

## Platform

Provide information on:

**Operating System:** Red Hat Enterprise Linux 7

**Terminal:** bash

**Comment by ClementTsang** [comment]
Already fixed in another commit.  Will deploy soon.

d7b068b69236e11763c103ffcb0668df66d51ff5

**Comment by jannickj** [comment]
Just saw this being posted on reddit, looks really cool but I can't install it either, any news on the deployment?

**Comment by ClementTsang** [comment]
``cargo install bottom --features=serde/derive`` seems to be a working workaround for now.

I'm unfortunately still at work and deploying to crates.io is a bit hard with just a phone sadly.  The build is done and all, so I just have to publish it via cargo.

**Comment by ClementTsang** [comment]
Alright, deployed to crates.io.  Seems fine to me.  If I get some confirmation that it works then I'll close this.

**Comment by ClementTsang** [comment]
Hmmm, seems fine for me on two machines.  Going to close; if people are still finding this a problem reopen please.
