### ISSUE TITLE
CPU 0 in Basic Mode with AVG Disabled

### ISSUE THREAD

**Issue by KabirKwatra** [ClementTsang/bottom#306]
### Basic Mode with AVG Disabled

When in basic mode (`-b`, `--basic`) and avg is disabled, there is one extra cpu displayed.
I am not sure if the intentional behavior is to have 0-15 for 16 cores or to have 1-16.
CPU 0 shows zero usage under sustained all core load.

### To reproduce

1. Run `btm -ba`
2. Run `stress` or a cpu intensive workload
3. See that CPU0 shows zero usage and that the number of CPUs displayed is one more than exist on the machine

### bottom version (use `btm -V`)
bottom 0.4.7

### bottom config file (if one is used)
N/A

### Installation method
AUR `bottom-bin`

### Platform
AMD64/x86-64

**Operating system and OS version:**
Manjaro Linux 5.9.8

**Terminal (i.e. urxvt, kitty, etc.):**
Alacritty

**Shell (i.e. zsh, bash, etc.):**
fish

**Comment by ClementTsang** [comment]
I think this is the same issue as https://github.com/ClementTsang/bottom/issues/288?  If so this should be fixed in master.
