### ISSUE TITLE
Text and Graph colors transparent

### ISSUE THREAD

**Issue by H4dr1en** [ClementTsang/bottom#307]
### Describe the bug

On Macos terminal (ssh to debian machine), colors and text appear grey/transparent, making it difficult to read in general.

<img width="1680" alt="Screenshot 2020-11-18 at 14 04 22" src="https://user-images.githubusercontent.com/16240134/99534114-362b0b80-29a7-11eb-939d-194045349cae.png">

### bottom version (use `btm -V`)
0.4.7
### Installation method
dpkg
**Operating system and OS version:**
MacOS 10.14
**Shell (i.e. zsh, bash, etc.):**
bash

**Comment by ClementTsang** [comment]
Can replicate by SSH-ing into my own Linux machine from my MBP using 0.4.7.  Problem does not appear after using #308, so I assume that it will fix this problem.

**Comment by ClementTsang** [comment]
Closing this due to #308; if 0.5.0 also shows issues for you on release then feel free to re-open.

**Comment by H4dr1en** [comment]
Best reactivity ever, thanks a lot 🥇
