### ISSUE TITLE
Disk Filter by Mount Point

### ISSUE THREAD

**Issue by ibrokemypie** [ClementTsang/bottom#311]
### Describe the feature request

A way to filter in/out drives in the drive_filter by mount point rather than device location.

### Additional context/details

Right now it seems like you can only filter drives by device location, but not mount point. If you have some drives mounted in multiple locations (eg bind mounts) the same drive shows multiple times in bottom, and there doesnt seem to be any way to show only one instance per drive, only to remove the drive entirely or show it for each time it is mounted.

For example:
![image](https://user-images.githubusercontent.com/7827846/99755944-1a0ea200-2b40-11eb-825f-aae8b3c38553.png)

**Comment by ClementTsang** [comment]
Yeah, I know what you mean - I originally was going to do it for both, but never really got around to doing it.

I'll probably try to implement this in the near future.

**Comment by ClementTsang** [comment]
Mount filter feature added, should be available in the next nightly (and stable) build.
