### ISSUE TITLE
New color option isn't respected from config file

### ISSUE THREAD

**Issue by BachoSeven** [ClementTsang/bottom#317]
### Describe the bug
Using `btm --color gruvbox` works just fine, but putting `color="gruvbox"` in the config file has no effect.
### To reproduce

_Steps on how to reproduce the behaviour:_
Using the minimal config file below
### bottom version (use `btm -V`)
0.5.0
### bottom config file (if one is used)
``` toml
[flags]
color = "gruvbox"
```
### Installation method
AUR
### Platform
Linux
**Operating system and OS version:**
Arch
**Terminal (i.e. urxvt, kitty, etc.):**
st
**Shell (i.e. zsh, bash, etc.):**
zsh

**Comment by ClementTsang** [comment]
@BachoSeven ugh, I know why.

Does your config file also have the `[colors]` TOML value uncommented?  It's because the order of precedence when I check for colours is:

1.  `--color = <WHATEVER>` as a command line flag
2.  Custom colours
3.  `color = "<WHATEVER>"` in the config file.

I check 2 by looking for `[colors]` in the config file.  Unfortunately, I also leave that uncommented by default when I generate default config files... so that's probably why it isn't working.

**Comment by ClementTsang** [comment]
This shouldn't be an issue again after 99d04029f0ebfc73d36adb06ea58ad68f090017c.  Will look into pushing this today.

**Comment by BachoSeven** [comment]
@ClementTsang don't kick yourself please :'D

And yes, I did have the `[colors]` tag uncommented (with no definitions inside it though), so I guess that's fixed since you already figured it out. 

A question: after you push the solution, would one be able to make just a few definitions inside the [colors] tag while also choosing a builtin colortheme, effectively changing just some of the colors of a builtin theme?

**Comment by ngirard** [comment]
@ClementTsang, this deserves a full release (with precompiled binaries) on its own, IMHO.

Cheers, and thanks for all the fish !

**Comment by ngirard** [comment]
@ClementTsang, thanks for the release !
I just tried the precompiled binary (v0.5.1) on Ubuntu 20.04 and it didn't seem to take into account any of these configuration lines under the `[colors]` section:

```toml
colors = "default-light"
color = "default-light"
```

Also, you might want to add this option to the [default config file](https://github.com/ClementTsang/bottom/blob/master/sample_configs/default_config.toml).

**Comment by BachoSeven** [comment]
@ngirard AFAIK the `color="default-light" definition belongs under the `[flags]` section, and not the `[colors]` one.

**Comment by ngirard** [comment]
Got it @BachoSeven, thanks !
It's working just fine now.

**Comment by ClementTsang** [comment]
> Also, you might want to add this option to the default config file.

@ngirard Yeah, that sounds like a good idea, I forgot to update that... will do in a bit.
