### ISSUE TITLE
Windows temp sensors might not be working?

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#32]
## Describe the bug

Don't seem to be able to get any temp outputs on Windows.

## To reproduce

Steps on how to reproduce the behaviour:

1. Go to bottom and look at the temp sensors.
2. They're blank for me

## Platform

Provide information on:

**Operating System:** Windows

**Terminal:** Powershell

**Any other relevant information (more details are always good!):**

## Additional context

If anything hasn't been covered by the above categories, state it down here.

This would really be on the temperature providers I'm using.  Worst case, I just write the detection myself... yay...

**Comment by ClementTsang** [comment]
If anyone has another experience (that they *do* work) then please let me know, I'll close this.

**Comment by Walther** [comment]
Confirming, running `btm` in a WSL Debian under Windows results in no sensors found
![Screenshot 2020-05-20 at 16 25 36](https://user-images.githubusercontent.com/2943750/82451358-8e478a80-9ab6-11ea-82e8-312555638855.png)

**Comment by PGScully** [comment]
I have the computer temperature showing, but only if running as Administrator.  As a non-priviledged user I get No sensors found.

**Comment by ClementTsang** [comment]
Hmm... thanks for the reports, I might have to do some digging to see if I have to manually implement this feature (at least for Windows) rather than using sysinfo and/or PR a fix...

**Comment by ClementTsang** [comment]
Did some digging - sysinfo does it correctly, but at least for some systems (mine included), the query to get the temperature just doesn't work.

Manually running the WMI query gives me:
```powershell
Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | Select-Object -Property InstanceName,CurrentTemperature                                                                                     Get-WmiObject : Not supported
At line:1 char:1
+ Get-WmiObject MSAcpi_ThermalZoneTemperature -Namespace "root/wmi" | S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

...which seems to indicate that it's just an issue with WMI and the hardware I'm using not playing nice.  Alternatives using OpenHardwareMonitor exist, but I can't really think of a good way to integrate that into this application off the top of my head.

Also not just a Rust issue or sysinfo issue; the same issue has some discussion here for gopsutil, which also currently uses the WMI query, but will not work on some hardware: https://github.com/shirou/gopsutil/issues/472#issuecomment-405033594

**Comment by rashil2000** [comment]
CPU temperature shows the correct readings for me, it even changes on-the-fly. However as @PGScully mentioned, reading temperatures requires elevated access. So I use this utility called [gsudo](https://github.com/gerardog/gsudo) and simply run `sudo btm`. Might be useful for someone.

**Comment by ClementTsang** [comment]
Closing this for now, seems to be resolved by having elevated access, *but* using something like OHM in the future might be cool if it was feasible, though it would require separate DLLs...

**Comment by lbibass** [comment]
Just a note, I am also getting no temp reporting over ssh, even with Gsudo. 

I will update this once I'm able to test locally.

**Comment by iHaired** [comment]
Windows 11, elevated PowerShell via gsudo. No temp readings.

**Comment by vec715** [comment]
any updates? Still no CPU temp even with admin permissions :(
