### ISSUE TITLE
Inverted behavior of 'hide_avg_cpu' flag in config file

### ISSUE THREAD

**Issue by seifrox** [ClementTsang/bottom#325]
### Describe the bug

The average CPU is not hidden when `hide_avg_cpu = true` is provided in the config file, rather the behavior is inverted. When `hide_avg_cpu = false` is provided the average is actually CPU hidden.

### To reproduce

_Steps on how to reproduce the behaviour:_

create a `~/.config/bottom/bottom.toml` config file with the following content:
```
[flags]
# Whether to hide the average cpu entry.
hide_avg_cpu = true
```

### bottom version (use `btm -V`)
bottom 0.5.1

### bottom config file (if one is used)

```
[flags]
# Whether to hide the average cpu entry.
hide_avg_cpu = true
```
### Installation method
```
curl -LO https://github.com/ClementTsang/bottom/releases/download/0.5.1/bottom_0.5.1_amd64.deb
sudo dpkg -i bottom_0.5.1_amd64.deb
```

### Platform

**Operating system and OS version:**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Terminal (i.e. urxvt, kitty, etc.):**
kitty 0.15.0 created by Kovid Goyal

**Shell (i.e. zsh, bash, etc.):**
fish, version 3.1.0

**Comment by ClementTsang** [comment]
Yep, you're right, seems like I forgot to fix this when I switched from `show_avg_cpu` to `hide_avg_cpu`.

Will deploy a release with a fix in a bit, hopefully.
