### ISSUE TITLE
Some chars (likely unicode) crash search

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#33]
## Describe the bug

_A clear and concise description of what the bug is and what the expected behaviour was:_

Typing ``Option+C`` then another character crashes the program.

## To reproduce

_Steps on how to reproduce the behaviour:_

1. Open search
2. Type `Option + C`
3. Type another character

## Screenshots

_If applicable, add screenshots to help explain your problem:_

## Platform

_Provide information on:_

**Operating System:** macOS

**Terminal:** Kitty

**Any other relevant information (more details are always good!):**

## Additional context

_If anything hasn't been covered by the above categories, state it down here:_

Trace:

```bash
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/ctsang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.43/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/ctsang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.43/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace
             at /Users/ctsang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.43/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create
             at /Users/ctsang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.43/src/capture.rs:164
   3: backtrace::capture::Backtrace::new
             at /Users/ctsang/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.43/src/capture.rs:128
   4: btm::panic_hook
             at src/main.rs:772
   5: btm::main::{{closure}}
             at src/main.rs:186
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:468
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
   8: rust_begin_unwind
             at src/libstd/panicking.rs:302
   9: std::panicking::begin_panic
  10: std::panicking::begin_panic
  11: alloc::string::String::insert
             at <::core::macros::panic macros>:5
  12: btm::app::App::on_char_key
             at src/app.rs:809
  13: btm::handle_key_event_or_break
             at src/main.rs:331
  14: btm::main
             at src/main.rs:225
  15: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
      std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  18: std::panicking::try
             at src/libstd/panicking.rs:265
      std::panic::catch_unwind
             at src/libstd/panic.rs:396
      std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  19: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  20: <btm::_IMPL_DESERIALIZE_FOR_ConfigColours::<impl serde::de::Deserialize for btm::ConfigColours>::deserialize::__Visitor as serde::de::Visitor>::expecting
```

**Comment by ClementTsang** [comment]
Can probably be solved using unicode-segmentation.

**Comment by DenSASoftware** [comment]
The problem here is that you're calling `String::insert` on line 809 in src/app.rs and pass an index that is interpreted as a byte index. As soon as you add a character that's 2 or more bytes long (umlaut, emoji, etc.) your index points to the byte after the added char that is no valid char boundary.

A pure stdlib way to cover most inputs would be `let insert_index = my_string.indices().chain(std::iter::once(my_string.len())).nth(cursor_position).unwrap()`. Unfortunately this does not cover grapheme clusters like flags and emojis with skin color. That's why my recommendation is to use the crate unicode-width.

**Comment by ClementTsang** [comment]
Yeah, I was taking a look at it last night and reached a similar conclusion.  The cursor movement and backspace are also problematic due to my initial approach.
