### ISSUE TITLE
weird font in graphs

### ISSUE THREAD

**Issue by microo8** [ClementTsang/bottom#338]
I've got a problem with the font in graphs. I tried alacritty and urxvt. Used ubuntu moto font and roboto, with no effect.

But when I try bottom in tty it's ok. What's  wrong?

![image](https://user-images.githubusercontent.com/1846338/100980726-f5ee9000-3545-11eb-8f00-ba1e953a6477.png)

**Comment by ClementTsang** [comment]
If the issue's the braille font for displaying the graph lines, then see https://github.com/ClementTsang/bottom/issues/337

If the issue's the borders... yeah I don't know what's causing that.

**Comment by microo8** [comment]
Thanks, I've installet [ttf-braille](https://aur.archlinux.org/packages/ttf-ubraille/) and removed gnu-free-fonts and it's beautifull :)

**Comment by ClementTsang** [comment]
@helmesjo you'll probably need to mess around with your fontconfig and/or font choices inside your terminal emulator of choice. I might need a bit more info to try and help you if you want.

Feel free to move this to a new discussion btw, if that might make it easier.

**Comment by yozachar** [comment]
When I was installing with Firefox, selecting `ttf-dejavu`  fixed for me. Related https://github.com/ClementTsang/bottom/issues/914, https://github.com/ClementTsang/bottom/issues/913, https://github.com/ClementTsang/bottom/issues/337, https://github.com/ClementTsang/bottom/issues/300.
