### ISSUE TITLE
Sorting icons not displaying properly

### ISSUE THREAD

**Issue by Shootertrex** [ClementTsang/bottom#35]
## Describe the bug

The arrows used to indicate that a column has been sorted does not fully appear.

## To reproduce

1. Start bottom
2. Sort a process column e.g. cpu

## Screenshots

![Screenshot_20200225_212133](https://user-images.githubusercontent.com/6365966/75306195-5366eb00-5816-11ea-9a88-e4ae909f8cd9.png)

![Screenshot_20200225_213157](https://user-images.githubusercontent.com/6365966/75306197-56fa7200-5816-11ea-8fc5-5d3d56173489.png)

## Platform

**Operating System:**

OpenSUSE Tumbleweed

**Terminal:**

Konsole

**Shell:**

bash 5.0.11

**Additional Details:**

On another computer using Terminator (also bash), a similar issue happened, but the right half of the triangle didn't repaint until the terminal was resized (half pointed up, half pointed down and vice versa). Unfortunately I don't have screenshots of it.

**Comment by ClementTsang** [comment]
@Shootertrex I'm able to replicate your Konsole issue and I have a fix... can't seem to replicate your Terminator issue though.

https://github.com/ClementTsang/bottom/commit/5d90c235eb22750a6c6a8855ad3db28ad8733165 should fix the Konsole issue, however.

**Comment by ClementTsang** [comment]
Going to close since this should solve the Konsole issue and I can't replicate your terminator issue; feel free to reopen if this fix doesn't solve either though.

**Comment by Shootertrex** [comment]
Thank you for the quick turnaround. I can confirm that it is fixed in Konsole, but it still occurs in Terminator for me. I was able to get screenshots today (occurs in both directions), but if you're unable to reproduce it yourself, they may not be useful.

![1](https://user-images.githubusercontent.com/6365966/75410755-e2ddce00-58ea-11ea-9144-e9787b7d99a0.PNG)
![2](https://user-images.githubusercontent.com/6365966/75410762-e6715500-58ea-11ea-93c9-29e3af4b835b.PNG)

I'm not sure if it's just something on my end then. It's not a big deal though.

**Comment by ClementTsang** [comment]
Hmm, interesting.  I'll open a new issue and try to replicate it.

**Comment by ClementTsang** [comment]
@Shootertrex  if possible, can you send me any config files and font choice you're currently using on Terminator?

**Comment by ClementTsang** [comment]
@Shootertrex sorry to ask you again, but can you try cloning from master and see if https://github.com/ClementTsang/bottom/pull/46 solves your problem?

I was having similar issues with the arrow on macOS and this solved it, so it might also deal with your issue on Terminator.

**Comment by Shootertrex** [comment]
@ClementTsang Building and running master didn't exactly solve the Terminator issue. I want to preface this with that this is occurring on my work machine inside of an older VM (Ubuntu 18.04), so there could possibly be some weirdness coming from that. With that said, it still happens but moving the mouse cursor within the horizontal line where the arrow is refreshes it now. 

Interestingly, Terminator and Tilix (which this also occurs on for me) do not appear to be displaying a small, single character arrow, while Konsole and urxvt both display the character correctly. Changing the font did not help (Ubuntu Mono Regular -> Oxygen Mono Regular). Also interestingly, changing the font size actually fixed the issue in all fonts I tested (except Ubuntu Mono Regular) when set to 12 or below (13 was what I had the terminal at before). It's still the larger arrow, but it will fully repaint.

At this point, I'm not sure if the issue is coming from bottom or from the VM itself, as it displays correctly on my home machine (Konsole). I don't know if any of this extra information is helpful, but just in case.
