### ISSUE TITLE
Process tree navigation continues after a key was released

### ISSUE THREAD

**Issue by singalen** [ClementTsang/bottom#366]
### To reproduce

_Steps on how to reproduce the behaviour:_

1. Navigate to process list.
2. Press and hold Down or Up key.
3. Release the key.

Expected: process selection line stops immediately, like it does in `htop`.
Actual result: process selection line continues to move into the same direction and only stops after it runs another 4-5 processes.

### bottom version (use `btm -V`)

bottom 0.5.5, git 4471ecc16162edce8616f5b92c756a5fd46cccd4.

### bottom config file (if one is used)

[bottom.zip](https://github.com/ClementTsang/bottom/files/5713381/bottom.zip)

### Installation method

`cargo run`

### Platform

**Operating system and OS version:** Ubuntu Linux 20.04, remote session with `et` from Mac OS.

**Terminal (i.e. urxvt, kitty, etc.):** iTerm 3

**Shell (i.e. zsh, bash, etc.):** bash

## Additional context

On Mac, the keyboard repeat interval is set up to be more frequent than the defaults, but it hardly matters.

**Comment by ClementTsang** [comment]
@singalen If you're using debug mode, it's a known problem that doesn't really matter.

It shouldn't be an issue with release, which is how you would use it most likely... do you get the same problem with `cargo run --release`?

**Comment by singalen** [comment]
Indeed, it's OK in release. Sorry for bothering.
