### ISSUE TITLE
Disable swap monitoring if none is available.

### ISSUE THREAD

**Issue by MithicSpirit** [ClementTsang/bottom#370]
### Describe the feature request

In the memory widget, it shouldn't display the swap usage if the system has no swap available. Alternatively, there should be a way to just disable swap from showing up in the config.

### Additional context/details

This would be useful because having a flat yellow line in the memory widget is kind of pointless imo.

**Comment by ClementTsang** [comment]
Agree with this, should be fairly easy to change.

**Comment by ClementTsang** [comment]
@MithicSpirit out of curiosity, would you also want the legend entry (the `SWP: 0%     0.0GB/0.0GB` or whatever) to also be hidden in the case where you have no swap, or would you just want the line to be hidden?

**Comment by MithicSpirit** [comment]
> @MithicSpirit out of curiosity, would you also want the legend entry (the `SWP: 0%     0.0GB/0.0GB` or whatever) to also be hidden in the case where you have no swap, or would you just want the line to be hidden?

Yeah imo the legend entry should also be hidden
