### ISSUE TITLE
macOS M1 support

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#382]
### Describe the feature request

_What is the feature of interest? Be clear and concise._

Adding support for the M1 processor is a good idea, especially if/when it becomes a tier-1 target and has better tooling to work around it.

Currently I can't exactly *test* for these, or need to wait for upstream support on libraries I rely on, though.

Currently not working on M1:

- Temperatures: See https://github.com/ClementTsang/bottom/issues/371#issuecomment-753527248

**Comment by wouterds** [comment]
We're 1 year later, any plans on adding support for this? Would be much appreciated! Sadly enough I do not have any relevant experience to look into it myself.

**Comment by ClementTsang** [comment]
Unfortunately I don't have the hardware to develop this at the moment.

**Comment by zannis** [comment]
I'd love to contribute this feature if you can offer some guidelines on how to approach it.

**Comment by ClementTsang** [comment]
Main thing is the data collection. Normally I rely on other crates to do this and just extract the relevant data, but:

1. The main two data libraries I use don't fully support macOS M1 as far as I'm aware.
2. I can't test if any implementation of M1 data collection actually works, nor can I verify that my usage of any library for M1 works.

TBH the best course of action would be contributing upstream to [sysinfo](https://github.com/GuillaumeGomez/sysinfo/issues/456) because that would kill two birds with one stone (as it's also stuck on the same problem I have, lack of hardware), but I see you're already looking there, so I don't think I need to say much more in regards to that. If that's fully supported then I can just reuse my existing code and just make sure its also used when compiling for M1.

Then, the only other thing I need is someone to be able to test bottom on an M1 just to verify everything works.

For what it's worth, I do plan on buying M1 hardware myself after I graduate, but that's going to take a few months so if you would like to tackle this now I would be very grateful.

**Comment by wouterds** [comment]
Any news on this? Have the relevant third-party libs already been updated with support for Apple silicon? Cheers

**Comment by ClementTsang** [comment]
Sorry, been busy with a bunch of IRL stuff so activity on this application has been unfortunately somewhat slow (about to move to another country for work).

Putting that aside though, at a glance, I think(?) most things should(?) work fine after I move stuff over to sysinfo fully, barring some known stuff like temperature (see https://github.com/GuillaumeGomez/sysinfo/issues/456) - however, it seems like a PR came up recently!

Other than that it's really just having some M1 hardware on hand to actually test if these things work. I'm planning on buying an M1/M2 laptop after I move though so that would probably help in that regard.

**Comment by ClementTsang** [comment]
More follow-up: sysinfo 0.25.3 supports m1 temperatures! However, it has a segfault issue, so I'll wait till that's fixed before moving to it.

**Comment by wouterds** [comment]
Awesome, looking forward! 🙌

**Comment by wouterds** [comment]
Fwiw I came across this thing if it could you help find some learnings https://github.com/tlkh/asitop

**Comment by wouterds** [comment]
Any plans on supporting the temperature sensors on Apple Silicon?

![Screen Shot 2022-09-16 at 10 50 29](https://user-images.githubusercontent.com/1210628/190597894-206b53a1-ac50-4298-9672-f43e3abbc833.jpg)

**Comment by ClementTsang** [comment]
> Any plans on supporting the temperature sensors on Apple Silicon?
> 
> ![Screen Shot 2022-09-16 at 10 50 29](https://user-images.githubusercontent.com/1210628/190597894-206b53a1-ac50-4298-9672-f43e3abbc833.jpg)

Speak of the devil, I just merged https://github.com/ClementTsang/bottom/pull/806 which should mean temperature works now on M1 (at least, it does on my M1 MBP).
