### ISSUE TITLE
Mouse support for sorting columns

### ISSUE THREAD

**Issue by mjlbach** [ClementTsang/bottom#395]
### Describe the feature request

In htop, when you click on a column label (cpu/mem/time) it will toggle sort in descending order. A second click sorts in ascending order. (As small as this is), this is about about the only feature that prevents me from aliasing htop to btm -b

**Comment by ClementTsang** [comment]
Yep, this is something I want to add as well.

**Comment by mjlbach** [comment]
Thank you!
