### ISSUE TITLE
On some legacy Macs, CPUs are not shown in the basic mode

### ISSUE THREAD

**Issue by 097115** [ClementTsang/bottom#397]
## Describe the bug

I have this oldie [MacBook](https://everymac.com/systems/apple/macbook/specs/macbook-core-2-duo-2.4-aluminum-13-late-2008-unibody-specs.html), running 10.11, and in basic mode CPUs aren't shown.

## To reproduce

_Steps on how to reproduce the behaviour:_

`btm -b`:

![](https://i.imgur.com/6EhWTHn.png)

vs `btm`:

![](https://i.imgur.com/TwBkakZ.png)

## bottom version

bottom 0.5.6

## bottom config file (if used)

None.

## Installation method

A binary from Releases.

### Operating system, OS version, and architecture

macOS 10.11

### Terminal (i.e. urxvt, kitty, etc.)

Terminal.app, Alacritty, iTerm

### Shell (i.e. zsh, bash, etc.)

bash

### Miscellaneous system info

_RAM size:_ 8GB

_SWAP size:_ 1GB

_CPU and number of cores:_  2.4 GHz Intel "Core 2 Duo" processor (P8600), with two independent processor "cores" on a single silicon chip, a 3 MB shared "on chip" level 2 cache

**Comment by ClementTsang** [comment]
Hm, that's weird - it's probably a bug in how I display CPU cores in basic mode, which shouldn't be too hard to fix.

I'll try to replicate it in another low-core environment when I have some time and get back to you with a fix if possible.

**Comment by ClementTsang** [comment]
Can replicate on Ubuntu with 2 cores.  Investigating...
