### ISSUE TITLE
Add nord as a color scheme

### ISSUE THREAD

**Issue by TheOPtimal** [ClementTsang/bottom#403]
### Add Nord as a color scheme

Nord is an arctic, bluish color theme that's a bit dark and very nice. A lot of people use it. I ask for the Nord color scheme to be available in `--color`.

### Additional context/details

Colorscheme documentation is available [here](https://www.nordtheme.com/docs/), and the [bat](https://github.com/sharkdp/bat) project might be a good reference as it has Nord as an available colorscheme and is written in Rust.

**Comment by ClementTsang** [comment]
Sure thing.

Funny story, actually, it was already implemented, but I just never enabled it.

**Comment by TheOPtimal** [comment]
You may also want to use the BAT_THEME environment variable as a default, as most bottom users will have bat installed. However, this is optional.

**Comment by alerque** [comment]
Using prefixed variables targeted at other apps is not a good idea. Such stunts should only be attempted behind some off-by-default flag or env var actually targeted at the app in question, e.g. `BOTTOM_USE_BAT_THEME=true`.

**Comment by TheOPtimal** [comment]
Good call.

**Comment by ClementTsang** [comment]
@TheOPtimal Here's my current colour scheme based on Nord, any thoughts/suggestions?  Open to anything:

nord:
![image](https://user-images.githubusercontent.com/34804052/107902317-0e9aff00-6f14-11eb-9160-f53d668e9855.png)

nord in basic mode:
![image](https://user-images.githubusercontent.com/34804052/107902334-1c508480-6f14-11eb-9196-61e06d2aff69.png)

nord-light (for light backgrounds):
![image](https://user-images.githubusercontent.com/34804052/107902373-3b4f1680-6f14-11eb-906f-e8e034e7843a.png)

nord-light in basic mode:
![image](https://user-images.githubusercontent.com/34804052/107902356-2f635480-6f14-11eb-8992-b6c9a74dea94.png)

**Comment by ClementTsang** [comment]
Currently going to mark this as closed to keep track of its status as the task is done + merged, though feel free to re-open if there are any changes to suggest.

**Comment by TheOPtimal** [comment]
I quite like it! Although, I think the white borders look a bit out of place. I suggest either using something out of Frost for the border..

**Comment by ClementTsang** [comment]
@TheOPtimal switched to using: #5e81ac for the highlighted border colour and #88c0d0 for the border colour.  Would that work better?

![image](https://user-images.githubusercontent.com/34804052/108607877-24377b00-7391-11eb-87d5-6a414b1bf343.png)

**Comment by TheOPtimal** [comment]
Looks much better, amazing job!
