### ISSUE TITLE
CPU graph shows as 0% in Windows 10

### ISSUE THREAD

**Issue by thehyperpineapple** [ClementTsang/bottom#404]
## Issue
The CPU usage graph shows up as 0%

## To reproduce
The error is produced whenever bottom is in use

## bottom version
bottom version - 0.5.7

## Method of installation
Installed using the msi file from the GitHub [release page](https://github.com/ClementTsang/bottom/releases)

## Operating System
Operating System - Windows 10 (x86_64)

## Terminal 
Terminal - Alacritty

## Shell
Shell - Windows PowerShell

![image_2021-02-07_113817](https://user-images.githubusercontent.com/62801500/107138183-f84fda80-6938-11eb-812d-1d717fe6772c.png)

**Comment by ClementTsang** [comment]
Hmm, that's weird, I just tried the exact same setup and it works fine:

![image](https://user-images.githubusercontent.com/34804052/107138532-e4798980-68e2-11eb-95c1-ed79af42a2d1.png)

**Comment by thehyperpineapple** [comment]
Strange. Here's my system info if it's of any use

## RAM size
8.00 GB RAM

## Swap size
 5120 MB
 
## CPU and number of cores
CPU - Intel i5 -10210U CPU @ 1.60 GHz 2.10 GHz
Number of cores - 4

**Comment by GiowGiow** [comment]
I have the exact same problem. Is there any log that I can provide ?
My CPU is an I5 4670k

**Comment by ClementTsang** [comment]
Hm, weird.

Unfortunately, I removed my logging debug option since it was strangely causing issues - I wanted to add it back, but right now it's not there.

If it's not too much trouble, could you clone https://github.com/GuillaumeGomez/sysinfo and run
```
cd examples
cargo run
```
and type "refresh" and "processors" a few times, and let me know if it shows anything?  This would help narrow it down to either  an upstream library issue or one with the program (probably latter though).

**Comment by ClementTsang** [comment]
Ah.  I just noticed that there *was* a recent commit which might affect CPU usage: https://github.com/GuillaumeGomez/sysinfo/issues/459

I'll try updating the version and trigger a nightly build, hopefully one of you two could try it for me and see if that fixes it.

**Comment by GiowGiow** [comment]
> Hm, weird.
> 
> Unfortunately, I removed my logging debug option since it was strangely causing issues - I wanted to add it back, but right now it's not there.
> 
> If it's not too much trouble, could you clone https://github.com/GuillaumeGomez/sysinfo and run
> 
> ```
> cd examples
> cargo run
> ```
> 
> and type "refresh" and "processors" a few times, and let me know if it shows anything? This would help narrow it down to either an upstream library issue or one with the program (probably latter though).

I cloned the repo, and ran refresh and processors 5 times. Each time the result was the same, the CPU usage was 0 for each of the 4 cores. Just for the sake of testing if it was a permission issue, I did the same testing using elevated Powershell but got the same results.

**Comment by ClementTsang** [comment]
Well... that was not the result I was expecting.  So it sounds like it's an issue with sysinfo?

Just pushed a PR to update a bunch of dependencies.  If it's alright with you, could you try to clone the repo and do:
```
cargo r
```
and see if that's changed anything in regards to the CPU usage?  If not, then I'll try switching the data input source and hopefully that'll fix it.

Really sorry for all the trouble.

**Comment by GiowGiow** [comment]
> Well... that was not the result I was expecting. So it sounds like it's an issue with sysinfo?
> 
> Just pushed a PR to update a bunch of dependencies. If it's alright with you, could you try to clone the repo and do:
> 
> ```
> cargo r
> ```
> 
> and see if that's changed anything in regards to the CPU usage? If not, then I'll try switching the data input source and hopefully that'll fix it.
> 
> Really sorry for all the trouble.
Tried again with the updated commit from the PR and got the same results, still nothing... 
From what we tested I think the problem is on sysinfo side. If it can't get CPU information, bottom can't display it. I'll try some tests later with sysinfo to see if I can understand what is happening. 

Anyway, thanks for helping me figure out where to look for. 
Don't be sorry, you haven't caused any trouble, rather, this piece of software here is really nice!

**Comment by ClementTsang** [comment]
Could you try to pull and switch to the `switch_windows_cpu_source` branch, and try running that?

If that doesn't work then I have no idea, haha.

**Comment by GiowGiow** [comment]
> Could you try to pull and switch to the `switch_windows_cpu_source` branch, and try running that?
> 
> If that doesn't work then I have no idea, haha.

It worked! I tried just now and the CPU is now showing perfectly!
Thanks for your help!

**Comment by ClementTsang** [comment]
Cool, I'll switch over to that for now then.

Thanks very much for the help, wouldn't have been able to fix it otherwise!

**Comment by SebastianFelgueras** [comment]
> > Well... that was not the result I was expecting. So it sounds like it's an issue with sysinfo?
> > Just pushed a PR to update a bunch of dependencies. If it's alright with you, could you try to clone the repo and do:
> > ```
> > cargo r
> > ```
> > 
> > 
> > and see if that's changed anything in regards to the CPU usage? If not, then I'll try switching the data input source and hopefully that'll fix it.
> > Really sorry for all the trouble.
> 
> Tried again with the updated commit from the PR and got the same results, still nothing...
> From what we tested I think the problem is on sysinfo side. If it can't get CPU information, bottom can't display it. I'll try some tests later with sysinfo to see if I can understand what is happening.
> 
> Anyway, thanks for helping me figure out where to look for.
> Don't be sorry, you haven't caused any trouble, rather, this piece of software here is really nice!

Hi! I'am the one that found the issue in sysinfo and made a PR to fix it.
If you need any help i can try to help you. I would also like to know wich test you made so if there is a problem in sysyinfo i can try to fix it
