### ISSUE TITLE
Disk widgets won't display anything on Void Linux with an encrypted disk

### ISSUE THREAD

**Issue by Bumbadawg** [ClementTsang/bottom#419]
## Describe the bug

Disk widgets won't display anything on Void Linux.

## bottom version

bottom 0.5.7

## Installation method

Btm either installed through package manager or through cargo.

### Operating system, OS version, and architecture

- _Linux (`x86_64`, `i686`, `aarch64`)_ Void Linux

### Terminal (i.e. urxvt, kitty, etc.)

didn't impact.

### Shell (i.e. zsh, bash, etc.)

zsh

### Rust version
1.48

**Comment by ClementTsang** [comment]
Hmm... I'll take a look in a while.

**Comment by ClementTsang** [comment]
@Bumbadawg well this is weird - I tried installing void onto a VM via cargo and:

![image](https://user-images.githubusercontent.com/34804052/108800451-27816100-7561-11eb-93f2-cb5b9778024a.png)

Disk seems fine for me.

The only difference I can think of is that I used rust 1.50, but I really don't think that would have caused it to magically work for me...

**Comment by jubelbube** [comment]
Hello,
I have the same problem while using a NVMe drive and LVM on LUKS
bottom 0.5.7
installed via xbps
Void Linux (musl)
terminal: st
shell: mksh / bash
rustc 1.48.0

**Comment by ClementTsang** [comment]
Tried running it on my VM again, this time dropped to rustc 1.48 and tried both musl and gnu.  Also tried installing via xbps.

![image](https://user-images.githubusercontent.com/34804052/108973791-c5a12400-7652-11eb-8497-a710f51551f4.png)

In all cases, I just can't seem to replicate either of your findings, which makes trying to fix the problem (whatever it is) basically impossible for me... so I might need some help.

If any of you two (or anyone else with this issue who sees this thread) can try to do the following for me:

1.  Clone heim at https://github.com/heim-rs/heim
2. `cd` into the repo, then `cd` into `examples/`
3. `cargo run --example disk_usage`, report back what  your output.

When I run it on my machine, I get something like:
```
Device            Total, Mb  Used, Mb   Free, Mb   Type       Mount
/dev/nvme0n1p2    105152     58064      41702      ext4       /
/dev/nvme0n1p3    396779     207342     169210     ext4       /home
/dev/sda2         100        72         28         vfat       /boot
```

If you get an empty output or some error, then please let me know as well.

If it *does* work, then could you also try running one of the [nightly](https://github.com/ClementTsang/bottom/releases/tag/nightly) versions and see if that works?

I know this is asking a lot, but it'll help a lot in narrowing down the issue.

Thanks!

**Comment by jubelbube** [comment]
ok, I went through the steps, this is what I get:
`cargo run --example disk_usage`

`Device            Total, Mb  Used, Mb   Free, Mb   Type       Mount`
`/dev/mapper/voidvg-root 52576      6680       43194      ext4       /`
`/dev/mapper/voidvg-home 31568      1427       28513      ext4       /home`
`/dev/nvme0n1p1    535        0          535        vfat       /boot/efi`

Next will try the nightly versions (later today)
YET: Out of curiosity I tried `sudo btm` and that works. So it might have to do with permission
or users being in certain groups.

Thanks for your help to this point!

**Comment by ClementTsang** [comment]
Huh, weird that heim worked without sudo but bottom had issues...

That definitely does help a bit though, thanks a ton!

**Comment by jubelbube** [comment]
Sorry, I was wrong, I ran that with sudo as well. Edited above.

**Comment by ClementTsang** [comment]
Gotcha.  I can probably try to see if there's any workarounds when I have some time, then.

**Comment by jubelbube** [comment]
ok, I finished my "work": nightly tested and post edited.
Thanks again

**Comment by Bumbadawg** [comment]
I use LVM+LUKS as well.
Updated to Rustc 1.50 didn't change the outcome.

Disk Example code worked for listing the LVM disks but then fails and exit on this error (before even listing the regular disks.

```
Error: Error { source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" },
context: Some(Ffi { func: "statvfs" }) }
```
And... "sudo btm" works for the disks..
In VoidLinux, this is possibly related to user groups and rights. For instance, by default you can't mount a phone without changing your user to the adequate group.

**Comment by ClementTsang** [comment]
Alright, thanks, I'll try to tackle this sometime this week now that it's more clear what the issue is.

**Comment by ClementTsang** [comment]
Both the I/O being missing and the missing disks issue should be fixed.

If possible try out a [nightly](https://github.com/ClementTsang/bottom/releases/tag/nightly) build/clone the repo and tell me if it works for you.

**Comment by jubelbube** [comment]
I downloaded bottom_x86_64-unknown-linux-musl.tar.gz
and also from GIT `git clone https://github.com/ClementTsang/bottom` which compiles ok.
Looks ok now, showing disk info without root privileges:
both logicial volume (root and home) with used/free/total/read/write
EFI boot partition (/boot/efi) used/free/total show N/A, no I/O output (which all is no problem for me)
Thanks for your efforts!

**Comment by Bumbadawg** [comment]
We can now enjoy a fully-stacked rust bottom ! Thanks @ClementTsang you rock
