### ISSUE TITLE
Summarize values for collapsed node in process trees

### ISSUE THREAD

**Issue by simonwiles** [ClementTsang/bottom#424]
### Describe the feature request

It would be great if collapsing a node in process tree view would show summarized values for CPU%, Mem% etc for the collapsed branch, similar to what is done with the "group/un-group processes with the same name" feature.

**Comment by ClementTsang** [comment]
That sounds logical, I'll probably add it + a flag + config option along with it to control the behaviour if people prefer the current display.

**Comment by simonwiles** [comment]
Awesome, thanks!  It's not at all clear to me what the value of keeping the present behaviour would be, tbh -- as with the "group/un-group processes with the same name", if the row represents multiple processes then showing values from only one of those is of questionable utility, but perhaps there's something I'm overlooking in this case?  In any event, this great tool will only be even better with this addition; thanks again!

**Comment by ClementTsang** [comment]
I do think you're right in that the current behaviour isn't really useful, and I definitely agree with you in retrospect - I don't see too much use in the current behaviour and would prefer to just make the proposed behaviour the default, for sure.

I did kinda copy htop's behaviour in regards to collapsing trees though, and it doesn't summarize values, so I guess that was why I initially made the behaviour like that.  Not sure if people prefer that behaviour, even if it is, like we agree on, not really that useful, so I still might add the option to fall back to the old behaviour.
