### ISSUE TITLE
fish completions don't seem to be available when installed via brew

### ISSUE THREAD

**Issue by taranjlu** [ClementTsang/bottom#426]
## Describe the bug

After installing `bottom` via `brew` on Fedora 33, I am unable to locate the `btm.fish` completions file mentioned in the docs.

```
~
❯ brew ls --verbose bottom
find /home/linuxbrew/.linuxbrew/Cellar/bottom/0.5.7 -not -type d -print
/home/linuxbrew/.linuxbrew/Cellar/bottom/0.5.7/etc/bash_completion.d/btm.bash
/home/linuxbrew/.linuxbrew/Cellar/bottom/0.5.7/share/zsh/site-functions/_btm
/home/linuxbrew/.linuxbrew/Cellar/bottom/0.5.7/bin/btm
/home/linuxbrew/.linuxbrew/Cellar/bottom/0.5.7/.brew/bottom.rb
/home/linuxbrew/.linuxbrew/Cellar/bottom/0.5.7/INSTALL_RECEIPT.json

~
❯ cd /home/linuxbrew/.linuxbrew/Cellar/bottom/0.5.7/

/h/l/.l/Cellar/bottom/0.5.7
❯ exa -1 --group-directories-first
bin
etc
share
INSTALL_RECEIPT.json

/h/l/.l/Cellar/bottom/0.5.7
❯ tree -C --dirsfirst
.
├── bin
│   └── btm
├── etc
│   └── bash_completion.d
│       └── btm.bash
├── share
│   └── zsh
│       └── site-functions
│           └── _btm
└── INSTALL_RECEIPT.json

6 directories, 4 files
```

## To reproduce

Install `bottom` via `brew` on Linux (probably also affects macOS). Try to locate fish completions file.

## bottom version

```
~
❯ btm -V
bottom 0.5.7
```

## Installation method

Installed via `brew` on Fedora 33.

### Operating system, OS version, and architecture

- Fedora 33 (`x86_64`)

### Terminal (i.e. urxvt, kitty, etc.)

- `alacritty`

### Shell (i.e. zsh, bash, etc.)

- `fish`

**Comment by ClementTsang** [comment]
Yeah, taking a look at my homebrew template (you can see the 0.5.7 one here)[https://github.com/ClementTsang/homebrew-bottom/blob/master/bottom.rb] I seem to have forgotten to put fish completions in...

**Comment by ClementTsang** [comment]
@taranjlu updated the brew .rb in the [homebrew repo](https://github.com/ClementTsang/homebrew-bottom) and I see the fish completion file on macOS.  Let me know if there are any issues.

**Comment by taranjlu** [comment]
Yep, it's working for me now. Thank you!
