### ISSUE TITLE
How can I see full process command line?

### ISSUE THREAD

**Issue by sinapis** [ClementTsang/bottom#432]
I have some very lengthy process command lines which are truncated:
![image](https://user-images.githubusercontent.com/15230040/110239356-3566b700-7f4f-11eb-88ac-785341771632.png)

Is there a way to see the full command line of the process?

for example in [procs](https://github.com/dalance/procs) i can scroll horizontally:
![image](https://user-images.githubusercontent.com/15230040/110239449-91c9d680-7f4f-11eb-9ffa-4a513a915e18.png)
![image](https://user-images.githubusercontent.com/15230040/110239456-9c846b80-7f4f-11eb-83b5-ba91b18dfb3b.png)

**Comment by ClementTsang** [comment]
Unfortunately, there isn't a way to do so for now.
