### ISSUE TITLE
showing CPU usage or process for specific user

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [ClementTsang/bottom#434]
### Question

I have the `btm` on our institute cluster with many users. How can I see only my resource usage. I see there is the `user=foo` flag in the manual but I do not get it.
Thanks!

**Comment by ClementTsang** [comment]
Note that is only on the nightly version, 0.5.7 does not have that feature yet as it's quite recent.

![image](https://user-images.githubusercontent.com/34804052/110876347-48f28480-82a5-11eb-8eaf-4528c8b956d5.png)
