### ISSUE TITLE
pkill doesn't work?

### ISSUE THREAD

**Issue by ixzh** [ClementTsang/bottom#438]
### Question

_What do you want to ask in regards to this project?_

I tried to run `sudo btm` a few times and noticed there were plenty of root btm process that can't be killed and with a high CPU % usage.... what is wrong here?

**Comment by ClementTsang** [comment]
Could you provide more details?  This sounds like a bug.

**Comment by ixzh** [comment]
> Could you provide more details?

I have not set up my screenshot yet so will include screen shot later.

However logging in as root and lauch htop can kill btm process. CPU usage drop to low level.  I will try to reproduce the case with screenshot.

The root of this questions is: what is the correct way to launch btm with root right to kill any process?

**Comment by ClementTsang** [comment]
I'm not exactly sure what you mean, sorry.  So you want to run bottom as sudo to kill a process?  What process, for example?  What version of bottom?  Can you please provide detailed steps on what you're trying to do?

Furthermore, in regards to high cpu usage, could you mention what environment you're using this in?  What OS?

I'm a bit confused by your use case and problems, my apologies.  Normally the but report template has fields to fill in to help provide me more context.

**Comment by ixzh** [comment]
I will file a proper issue. Thanks for the prompt reply!

**Comment by ClementTsang** [comment]
Closing for now, if there's still an issue file a new one as a bug report as mentioned before.
