### ISSUE TITLE
Text and Graph colors transparent - 2

### ISSUE THREAD

**Issue by H4dr1en** [ClementTsang/bottom#447]
## Describe the bug

On Macos terminal (ssh to debian machine) with system bright theme activated, colors and text appear grey/transparent, making it difficult to read in general.

<img width="1680" alt="Screenshot 2021-04-08 at 16 06 56" src="https://user-images.githubusercontent.com/16240134/114041347-c5688b00-9884-11eb-90ba-454585438fec.png">

## bottom version

0.5.1

## bottom config file (if used)

_If you're using a config file, please include it in the report._

## Installation method

dpkg

### Operating system, OS version, and architecture

macOS 10.14

### Shell (i.e. zsh, bash, etc.)

Default

**Comment by ClementTsang** [comment]
Is using a more recent version with a light theme not available?

**Comment by ClementTsang** [comment]
That version is also very old... I don't know if that's part of the issue.

**Comment by ClementTsang** [comment]
@H4dr1en could you get back to me on this if possible?  I would like to know if this issue can be resolved, or if there's something else blocking resolution.

Note that ideally I would add some automatic light-terminal-background detection to avoid having to manually set a colour theme, but that's more of a feature to do in the future.

**Comment by H4dr1en** [comment]
Hi @ClementTsang (Sorry I didn't get the notifications) 

Yes, using `btm --color default-light` solves this issue. Indeed automatic light terminal background would be nice, for the moment I'll just set up an alias. Thanks for the tool!

**Comment by ClementTsang** [comment]
Cool, thanks for getting back to me!

If you don't want to use an alias, you can instead set it in the config file.  It should be somewhere like `~/.config/bottom/bottom.toml`.  By default, it should look something like:

```toml
[flags]
# ...
#color = "default"
# ...
```
Uncomment the color line and set it to `"default-light"`:

```toml
[flags]
color = "default-light"
```
