### ISSUE TITLE
Add decimal digit to a process memory representation when it's in GiB

### ISSUE THREAD

**Issue by vglfr** [ClementTsang/bottom#448]
### Describe the feature request

_What is the feature of interest? Be clear and concise._

While observing memory-hungry process GiB digit only seems not enough. What actually is 1GiB - 1.1GiB or 1.9GiB? What limit should be used as a first guess during containerization?

Currently: 

![2021-04-09_14-09-57](https://user-images.githubusercontent.com/20283252/114172164-fc4ea780-993d-11eb-8fc1-2ccea2504f85.png)

What I'd like to:

![2021-04-09_14-09-31](https://user-images.githubusercontent.com/20283252/114172326-31f39080-993e-11eb-8d49-8b6030c74d6b.png)

### Additional context/details

_Provide any additional context or details here. What needs to be done, why, etc:_

It seems all it takes in case of per-process memory is adding special case for GiB at:

https://github.com/ClementTsang/bottom/blob/e63a0b40827871b8c923a7bd7211fcd0c56aa97c/src/data_conversion.rs#L1239

Not sure whether it needs to be extrapolated to other metrics or units.

**Comment by ClementTsang** [comment]
Sounds good, bit of an oversight on my part I guess since I usually use the % view.

**Comment by ClementTsang** [comment]
Decided to apply it for all units, does this look fine?

![image](https://user-images.githubusercontent.com/34804052/114227705-52721980-9943-11eb-97a1-b6b043f89e10.png)

**Comment by vglfr** [comment]
Please don't take it as nitpicking but I'd rather left integers for Mb. It doesn't really matter whether it's 194.5Mb or 194Mb but latter reads better; however difference between 1.1Gb and 1.9Gb is quite substantial.

Anyway thanks for quick resolution and great tool!

**Comment by ClementTsang** [comment]
Hmm, gotcha.  That sounds reasonable.

**Comment by ClementTsang** [comment]
Merged change into master, should appear on a nightly build soon.  Thanks for the suggestion!
