### ISSUE TITLE
dd should allow kill -9

### ISSUE THREAD

**Issue by jason-oliveira** [ClementTsang/bottom#453]
### Describe the feature request

dd in the process menu should not just do a kill -15 on a pid. it should do a kill -9.

### Additional context/details

This is a dealbreaker for sysadmin tasks, or misbehaving (usually Wine) applications. Hanging/Zombie processes laugh in the face of kill -15.

**Comment by ClementTsang** [comment]
There's already an advanced kill menu on nightly that allows you to pick any kill level you want, but I do understand your point, I'll change it in the future.

![image](https://user-images.githubusercontent.com/34804052/115120908-ecf2de00-9f7d-11eb-81e8-3c71c00bdef4.png)

**Comment by ClementTsang** [comment]
The newly released version (0.6.0) includes a kill menu that allows you to pick a signal by default.  Hopefully that should address this pain point.

**Comment by ClementTsang** [comment]
Closing for now as housekeeping since this issue should be resolved by this new feature; feel free to reopen if necessary.
