### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#480]
### Describe the feature request

_What is the feature of interest? Be clear and concise._

https://github.com/unrelentingtech/systemstat seems like a good candidate library for a data source.

### Additional context/details

_Provide any additional context or details here. What needs to be done, why, etc:_

Probably want to refactor a bit first to make this a bit nicer to implement, code's a bit of a mess rn...

**Comment by ClementTsang** [comment]
See #482 for addressing the note.

**Comment by Mostly-BSD** [comment]
Up voting this, now that sysinfo has FreeBSD support.

**Comment by ClementTsang** [comment]
Renaming this one to refer specifically to FreeBSD, and opening https://github.com/ClementTsang/bottom/issues/640 to track OpenBSD.

**Comment by hronro** [comment]
Is it possible to download FreeBSD binaries in GitHub Releases?

**Comment by ClementTsang** [comment]
> Is it possible to download FreeBSD binaries in GitHub Releases?

Planned but currently not possible ASAP since I want to use CirrusCI for this, but I can't activate it right now due to some bugs.

When that's done I'm planning on adding builds for the binaries.
