### ISSUE TITLE
Under processes allow to sort by etc. Memory or R/s or W/s etc.

### ISSUE THREAD

**Issue by Darkyere** [ClementTsang/bottom#485]
It would be a useful feature to be able to click the processes list as one all ready can.
But then be able to press Right/Left key on keyboard to choose how the list should be sorted.

I sometimes run Read or Write demanding applications. But they have very little CPU usage.
So i am not able to see the actual speed of the applications.

A feature where i could choose to sort by etc. W/s by pressing the right arrow key till it has reached the W/s section would be nice.

Thank you for listening and best regards,
Darkyere

**Comment by ClementTsang** [comment]
@Darkyere you already can choose sorting method for processes, click on the column header with the mouse or press `s` in a process widget.

As for doing it by arrow keys, I might be using left/right arrow keys for something else in the future, but I'll try to make it more ergonomic to change sorting methods using only the keyboard.
