### ISSUE TITLE
Compilation failed 

### ISSUE THREAD

**Issue by Martinfx** [ClementTsang/bottom#489]
## Describe the bug

_A clear and concise description of what the bug is and what the expected behaviour was. If applicable, add screenshots to help explain your problem:_

I compiled bottom application on FreeBSD but i had issue with dependency

## How to reproduce

Compilation source code from master on FreeBSD 

`   Compiling thiserror v1.0.25
   Compiling futures-executor v0.3.15
   Compiling futures v0.3.15
   Compiling toml v0.5.8
error[E0433]: failed to resolve: could not find `MemHarvest` in `memory`
  --> src/app/data_farmer.rs:73:37
   |
73 |             memory_harvest: memory::MemHarvest::default(),
   |                                     ^^^^^^^^^^ could not find `MemHarvest` in `memory`

error[E0433]: failed to resolve: could not find `MemHarvest` in `memory`
  --> src/app/data_farmer.rs:74:35
   |
74 |             swap_harvest: memory::MemHarvest::default(),
   |                                   ^^^^^^^^^^ could not find `MemHarvest` in `memory`

error[E0433]: failed to resolve: could not find `CpuHarvest` in `cpu`
  --> src/app/data_farmer.rs:75:31
   |
75 |             cpu_harvest: cpu::CpuHarvest::default(),
   |                               ^^^^^^^^^^ could not find `CpuHarvest` in `cpu`

error[E0433]: failed to resolve: could not find `IoHarvest` in `disks`
  --> src/app/data_farmer.rs:79:32
   |
79 |             io_harvest: disks::IoHarvest::default(),
   |                                ^^^^^^^^^ could not find `IoHarvest` in `disks`

error[E0433]: failed to resolve: could not find `MemHarvest` in `memory`
  --> src/app/data_farmer.rs:92:39
   |
92 |         self.memory_harvest = memory::MemHarvest::default();
   |                                       ^^^^^^^^^^ could not find `MemHarvest` in `memory`

error[E0433]: failed to resolve: could not find `MemHarvest` in `memory`
  --> src/app/data_farmer.rs:93:37
   |
93 |         self.swap_harvest = memory::MemHarvest::default();
   |                                     ^^^^^^^^^^ could not find `MemHarvest` in `memory`
`
## bottom version

Source code from master
_Use `btm -V` and report the version of bottom you have installed. Also, if you're not on the latest version, please [try that](https://github.com/ClementTsang/bottom/releases/latest) and see if the problem is already resolved._

## bottom config file (if used)

_If you're using a config file, please include it in the report._

## Installation method

_How did you install bottom? Note if it's not a supported method, I may not be able to help you._

### Operating system, OS version, and architecture

_Please specify your operating system, the version, and architecture, so I can try to replicate your environment as best as possible. Note that the officially supported platforms are:_

- _macOS (`x86_64`)_
- _Linux (`x86_64`, `i686`, `aarch64`)_
- _Windows (`x86_64`, `i686`)_

_If your platform is not listed, please be aware I do not officially support it and may be unable to fix this issue._

### Terminal (i.e. urxvt, kitty, etc.)

_Sometimes this matters, so please mention your terminal/terminal emulator._

### Shell (i.e. zsh, bash, etc.)

_Again, sometimes this matters, so please mention your shell type if possible._

### Miscellaneous system info

_Not totally necessary, but if possible, include details like:_

_RAM size:_

_SWAP size:_

_CPU and number of cores:_

### Rust version

_Check this with `rustc --version`. This is only relevant if your version of bottom isn't from a pre-built binary (i.e. Cargo). Otherwise, feel free to skip._

## Additional context

_If anything hasn't been covered by the above categories, feel free to include it here:_

**Comment by ClementTsang** [comment]
As per the bug report, FreeBSD is not supported in any official capacity (yet).

**Comment by ClementTsang** [comment]
BSD support would hopefully come as part of https://github.com/ClementTsang/bottom/issues/480, but I haven't had the time to get to it yet.

Closing this as this is something I can't really "fix".
