### ISSUE TITLE
I would like to transfer ownership of AUR package "bottom-bin"

### ISSUE THREAD

**Issue by KSXGitHub** [ClementTsang/bottom#49]
@ClementTsang Are you [xoronth](https://aur.archlinux.org/account/xoronth) in aur.archlinux.org? Are you willing to maintain [bottom-bin](https://aur.archlinux.org/packages/bottom-bin/)? I'd like to have less job in my hand to deal with.

**Comment by ClementTsang** [comment]
Yeah, that's me.  I'll take it if you want.

**Comment by KSXGitHub** [comment]
Transfer completed.

**Comment by KSXGitHub** [comment]
Are you going to keep `bottom-bin` up-to-date? If not, can you re-add me to list of maintainers so that I may do it when necessary?
