### ISSUE TITLE
include shell completion files with releases

### ISSUE THREAD

**Issue by adgai19** [ClementTsang/bottom#493]
## Details

Right now, the completion files are released through the binaries, although while sometimes, the completion files are not generated,  Can you please add generated completion files along with release files with each release? As it will be easier to  download and copy them to necessary path.

**Comment by ClementTsang** [comment]
Sure thing!

**Comment by adgai19** [comment]
Thanks

**Comment by ClementTsang** [comment]
#494 adds them to both nightly and release builds as `completion.tar.gz`.  Also added to the 0.6.1 release.
