### ISSUE TITLE
Add non-normalized CPU usage to processes

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#496]
### Describe the feature request

_What is the feature of interest? Be clear and concise._

Add a column to show non-normalized CPU usage.  We currently only offer a normalized (over #cpu cores)  usage.

### Additional context/details

_Provide any additional context or details here. What needs to be done, why, etc:_

Originally based on #495.  This should be very easy to do in terms of data collection and displaying, but is currently blocked on adding customization to process/table columns, as this would have to be optional.

**Comment by vorner** [comment]
Hello

I was wondering if anyone actually wants both columns or if people would prefer to choose. In that case it wouldn't have to be a separate column, maybe just a command line switch, similar to how `--current_usage` works. For example, I wouldn't need the normalized column at all, but the non-normalized is useful. Having something running at 100% is obviously saturating one core and the CPU is a bottleneck for it, while going on 16% is much less obvious.

**Comment by ClementTsang** [comment]
Yeah, that would be the quick way of implementing it.  I might do that for now once I'm a bit less busy with IRL, since it's fairly easy to add.

Should have clarified a bit more in the original issue though, I did eventually want to build more granular control of what columns are shown though (think like htop), so that's more of where the "add another column" comes in.

**Comment by kvelicka** [comment]
Hello,

I'm interesting in this feature too, glad to see there's already an open issue for it! Regarding the implementation, another hopefully-easy alternative could be to use the same/similar mechanism as `%` which switches between absolute and percentage memory - some shortcut could be used to switch between normalised and not CPU usage.

**Comment by ClementTsang** [comment]
Yep, that's kinda what I had in mind for implementing this for now, and it would be pretty easy. Just currently a bit busy with work stuff (started a new job this week) and with some internal refactoring that's blocking working on... really any feature.

Hopefully soonish!

**Comment by kvelicka** [comment]
No rush whatsoever, thanks for the quick response!

**Comment by Integralist** [comment]
**Silly question**: is this particular GH issue related to why I would see all my macOS CPUs maxing out (to the point where the fan is kicking in!) and yet the CPU column shows at most ~30% being used rather than what I would expect to see which is multiple processes all hitting 90+% CPU usage...

<img width="2026" alt="Screenshot 2021-12-17 at 11 35 38" src="https://user-images.githubusercontent.com/180050/146539340-3c739339-3397-4a15-9fc1-fb457c03b72c.png">

**Comment by ddrcoder** [comment]
The lack of this is particularly significant when I'm working on a big server with 56 threads. I almost never see CPU usage above 100/56  = 1.8%. I far prefer the representation which considers 100% to be 1 core. This nicely captures the extent to which a process is parallelized. For the vast majority of processes I'm monitoring, so the range of [0, 1.7%] isn't that helpful.

**Comment by database64128** [comment]
I just built a new desktop PC with i9-13900K (32 threads) and the lack of this feature now significantly affects my use of bottom.

> I was wondering if anyone actually wants both columns or if people would prefer to choose. In that case it wouldn't have to be a separate column, maybe just a command line switch, similar to how `--current_usage` works. For example, I wouldn't need the normalized column at all, but the non-normalized is useful. Having something running at 100% is obviously saturating one core and the CPU is a bottleneck for it, while going on 16% is much less obvious.
> 
> I don't feel like doing the refactoring for the customization of columns, but if the command-line option was enough, I could give it a try.

This is exactly what I want. I made a quick attempt to implement it: https://github.com/database64128/bottom/tree/per-core-percentage

@ClementTsang What do you think? If you are OK with this approach, I can open a PR.

**Comment by ClementTsang** [comment]
Marking this as done, available as `--unnormalized_cpu`.
