### ISSUE TITLE
config file not respected

### ISSUE THREAD

**Issue by dkwo** [ClementTsang/bottom#498]
If I set some options in
```
$ cat .config/bottom/bottom.toml
basic = true
# battery = true
```
say `basic` or `battery`, they are not honoured by `btm`.
Of course, everything works if I use instead `btm -b`, or `btm --battery`, respectively.
```
$  btm -V
bottom 0.6.1
```
This is packaged on Void Linux, see [here](https://github.com/void-linux/void-packages/blob/master/srcpkgs/bottom/template) and [here](https://github.com/void-linux/void-packages/blob/master/common/build-style/cargo.sh) for the cargo buildstyle.
My system:
```
$ xuname
Void 5.12.10_1 x86_64-musl GenuineIntel uptodate rrnFFFFFFF
```
My terminal is `st`, shell is `bash`.
Thanks.

**Comment by ClementTsang** [comment]
You have to put it under the flags section in the toml file:

```toml
[flags]
battery = true
basic = true
```

Please try that and get back to me.

**Comment by dkwo** [comment]
That solves it, thank you.
