### ISSUE TITLE
Modularity with widget placement

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#51]
## Describe the feature request

_Why should we consider this feature request? Describe why, and/or how you think this feature will solve the issue, or overall improve the application:_

Some people might not like the default placement of widgets that I provide.  It seems like a decent idea to provide the option of rearranging them.

I personally think that doing so via purely config files is fine; doing it through command line sounds incredibly messy.

### Current Status

_Provide any additional context or details here. What needs to be done, why, etc:_

- [x] This will require redoing how we currently manage widget movement (that's hard coded)

- [x] Planning out *how* we plan to allow customization - what things will we let users change?  What things will we not?

- [x] Configuration files and format

- [x] Getting canvas to accept this layout

- [x] Movement 

- [x] Expanded mode

- [x] Default widget option

- [x] Basic mode - how will this play out?

- [x] Cleanup if required (currently, some FIXMEs)

- [ ] Testing

**Comment by ferrettim** [comment]
i was about to open an issue on this, so nice that it's here. will this include not displaying certain widgets? the disks widget, for example, is useless on zfs drives so it would be nice to turn it off.

**Comment by ClementTsang** [comment]
Yeah, I'm planning on making that configurable.  So you could display, say, only CPU/Mem/Processes if you wanted.
