### ISSUE TITLE
Feature Request: Add the ability to temporarily focus on one of the widgets

### ISSUE THREAD

**Issue by IndianBoy42** [ClementTsang/bottom#516]
### Describe the feature request

Sometimes I mainly just want to look at the process list or at the CPU graph. 
Or I have a smaller terminal window (for example if its just one split in tmux), and I can't really see anything in enough detail.

In both cases it would be nice to be able to look at one widget at a time, but I can't seem to find an easy way to do this now

**Comment by ClementTsang** [comment]
`e` key expands a widget.

![image](https://user-images.githubusercontent.com/34804052/122933494-b0a47b00-d33c-11eb-8723-584822b2f1d5.png)

![image](https://user-images.githubusercontent.com/34804052/122933523-b7cb8900-d33c-11eb-9b9c-b7c1d6122f91.png)
