### ISSUE TITLE
CPU usage % exceeds 100% when running a VM

### ISSUE THREAD

**Issue by hbina** [ClementTsang/bottom#523]
## Describe the bug

Percent exceeds 100% when using VirtualBox?
![Screenshot (2)](https://user-images.githubusercontent.com/6733660/123499315-70106e80-d668-11eb-8099-5643a4264815.png)

## What operating system/architecture are you using?

Windows x86_64

## What terminal are you using `bottom` on?

The new Windows Terminal.

## What version are you on?

```bash
PS C:\Users\Hanif> btm --version
bottom 0.6.1
PS C:\Users\Hanif> cargo --version
cargo 1.53.0 (4369396ce 2021-04-27)
PS C:\Users\Hanif>
```

## How did you install `bottom`?

Installed using `cargo`.

## How can we reproduce this?

I think can be reproduced by running VirtualBox and running a VM.

## What is the actual behaviour?

Percent implies it shouldn't ever go beyond 100%...Puts into question if the rest sums up to 100% at all?

## What is the expected behaviour?

It should at worst cap at 100%.

**Comment by ClementTsang** [comment]
Hmmm, interesting.  Let me see if I can reproduce.

**Comment by ClementTsang** [comment]
Chances are if it's Windows then it's actually on sysinfo's side, as I just use their library for Windows stats, but I'll see if it's on my side.

**Comment by ClementTsang** [comment]
Alright, can reproduce.  Looking into today or tomorrow...

**Comment by ClementTsang** [comment]
Gah, I know what the issue is - I missed the memo to divide the usage by the number of cores in sysinfo.  This used to not be the case, and I ended up overlooking it!

**Comment by ClementTsang** [comment]
Should be fixed in master now.  I'll be deploying 0.6.2 sometime on Saturday if you want to wait a bit, or you can just directly install from master.

Let me know if something's still broken, and feel free to reopen the issue.  Thanks for catching this!
