### ISSUE TITLE
No disk, temp or memory information

### ISSUE THREAD

**Issue by tirohia** [ClementTsang/bottom#528]
## Describe the bug
No temperature or disk sensors found

## What operating system/architecture are you using?
Linux Mint 19
4.15.0-142-generic

## What terminal are you using `bottom` on?
Quake, Gnome Terminal. 

## What version are you on?
Nightly (0.6.2)

## How did you install `bottom`?
sudo snap install bottom

## How can we reproduce this?
No config file used. No flags used. 

## What is the actual behaviour?
Memory graph remains static and empty. Disk and temp widgets display "No Fensors Found"

## What is the expected behaviour?
Display of the relevant details. 

After much digging, I thought this might have something to do with heim not being present, I eventually figured out (I think, very new to rust) that Heim doesn't have binaries to install. At the very least, the heim pages don't provide any information on how to install any, if they do exist. There's no error messages, so I'm not sure where to start to provide information for you to be able to debug this. Happy to take direction.

**Comment by ClementTsang** [comment]
Interesting issue.  I'll see if I can reproduce.

Heim is just a library that extracts information through stuff like `/proc`, so I don't think that's the issue.

**Comment by ClementTsang** [comment]
If possible, could you send a screenshot of what you're seeing?

**Comment by tirohia** [comment]
The other sections appear to be working. It's just the three in the middle appear static.

![bottomScreenShot](https://user-images.githubusercontent.com/4374479/123563037-6c1a5300-d806-11eb-8628-42a1bd6009e6.png)

**Comment by ClementTsang** [comment]
I can reproduce this through Ubuntu 18.04.  However, I can *only* reproduce it through snap - if I manually install through my .deb package, it works fine.

If possible, could you try installing through the .deb file as well, like so:

```bash
curl -LO https://github.com/ClementTsang/bottom/releases/download/0.6.2/bottom_0.6.2_amd64.deb
sudo dpkg -i bottom_0.6.2_amd64.deb
```

and run with `btm`, and let me know if it works?

**Comment by tirohia** [comment]
That works (which is excellent, thank you). It's something to do with the snap install then.

**Comment by ClementTsang** [comment]
Good to hear.  Not sure what's wrong with the snap install, unfortunately, as I don't maintain it.

**Comment by ClementTsang** [comment]
Took a peek at snaps, seems like you have to manually enable the permissions?  So to display memory usage, I needed to add:

```bash
sudo snap connect bottom:system-observe :system-observe
```

to get it to run on my Ubuntu VM when I ran `snap run bottom`.  I feel like this should probably be documented by whoever is maintaining the snap, but I'm not sure what is expected for packages in the snap ecosystem.

Going to close as this problem is resolved otherwise.
