### ISSUE TITLE
bottom-git AUR package has an invalid version name

### ISSUE THREAD

**Issue by LordMZTE** [ClementTsang/bottom#529]
The `bottom-git` AUR package currently has the version number `0.6.3-nightly.1158.gc628645`
but it looks like this isn't valid. According to the output of `makepkg`, the `-` in the
version number is an invalid character, and thus the package fails to install.

# Logs
```
==> Making package: bottom-git 0.6.2.1151.ga626eee-1 (Di 29 Jun 2021 14:03:02 CEST)
==> Retrieving sources...
  -> Updating bottom git repo...
Fetching origin
==> Validating source files with sha256sums...
    bottom ... Skipped
==> Making package: bottom-git 0.6.2.1151.ga626eee-1 (Di 29 Jun 2021 14:03:08 CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating bottom git repo...
Fetching origin
==> Validating source files with sha256sums...
    bottom ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of bottom git repo...
Cloning into 'bottom'...
done.
==> Starting pkgver()...
==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
==> ERROR: pkgver() generated an invalid version: 0.6.3-nightly.1158.gc628645
error: failed to build 'bottom-git-0.4.3.791.g3ffa437-1':
```

**Comment by ClementTsang** [comment]
Gah.  Didn't realize this would affect AUR, thought it was a harmless change to better help users understand what version they're on.

FWIW I don't maintain this package, but I can roll back this change for now I suppose.

**Comment by ClementTsang** [comment]
TBH it would probably make more sense for the PKGBUILD to manually tweak the grabbed version of the repo to fit AUR standards, and not the other way around, but I'll change it on my side for now.

**Comment by ClementTsang** [comment]
Tried building, I think it seems fine?  Closing for now in that case.

**Comment by ClementTsang** [comment]
Just a heads-up, it's possible that I change this back in the future as I personally prefer this naming convention and think it's a much clearer way of denoting that a build is not stable (helps with bug reports too).  There's a posted workaround on that AUR package, hopefully the maintainer incorporates the fix.

**Comment by LordMZTE** [comment]
Thanks! The package builds now.
