### ISSUE TITLE
Outdated config generated on first run

### ISSUE THREAD

**Issue by duongdominhchau** [ClementTsang/bottom#541]
## Describe the bug

The config generated on first run doesn't include the key `hide_time`, but manually set it to `true` in the config does have effect.

## What operating system/architecture are you using?

- OS: ArchLinux
- Architecture: x86_64

## What terminal are you using `bottom` on?

Alacritty

## What version are you on?

0.6.2 and 0.6.3-7392b56

## How did you install `bottom`?

- 0.6.2: Prebuilt AUR package (`bottom-bin`)
- 0.6.3-7392b56: Compiled using the script on AUR (`bottom-git`)
```
$ rustc --version
rustc 1.55.0-nightly (d2b04f075 2021-07-07)
```

## How can we reproduce this?

Ensure there is no config file and run `btm`, the default config will be generated.

## What is the actual behaviour?

The generated config doesn't include the key for `hide_time`.

## What is the expected behaviour?

The generated config has the key `hide_time` with description.

**Comment by ClementTsang** [comment]
Thanks for the report, will fix in a bit.
