### ISSUE TITLE
inaccurate report of memory usage

### ISSUE THREAD

**Issue by foodornt** [ClementTsang/bottom#544]
Before you report, please take a look at [Troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting) to see if there's already an answer to your problem. Also check out [existing issues](https://github.com/ClementTsang/bottom/issues) and [known problems](https://clementtsang.github.io/bottom/nightly/support/#known-problems) to see if your problem is already reported/known.

Also, **please fill in all fields if possible** - if the issue is too hard to reproduce or vague, it may not be fixed!

## Describe the bug

Inaccurate report of memory usage

## What operating system/architecture are you using?

Please mention what operating system, version, and architecture you're experiencing the problem on (ex: macOS 10.13, x86_64). Please also ensure that your system is [on the list of supported systems](https://github.com/ClementTsang/bottom#support) - bug reports on unsupported systems are likely to be closed.

Linux x86_64

## What terminal are you using `bottom` on?

Kitty

## What version are you on?

0.5.7

## How did you install `bottom`?

Through the [AUR](https://aur.archlinux.org/packages/bottom/), built with rust 1.52.1

## How can we reproduce this?

No idea.

## What is the actual behaviour?

Showing inaccurate memory usage.

## What is the expected behaviour?

Showing less memory usage

![image](https://user-images.githubusercontent.com/40924367/125798205-6467fc80-0b1c-4f09-bb23-2d341d3ce1de.png)

the `free` command matches the gotop report, unlike btm which shows more memory usage

**Comment by ClementTsang** [comment]
Is this reproducible on 0.6.2?

**Comment by ClementTsang** [comment]
Anyways it's probably some weird conversion issue between GiB and GB (or similar).  I'll take a look later.

**Comment by foodornt** [comment]
> Is this reproducible on 0.6.2?

Yep, but now instead of showing 7.8 gigs of ram it shows 7.5
both htop and gotop show less ram usage

**Comment by ClementTsang** [comment]
Yeah, I see what you mean.  I may have accidentally messed with this when trying to make it more accurate for Windows.  I'll look in a bit.

**Comment by ClementTsang** [comment]
Found the problem.  Seems to be a combination of me misunderstanding the best ways to get memory usage through heim, and a *tiny* bug in heim that seems to have caused unit conversions to go awry for memory totals.  Turns out macOS also had some issues too.

The linked PR should hopefully fix those issues, I'll deploy a new version probably this weekend.  If you want the changes sooner, look into either the nightly builds or the `bottom-git` (I think that's what it's called?) AUR package.

Anyways, thanks for the report, it's been there for quite a while it seems.  If there are still issues feel free to reopen.

**Comment by foodornt** [comment]
Thank you a ton, I guess it works fine now, but can I display that in GB instead of GiB?

**Comment by ClementTsang** [comment]
Probably as a new feature in the future, not hard to do but not super high priority rn.

**Comment by Akari202** [comment]
I am encountering this issue, I just installed bottom 0.6.8. with cargo and it is massively underreporting my memory usage.

<img width="1280" alt="Screen Shot 2022-08-17 at 20 52 36" src="https://user-images.githubusercontent.com/84194114/185280804-0c2e48e7-3b69-4cdc-89a7-15f35f274fa4.png">

**Comment by ClementTsang** [comment]
@Akari202 I'll open a new issue since your problem is likely different from the one addressed in this issue, I'm guessing the problem is with heim and that might be fixed when I switch everything possible over to sysinfo.
