### ISSUE TITLE
Laptop Mode

### ISSUE THREAD

**Issue by Byron** [ClementTsang/bottom#55]
## Describe the feature request

If the machine `btm` is running on has a battery, show additional information that is most vital to the users of portable computers, namely:

1. charge status in percent
1. time till full or empty, depending on whether the machine is connected to power
1. current amount of power consumption watts

Right now I have to use `battop` for this usecase, which comes with a 'big' TUI with a lot of additional information that is not that useful in practice. It's more of a demo for the underlying library displaying all the information there is about batteries.

## Additional context

I love `btm` for…

* …being configurable
* …being controllable with hotkeys
* …having all the information I could ask for

For me this already replaces `bandwhich` and the MacOS Activity Monitor, which has terrible performance.

With the integration of battery information, `btm` is the single go-to place to see what's going on with the machine.

Here is the information I usually look at in `battop`:

<img width="990" alt="Screenshot 2020-02-29 at 08 38 31" src="https://user-images.githubusercontent.com/63622/75597367-0b72ed00-5ad0-11ea-86b5-061917b670f7.png">

### Technical Notes

* it looks like on MacOS at least, the OS only provides new battery information every half a minute or so. I usually launch `battop` with `-d 10`, to refresh only every 10 seconds.

**Comment by ClementTsang** [comment]
Interesting suggestion!  I can definitely see why this can be useful.

**Comment by Byron** [comment]
Awesome, thanks a lot! I am looking forward to the next release.
