### ISSUE TITLE
Image links are broken in docs

### ISSUE THREAD

**Issue by CrispyBaguette** [ClementTsang/bottom#552]
The image links point to `https://clementtsang.github.io/[path_to image]`, but the images are located at `https://clementtsang.github.io/bottom/[version]/[path_to image]`.

See [this page](https://clementtsang.github.io/bottom/0.6.3/configuration/config-file/data-filtering/).

**Comment by ClementTsang** [comment]
Thanks for the heads up, will fix in a sec.

**Comment by ClementTsang** [comment]
Should be fixed for 0.6.3 and nightly, feel free to open a new issue if you spot anything else that's broken.
