### ISSUE TITLE
[Feature] Add a setting to make text bold

### ISSUE THREAD

**Issue by ondohotola** [ClementTsang/bottom#556]
Is there a way of having the information on the screen be in bold?

Text and Braille?

Thanks, el

**Comment by ClementTsang** [comment]
Currently no, can add in the future.

**Comment by ondohotola** [comment]
WOuld be a nice feature for older eyes :-)-O

el

On 2021-07-22 16:18 , Clement Tsang wrote:
> Currently no, can add in the future.
> 
> —
> You are receiving this because you authored the thread.
[...]

-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***NA             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
      Book your Covid-10 Vaccination at https://c19.idtoday.com.na

**Comment by ClementTsang** [comment]
Haha, yeah, that sounds like it might be helpful.

For what its worth, it shouldn't be hard to do in terms of just adding bolded text (like it would take an hour probably), though I want to work on some other stuff first (#159) to make configuring it easier for users.

**Comment by ondohotola** [comment]
Clement,

great, thanks.

el

On 2021-07-22 17:58 , Clement Tsang wrote:
> Haha, yeah, that sounds like it might be helpful.
> 
> For what its worth, it shouldn't be hard to do in terms of just adding
> bolded text (like it would take an hour probably), though I want to
> work on some other stuff first (#159
> <https://github.com/ClementTsang/bottom/issues/159>) to make
> configuring it easier for users.
> 
> —
[...]
-- 
Dr. Eberhard W. Lisse   \         /       Obstetrician & Gynaecologist
***@***.***NA             / *      |  Telephone: +264 81 124 6733 (cell)
PO Box 8421 Bachbrecht  \      /  If this email is signed with GPG/PGP
10007, Namibia           ;____/ Sect 20 of Act No. 4 of 2019 may apply
	 Book your Covid-10 Vaccination at https://c19.idtoday.com.na

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Why add this to Bottom instead of merely configuring your system to utilisw bodl text? I am not able to comprehend why observation of solely Bottom is difficult none else.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Read my comment again. I merely ask why this is specifically useful for Bottom. Why not configure all of your system to utilise bold text rather than each program?

**Comment by vcrn** [comment]
Regarding your previous comment, should #159 (which you mention some comments up) be solved first before solving this issue?

**Comment by ondohotola** [comment]
> > [#556 (comment)](https://github.com/ClementTsang/bottom/issues/556#issuecomment-1111316893)
> 
> @ondohotola, observe my comment again. I merely ask why this is specifically useful for Bottom. Why not configure all of your system to utilise bold text rather than each program?
> 
> I do support the FR. However, you're definitely experiencing an X/Y problem.

Besides that I don't understand what a X/Y problem is, while I can read iTerm2 just fine, I find especially the Braille difficult to see somethine.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ClementTsang/bottom/issues/556#issuecomment-2258573111

@ondohotola, Google is your friend there, but https://en.wikipedia.org./w/index.php?title=XY_problem&oldid=1229184561#:~:text=The%20XY%20problem%20is%20a,resource%20mismanagement%2C%20and%20sub%2Dpar%20solutions contains a concise explanation. In this case, I mean that if bold text allows you to read better, then you should set it system-wide, or at the very least, terminal-wide, not at Bottom's level. Otherwise, no other commands shall be readable. I don't understand how braille support factors into Bottom's support for bold text.

**Comment by ClementTsang** [comment]
I was going to implement this regardless for styling reasons, so this discussion is becoming irrelevant.
