### ISSUE TITLE
Allwinner D1 Nezha - Working

### ISSUE THREAD

**Issue by heitbaum** [ClementTsang/bottom#564]
Thought you would like to know that btm 0.6.3 compiles and runs on Risc-V rv64gc

```
root@RVBoards:/tmp/bottom-0.6.3# rustc --version
rustc 1.52.1
root@RVBoards:/tmp/bottom-0.6.3# cargo --version
cargo 1.46.0
root@RVBoards:/tmp/bottom-0.6.3# more /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
root@RVBoards:/tmp/bottom-0.6.3# uname -a
Linux RVBoards 5.4.61 #22 PREEMPT Wed Jun 16 07:27:49 UTC 2021 riscv64 GNU/Linux
```

<img width="1408" alt="btm 0.6.3" src="https://user-images.githubusercontent.com/6086324/127741557-ba9ea481-8601-4f17-9eda-6766e1263b73.png">

**Comment by ClementTsang** [comment]
Neat!  Might add a note in the docs that it runs.

**Comment by ClementTsang** [comment]
Added some documentation/CI stuff in https://github.com/ClementTsang/bottom/pull/565, closing this.  Thanks for the heads up!
