### ISSUE TITLE
Sorting feature for Disks table

### ISSUE THREAD

**Issue by mmahmoudian** [ClementTsang/bottom#567]
### Describe the feature request

It would be very handy to be able to sort the Disks table. For example I'm constantly looking to know what disk has the lowest free space and try to manage the files. in the [sorting section of the documentation](https://clementtsang.github.io/bottom/nightly/usage/widgets/process/#sorting) it is worded in a way that all tables can be sorted (by mouse, <kbd>s</kbd>, or <kbd>F6</kbd>), but neither of them work in Disks table. Considering that the sorting concept is already implemented, I believe it should not be a big tasks to add this (but I don't know Rust enough, so I can well be wrong 😅 )

FWIW I'm using v0.6.3 on Manjaro 

P.s: This is an awesome tool and I love using it. Keep up the good work, you rock!

**Comment by ClementTsang** [comment]
Yep, this is something I'm currently working on as part of a larger widget rewrite (and also tackles https://github.com/ClementTsang/bottom/issues/429).
