### ISSUE TITLE
Per-core cpu usage column in Processes view

### ISSUE THREAD

**Issue by up-to-you** [ClementTsang/bottom#573]
### Describe the feature request

Currently, there is only %CPU column in Processes view, which is not informative if current CPU load is low and if some process use only single core.

To be more precise - we can compare Mac native Activity Monitor where we see 20% CPU usage (for example) for some process, but Bottom will show 0.1% in the best case. This difference may be due to calculation difference, since Activity Monitor show 20% for Single core and 200/300/400...% for 2/3/4 cores.

So, such additional column with Process per-core CPU usage (or Mode, or Config entry) will be very convenient and informative.

**Comment by ClementTsang** [comment]
Is this resolved through #496?

**Comment by up-to-you** [comment]
Yep, definitely ! This is the only missing thing which makes me open Activity Monitor on macos.

**Comment by ClementTsang** [comment]
Closing as #496 is completed and available on nightly as `--unnormalized_cpu`.
