### ISSUE TITLE
IO stats per process

### ISSUE THREAD

**Issue by alicektx** [ClementTsang/bottom#58]
Hi! It would be nice if btm displayed & could sort process per IO:
for example, say when 'entering' the full screen processes' view.
Such would eliminate the need of firing up a secondary terminal with iotop...

Reason i mentioned the full screen processes' view, 
is simply because there currently exists lots of  'free estate' there, 
and thereby things wouldn't look clunky & overcrowded,
on the standard 'default' view with all the widgets on display.
That's just a (hopefully not silly) idea for possible design...
![processfullscreen](https://user-images.githubusercontent.com/28889624/75611231-5832e400-5b21-11ea-997c-8bd3eb4f5850.png)

[zenith](https://github.com/bvaisvil/zenith), is another Rust-written program inspired by htop/gotop etc:
 that's pretty much where the idea above came to mind,
for suggesting the addition of per-process iotop stats...

Hopefully i'm not annoying you with the above request in the first place,
and you'll consider something among those lines at some point down the road...
All the best!

**Comment by ClementTsang** [comment]
Sounds like a good idea.

**Comment by alicektx** [comment]
Such a nice surprise early this morning - deeply thank you for your work!! :smiley:
