### ISSUE TITLE
May be make search case insensitive?

### ISSUE THREAD

**Issue by for-coursera** [ClementTsang/bottom#6]
When searching for processes in the search widget (called by either `/` or `<C-f>`), may be make this search case insensitive?

(Otherwise, everything seems to be working fine on macOS.)

**Comment by ClementTsang** [comment]
Hmmm, it should be case sensitive, it's just filtering using regex - I can't seem to reproduce this either (ie: typing 'discord' will not find the 'Discord' process for me on Linux).  Could you send me an example/screenshot of the case where it's not properly filtering?

**Comment by for-coursera** [comment]
> Hmmm, it should be case sensitive

It certainly is :) 

And I'm asking you to consider making to **in**sensitive.

> ie: typing 'discord' will not find the 'Discord' process

Exactly :). But don't you think that pressing Shift (and also *not forgetting* to do this) while searching for a process kinda slows down the the whole workflow?

Anyway, thanks for your app ;)

**Comment by ClementTsang** [comment]
Oh, oops.  I can't read.  I blame my train breaking down for an hour.

Hmm... I might consider adding a way to toggle between regex and just simple search.  Would that work?

**Comment by for-coursera** [comment]
> I might consider adding a way to toggle between regex and just simple search

Sounds good but won't it be still an additional key press? May be a command line option instead?

**Comment by ClementTsang** [comment]
I'm thinking of adding some way of toggling but allowing a command line flag to allow you to choose a default search method upon first opening search.  I'll take a look today and see how that might play out.

**Comment by ClementTsang** [comment]
Along with having added the option a while ago, made case insensitive default with this commit: 616ba01be0804b62918e4d3ea49695beb81ed784
