### ISSUE TITLE
PageUp/PageDn support on Process Widget

### ISSUE THREAD

**Issue by Yohe-Am** [ClementTsang/bottom#620]
### Describe the feature request

And/or a way to configure mouse scroll speed. As someone used to htop, the scroll speed on the Process Widget's coupled with the lack of PgDn/PgUp makes a mighty ergonomic hurdle. 

Willing to open a PR for this but I hesitate as btm seems to be in the middle of a large refactor. Do say if it won't be a bother.

**Comment by ClementTsang** [comment]
Hi - yeah, I can add something like that. And yeah, I would give it a bit of time, should hopefully finish the refactoring stuff soon-ish.

**Comment by yardenac** [comment]
This is honestly what's keeping me from leaving htop

**Comment by ClementTsang** [comment]
Added into master, which should come out on nightly soon - note that it might be a while before I release a major version with this feature, since I'm only planning on releasing a major version after I finish an internal rewrite.

**Comment by yardenac** [comment]
Wow, thank you!! Much obliged.
