### ISSUE TITLE
Windows: Temperature reported (only when elevated) at 25C, this is definitely a false reading

### ISSUE THREAD

**Issue by PloniAlmoni** [ClementTsang/bottom#624]
## Describe the bug

Bottom on Windows displays 25C as the temperature of my CPU at all times, this is inaccurate.

## What operating system/architecture are you using?

Windows 10 Home x86_64

## What terminal are you using `bottom` on?

Windows Terminal

## What version are you on?

0.6.4

## How did you install `bottom`?

MSI from the release page.

## How can we reproduce this?

Running btm with default configuration in an elevated terminal (non-elevated displays no temps at all).

## What is the actual behaviour?

![image](https://user-images.githubusercontent.com/8719607/145729739-e400628b-e0b5-4aa9-bef3-61cbf6f7e36f.png)

## What is the expected behaviour?

Accurate and varying with load and fans temperature.

What do you believe the expected behaviour should be given these steps?

A working temperature readout.

**Comment by ClementTsang** [comment]
> Do note this is a six core processor, a i7-9750H, and only three cores are displayed out of six. Should I file another bug?

Just to be sure, is it just hidden off screen (like you need to scroll to it)?

And I'll take a look at the temp issue, I rely on another library to do temperatures so it might be an upstream issue.

**Comment by PloniAlmoni** [comment]
Oh, the cores are hidden off-screen, like you said. The temperatures are definitely off though, now it's 30C somehow after waking up from sleep. 25C was definitely incorrect, however.

**Comment by PloniAlmoni** [comment]
it's also only CPU temperature, this laptop has a discrete GPU which has its own temperature readout in other programs.

**Comment by ClementTsang** [comment]
Hi, just as a quick sanity check - does it work if you try running bottom as an [administrator](https://docs.rs/sysinfo/0.22.3/x86_64-pc-windows-msvc/sysinfo/struct.Component.html)?  I think it's unlikely to change, but might as well try it.

If it doesn't work, I'll take a bit closer of a look if possible, but it's a bit tricky as I can't reproduce it.

For tracking, there's a related upstream issue: https://github.com/GuillaumeGomez/sysinfo/issues/546 - might look into filing/taking a look upstream.

**Comment by ClementTsang** [comment]
Note to self - there's a related upstream issue here: https://github.com/GuillaumeGomez/sysinfo/issues/546 - might look into filing/taking a look upstream.
