### ISSUE TITLE
CPU parsing will fail due to too short of a return value

### ISSUE THREAD

**Issue by hellow554** [ClementTsang/bottom#636]
## Describe the bug

When opening bottom the process panel is and stays empty

## What operating system/architecture are you using?

```
$ uname -a
Linux localhost 5.4.0 #1 SMP Thu Apr 22 16:18:59 MSK 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## What version are you on?

master branch

## How did you install `bottom`?

git / cargo run
cargo 1.53.0
release: 1.53.0

## How can we reproduce this?

Not entirely sure, how to reproduce this.
My Linux only has 9 fields in `/proc/stat` which will return in an Err at 

https://github.com/ClementTsang/bottom/blob/d6a112bee48c938db9b070d461e365f226b275c9/src/app/data_harvester/processes/linux.rs#L53-L59

Here's an excerpt:

```
$ cat /proc/stat
cpu  257822 0 15955 2518556 0 0 0 0
cpu0 38317 0 2412 308250 0 0 0 0
cpu1 33930 0 2145 312941 0 0 0 0
cpu2 30837 0 1811 316401 0 0 0 0
cpu3 29398 0 1749 317896 0 0 0 0
cpu4 30952 0 2009 316104 0 0 0 0
cpu5 32710 0 1894 314455 0 0 0 0
cpu6 31076 0 1960 316023 0 0 0 0
cpu7 30599 0 1971 316483 0 0 0 0
intr 0
swap 0 0

ctxt 1576034
btime 1640091689
processes 18732
procs_running 1
procs_blocked 0
```

I'm not entirely sure why I do have less fields than normal, but it should still be possible to parse the relevant information since most of them are zero? Htop is able to display my processes.

**Comment by hellow554** [comment]
Probably this code, could be rewritten:

https://github.com/ClementTsang/bottom/blob/d6a112bee48c938db9b070d461e365f226b275c9/src/app/data_harvester/processes/linux.rs#L61-L69

```rust
let user = val.get(1).and_then(|x| x.parse::<f64>().ok()).unwrap_or(0_f64);
```

**Comment by ClementTsang** [comment]
Thanks for catching this - it's ironic as I think I reported a similar issue before on another crate, but I guess I made the same mistake. I'll take a look and get a fix out when I can.

**Comment by ClementTsang** [comment]
Bit of a weird question, but are you using WSL/VM, or is this an install on bare metal?

**Comment by hellow554** [comment]
> Bit of a weird question, but are you using WSL/VM, or is this an install on bare metal?

It is a root server from strato.
I think they are using some kind of custom kernel but I can't any information about that.

**Comment by ClementTsang** [comment]
Pushed a fix.  I'll deploy it today or tomorrow.
