### ISSUE TITLE
fish completions now a directory?

### ISSUE THREAD

**Issue by briandipalma** [ClementTsang/bottom#644]
## Describe the bug

Tried an install via the `.deb` in the releases and I got some completion errors afterwards. Not sure if the fish completions are meant to be directories? The other completions I have installed are plain files.

![image](https://user-images.githubusercontent.com/1597820/147484156-388613cf-908e-4e94-91ec-d70ec557bc69.png)

## What operating system/architecture are you using?

Pop!_OS 21.10

## What terminal are you using `bottom` on?

Kitty

## What version are you on?

0.6.6

## How did you install `bottom`?

.deb file from GH releases.

**Comment by ClementTsang** [comment]
Hm, I'll look into it.

**Comment by ClementTsang** [comment]
Ah, I think I know what happened... I might have messed something up in the `cargo-deb` configuration.  I'll regenerate them as necessary if that's the case and make a note here after that's dealt with.

**Comment by ClementTsang** [comment]
Yep, broke from 0.6.5 onward.  I'll replace the two.

**Comment by ClementTsang** [comment]
Updated both of the `.deb` files, hopefully it should be fixed.

**Comment by briandipalma** [comment]
Yep, tested and it works great, thanks!
