### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6 not found

### ISSUE THREAD

**Issue by siferati** [ClementTsang/bottom#650]
## Describe the bug

Crash on start with errors:
```
btm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by btm)
btm: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by btm)
```

## What operating system/architecture are you using?

Ubuntu 20.04.3 LTS x86_64, inside Windows 11 10.0.22000.376, WSL 0.50.2.0.

## What terminal are you using `bottom` on?

bash

## What version are you on?

0.6.6

## How did you install `bottom`?

Following readme instructions:

```
curl -LO https://github.com/ClementTsang/bottom/releases/download/0.6.6/bottom_0.6.6_amd64.deb
sudo dpkg -i bottom_0.6.6_amd64.deb
```

**Comment by ClementTsang** [comment]
Ugh, I forgot that this might be an issue since I regenerated the .deb file.

Let me do that again...

**Comment by ClementTsang** [comment]
If you don't want to wait, it should work fine if you just manually build it yourself, but otherwise it's gonna take me a bit of time to regenerate the `.deb` files.  I'll put an update after I'm done that.

**Comment by ClementTsang** [comment]
For context for anyone interested, I regenerated the `.deb` files via `cargo-deb` on my Arch machine when trying to fix #644 because I didn't want to deal with messing around with some actions/git cherry picking, and completely forgot that this has the very likely issue of causing GLIBC problems.

Going to fix this my cherry-picking in the #644 patch into the appropriate tags and rebuilding via the `nightly` action, and updating the `.deb` files as appropriate.

**Comment by ClementTsang** [comment]
@siferati alright, could you try again?  Just updated the file at https://github.com/ClementTsang/bottom/releases/download/0.6.6/bottom_0.6.6_amd64.deb

**Comment by siferati** [comment]
Thanks, it's working fine now

**Comment by KeithTt** [comment]
Similar problem here, `btm: /lib64/libc.so.6: version 'GLIBC_2.18' not found (required by btm)`.

OS version: CentOS7

May I use one release which does not depend on GLIBC_2.18?

**Comment by ClementTsang** [comment]
https://github.com/ClementTsang/bottom/releases/download/0.6.8/bottom_x86_64-unknown-linux-gnu2-17.tar.gz should only require 2.17, but I don't have a debian file for it unfortunately.
