### ISSUE TITLE
Can't see temperatures -- no sensors found

### ISSUE THREAD

**Issue by siferati** [ClementTsang/bottom#652]
## Describe the bug

Can't see any temperature readings

![image](https://user-images.githubusercontent.com/15384781/147830310-55a8fd12-5a8d-4f41-bf06-9509090297e7.png)

## What operating system/architecture are you using?

Ubuntu 20.04.3 LTS x86_64, inside Windows 11 10.0.22000.376, WSL 0.50.2.0.

## What terminal are you using `bottom` on?

bash

## What version are you on?

0.6.6

## How did you install `bottom`?

Following readme instructions:

```
curl -LO https://github.com/ClementTsang/bottom/releases/download/0.6.6/bottom_0.6.6_amd64.deb
sudo dpkg -i bottom_0.6.6_amd64.deb
```

**Comment by ClementTsang** [comment]
This is a known issue and a limitation of WSL as far as I'm aware: https://clementtsang.github.io/bottom/nightly/support/official/#windows.  As such, I don't think I can fix this - IIRC they don't get sensor data.

In hindsight I should probably duplicate the WSL documentation line for Linux.
