### ISSUE TITLE
Showing memory usage in % and value

### ISSUE THREAD

**Issue by RaZ0rr-Two** [ClementTsang/bottom#655]
### Describe the feature request
I would like to see the memory usage in percentage in value as well as in percentage. Otherwise, a key to switch between them would be good as well. Now, I have to exit bottom and use `btm --mem_as_value` to see memory usage in value. To see in percentage, have to then exit and use  `btm`.

**Comment by ClementTsang** [comment]
Is this for processes?  If so, you can just hit `%` to do this.

**Comment by RayZ0rr** [comment]
Oh, thats what I was looking for. Thank you. Damn missed it in the [Docs](https://clementtsang.github.io/bottom/nightly/usage/widgets/process/)
