### ISSUE TITLE
`bottom` panics on newly installed PopOS! system

### ISSUE THREAD

**Issue by LukeMathWalker** [ClementTsang/bottom#657]
## Describe the bug

`bottom` panics when invoked. The printed error mentions a missing environment variable but it does not provide enough information to identify _which_ environment variable is missing.

## What operating system/architecture are you using?

```
$ uname -a
Linux pop-os 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux
```

## What terminal are you using `bottom` on?

Alacritty + bash.

## What version are you on?

`0.1.8`.

## How did you install `bottom`?

`cargo install`.

## How can we reproduce this?

Invocation is enough to trigger the issue.

## What is the actual behaviour?

The command panics and prints

```
# 2022-01-11 9:18:55 [pid: 10763] [pidns: 4026531836]
ERROR: ...
|-- file: /home/lucap/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.1.8/src/bins/btm.rs
|-- line: 37
`-- column: 9
Caused By: ...
|-- file: /home/lucap/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.1.8/src/bins/btm.rs
|-- line: 37
`-- column: 41
    Caused By:
    # 2022-01-11 9:18:55 [pid: 10763] [pidns: 4026531836]
    ERROR: ...
    |-- file: /home/lucap/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.1.8/src/bins/btm.rs
    |-- line: 81
    `-- column: 20
    |-- file: /home/lucap/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.1.8/src/bins/btm.rs
    |-- line: 83
    `-- column: 64
        Caused By: environment variable not found
        |-- file: /home/lucap/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.1.8/src/bins/btm.rs
        |-- line: 83
        `-- column: 64
thread 'main' panicked at 'explicit panic', /home/lucap/.cargo/registry/src/github.com-1ecc6299db9ec823/ruc-0.6.6/src/err.rs:90:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ClementTsang** [comment]
> 0.1.8

Er, sorry, but... does this happen with any *recent* version of bottom...?

**Comment by ClementTsang** [comment]
Wait, I don't even have a 0.1.8 version.

You're looking at https://crates.io/crates/btm, which is *not* this application.

**Comment by ClementTsang** [comment]
Going  to close this as this isn't a bug for this program.

**Comment by LukeMathWalker** [comment]
Lol, my bad 🤦🏻

**Comment by ClementTsang** [comment]
Haha, don't worry. I can see why someone makes that mistake, I might add a note in the README to not mix up the two.

Definitely threw me for a spin though, I was thinking "wait, did I even release a 0.1.8???" and started digging through crates.io.
