### ISSUE TITLE
change the order of columns in the process widget

### ISSUE THREAD

**Issue by ayushnix** [ClementTsang/bottom#662]
Hi! Thanks for creating `btm`. I wanted to replace `htop` without deviating too much from how it looks and `btm` seems good for this.

### Describe the feature request

I'd really like it if I could change the order of the columns inside the process widget. Specifically, I'd like to see `User` and `State` just after `PID`. So something like
- PID
- User
- State
- Name
...

This would resemble my htop configuration.

**Comment by ClementTsang** [comment]
Yes, this is something I already want to add, but is blocked by some refactor work (and IRL stuff).

**Comment by ayushnix** [comment]
> Yes, this is something I already want to add, but is blocked by some refactor work (and IRL stuff).

Yeah, I noticed the pinned issue. I guess I'll keep using `btm` for now and wait for this feature to land.
