### ISSUE TITLE
Output becomes blank when resizing

### ISSUE THREAD

**Issue by tlinford** [ClementTsang/bottom#664]
## Describe the bug
When resizing horizontally the terminal containing a running bottom instance, the output can disappear and afterwards the process becomes unresponsive, and high cpu usage can be observed.

## What operating system/architecture are you using?
Arch Linux: `Linux perihelion 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux`

## What terminal are you using `bottom` on?
`alacritty 0.10.0 (8a26dee0)`

## What version are you on?
`bottom 0.6.6`

## How did you install `bottom`?
`pacman`

## How can we reproduce this?
resize the alacritty window horizontally, reducing it's size.

## What is the actual behaviour?
here two instances of btm are running side by side, the one on the right is unresponsive and high cpu usage can be seen on the left:
![screenshot-2022-01-27T08:27:22](https://user-images.githubusercontent.com/7355179/151320920-8af8a0e1-8a4e-4248-8758-d7ff77994429.png)

**Comment by ClementTsang** [comment]
Huh, interesting. I'll take a look this weekend.

**Comment by ClementTsang** [comment]
Hmmm... trying on Arch, Alacritty 0.10, and I can't reproduce this.

The only thing I can think of right away (it's also 4am so I might be missing something obvious) that's different is that I'm using X/i3... and I see you're on sway. But that shouldn't have any effect, right...?

**Comment by tlinford** [comment]
strange - does not seem to be wayland related, just tested on gnome xorg session, and it happens there as well. Also happens with kitty.

here's a video showing how I trigger it, in case it helps:

https://user-images.githubusercontent.com/7355179/151327797-a8ba8a98-232a-4747-869a-697a419bcc55.mp4

I just installed via cargo as well, and still can reproduce.

In any case, not a big deal for me - was debugging a problem with alternate screen apps in zellij and bottom was my test case :)

**Comment by ClementTsang** [comment]
Thanks for confirming that my weird guess was incorrect! 

I see from the video you're reducing the horizontal size to a very small size before it seems to break - I think I know why then, and I guess I couldn't reproduce initially since my i3 config limits the min width to a bit larger than what you showed there.

I'll try reproducing tomorrow, hopefully I'll get a fix out soon.

**Comment by ClementTsang** [comment]
Alright, can reproduce, looking into now.

**Comment by ClementTsang** [comment]
Got a working fix, should be out on nightly shortly and I'll probably deploy a stable patch sometime this weekend.
