### ISSUE TITLE
WinGet package appears twice and installs regardless of current version

### ISSUE THREAD

**Issue by sharifhsn** [ClementTsang/bottom#672]
## Details

What is the issue? Please be clear and concise.

When I upgrade my system using `winget`, `bottom` will always update regardless of whether there is a new version or not. Also, the application appears twice in my installation despite me only installing it once.
![image](https://user-images.githubusercontent.com/61516383/152424620-08a85f03-425c-43bf-8b6b-3d991004c1eb.png)

Some notes:

- If the issue is specifically about an existing package/distribution, consider contacting the package maintainer
  instead in the appropriate location.

- If this issue is about supporting a new package manager/installation method,
  please do consider maintaining it yourself and sending in a PR, and I'll be glad accept it!
  See [the documentation](https://clementtsang.github.io/bottom/nightly/contribution/packaging-and-distribution/) for more information.

**Comment by ClementTsang** [comment]
I don't manage the winget packaging anymore, so I can't really help. I would take this issue to the [winget repo.](https://github.com/microsoft/winget-pkgs).

**Comment by ClementTsang** [comment]
Might be related to this issue: https://github.com/microsoft/winget-cli/issues/1392

**Comment by sharifhsn** [comment]
That seems to be exactly what's going on! Thank you for looking into it.
