### ISSUE TITLE
Move with ctrl + {h, j, k, l}

### ISSUE THREAD

**Issue by tiagovla** [ClementTsang/bottom#686]
I think a lot of people move around windows in vim with `ctrl + {h, j, k, l}`.
Is there a reason why these are commented?
https://github.com/ClementTsang/bottom/blob/9eabb061aaad8a1ebf6545dc8f36c98c1e622774/src/lib.rs#L164-L167

**Comment by ClementTsang** [comment]
They were just never really added, and now, they collide with some current keybinds.

However, I plan on adding custom keybinds at some point which probably solve this issue: https://github.com/ClementTsang/bottom/issues/454
