### ISSUE TITLE
Support for Linux ARM64/aarch64

### ISSUE THREAD

**Issue by balupton** [ClementTsang/bottom#709]
Currently bottom needs to be compiled through cargo on raspberry pi 4/400 machines. It would be nice if a precompiled binary was available.

Perhaps the build system from these rust packages could help:

- has arm64 builds among usual
    - https://github.com/sharkdp/bat
    - https://github.com/dandavison/delta
    - https://github.com/bootandy/dust
    - https://github.com/sharkdp/fd
    - https://github.com/sharkdp/hyperfine
    - https://github.com/XAMPPRocky/tokei
- has arm64 and apple silicon builds among usual
    - https://github.com/ajeetdsouza/zoxide

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Bottom appears to support my smartphone if installed and invoked by "http://f-droid.org/en/packages/com.termux.nix".

**Comment by balupton** [comment]
Seems the binaries are already provided for bottom, my mistake:

https://github.com/ClementTsang/bottom/releases/tag/0.6.8
