### ISSUE TITLE
environment variable not found - fatal panic - amz linux 2

### ISSUE THREAD

**Issue by SteveDevOps** [ClementTsang/bottom#716]
## Describe the bug

fatal panic on environment variable not found - line 83 btm.rs

btm                    

2022-04-29 01:52:20 +08:00:00 [pid: 17803] [pidns: 4026531836]
ERROR: ...
|--file: /home/sduys_linux1/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.6.5/src/bins/btm.rs
|--line: 37
`--column: 9
Caused By: ...
|--file: /home/sduys_linux1/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.6.5/src/bins/btm.rs
|--line: 37
`--column: 41
    Caused By: 
    # 2022-04-29 01:52:20 +08:00:00 [pid: 17803] [pidns: 4026531836]
    ERROR: ...
    |--file: /home/sduys_linux1/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.6.5/src/bins/btm.rs
    |--line: 81
    `--column: 20
    |--file: /home/sduys_linux1/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.6.5/src/bins/btm.rs
    |--line: 83
    `--column: 61
        Caused By: environment variable not found
        |--file: /home/sduys_linux1/.cargo/registry/src/github.com-1ecc6299db9ec823/btm-0.6.5/src/bins/btm.rs
        |--line: 83
        `--column: 61
thread 'main' panicked at 'explicit panic', /home/sduys_linux1/.cargo/registry/src/github.com-1ecc6299db9ec823/ruc-1.0.7/src/err.rs:132:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: ruc::err::RucError::print_die
   4: btm::cmd::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

## What operating system/architecture are you using?
amz linux 2

uname -a
Linux a-4lh7ze4rpjy4 4.14.275-207.503.amzn2.x86_64 #1 SMP Wed Apr 13 20:24:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

## What terminal are you using `bottom` on?

tilix 1.8.1
zsh 5.8.1 (x86_64-koji-linux-gnu)
oh-my-zsh framework
starship 1.5.4
branch:
commit_hash:
build_time:2022-03-28 16:13:58 -04:00
build_env:rustc 1.59.0 (9d1b2106e 2022-02-23),stable-x86_64-unknown-lin

## What version are you on?

btm v0.6.5

## How did you install `bottom`?
cargo install bottom

Please mention how you installed `bottom`. If you manually compiled it, please also mention your _Rust version_.

rustup show       
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/xxxxxx

stable-x86_64-unknown-linux-gnu (default)
rustc 1.59.0 (9d1b2106e 2022-02-23)

## How can we reproduce this?
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html

## What is the actual behaviour?
fatal crash/panic

## What is the expected behaviour?
successful execution

**Comment by ClementTsang** [comment]
Seems like you installed https://crates.io/crates/btm. This is *not* bottom. This is some other program that is named the exact same as the binary.

Please [follow the README's instructions for installation via cargo](https://github.com/ClementTsang/bottom#cargo):

```bash
cargo install bottom --locked
```

Closing as this is not an issue with bottom.

**Comment by SteveDevOps** [comment]
whups sorry about that @ClementTsang had "btm" on the brain...
