### ISSUE TITLE
Can't install on Amazon Linux arm64 instances.

### ISSUE THREAD

**Issue by Spunkie** [ClementTsang/bottom#723]
## Describe the issue

There are aarch64 releases here on github but when installing the repo on an arm64 system it does not work.

Here is the output when I try and enable the repo and install `bottom` on an amazon arm64 `t4g.nano` instance running `Amazon Linux 2`.
```shell
[ec2-user@<redacted> ~]$ sudo yum-config-manager --add-repo https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo
    Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
    adding repo from: https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo
    grabbing file https://pkgs.tailscale.com/stable/amazon-linux/2/tailscale.repo to /etc/yum.repos.d/tailscale.repo
    repo saved to /etc/yum.repos.d/tailscale.repo

[ec2-user@<redacted> ~]$ sudo yum -y copr enable atim/bottom
    Loaded plugins: copr, extras_suggestions, langpacks, priorities, update-motd
    copr done

[ec2-user@<redacted> ~]$ sudo yum -y install bottom
    Loaded plugins: copr, extras_suggestions, langpacks, priorities, update-motd
    https://download.copr.fedorainfracloud.org/results/atim/bottom/epel-8-aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
    Trying other mirror.
    tailscale-stable/aarch64/signature                                                                                                                                                                              |  800 B  00:00:00     
    tailscale-stable/aarch64/signature                                                                                                                                                                              | 2.9 kB  00:00:00 !!! 
    No package bottom available.
    Error: Nothing to do
```
Running the same set of commands on an amd64 instance runs/installs as expected.

**Comment by ClementTsang** [comment]
I don't handle any repos/mirrors on Ubuntu so I'm not really sure what's going on, unfortunately. Might have to contact the package maintainer.

**Comment by Spunkie** [comment]
Judging from the commit history that should be @tim77?

**Comment by ClementTsang** [comment]
Yeah, looks like it.

Note I don't know how Fedora/COPR expects people to contact package maintainers for stuff like this (I only have experience with this stuff in AUR), you might also have luck asking them through the package page: https://copr.fedorainfracloud.org/coprs/atim/bottom/

**Comment by tim77** [comment]
Thanks for reporting. Now `aarch64` builds [available](https://copr.fedorainfracloud.org/coprs/atim/bottom/build/4364943/) for recent Fedora/RHEL/CentOS.

**Comment by ClementTsang** [comment]
This again seems like a question for the package maintainer for copr. They mentioned they only have packages for _recent_ versions of Feodra/RHEL/CentOS - is that why?

**Comment by Spunkie** [comment]
Ah yes you are correct, I didn't notice that the EPEL 7 version is still amd64 only. https://copr.fedorainfracloud.org/coprs/atim/bottom/

**Comment by ClementTsang** [comment]
@tim77 sorry for pinging you again, but would it be possible to look at this?

**Comment by tim77** [comment]
> @tim77 sorry for pinging you again, but would it be possible to look at this?

No need to apologize. I'll try to look at this as soon as i can. But some my quick thoughts: official Amazon docs [said](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/add-repositories.html) that we need to enable EPEL-7 repo for AL2. The problem is that the only EPEL Fedora repos support `aarch64` (official EPEL repo), but Copr not. Copr support `aarch64` builds only for EPEL-8 and newer.

Packaging `bottom` for EPEL-7 is nearly impossible and requires a lot of resources due how Rust software packaged in Fedora/EPEL. Would be really great if Amazon Linux do not stuck in stone age and upgraded one day.

**Comment by ClementTsang** [comment]
Interesting stuff to learn, thanks for the info.

I guess one way (maybe?) to work around the glibc issues is just build for musl. However, I don't know how that would look in regards to packaging/distribution, or if that would be an acceptable solution.

**Comment by bkervaski** [comment]
No issues here installing bottom_aarch64-unknown-linux-gnu.tar.gz 0.6.8 on ec2 graviton 2 instances.
