### ISSUE TITLE
armv7 musl binaries

### ISSUE THREAD

**Issue by patrickelectric** [ClementTsang/bottom#725]
### Describe the feature request

I'm trying to run the binary under a TV, but it appears that some packages are missing, is it possible to have it as a static binary with musl ?

**Comment by patrickelectric** [comment]
Hey, thanks for the quick fix! But is I was unable to find the artifacts.

**Comment by ClementTsang** [comment]
Yeah, had to run a build. It should be available on the nightly release here (and eventually in an actual release whenever I get around to that): https://github.com/ClementTsang/bottom/releases/download/nightly/bottom_armv7-unknown-linux-musleabihf.tar.gz

I ran it on my Pi4 and it seems to work alright.
