### ISSUE TITLE
bottom not install problem with  libc6:amd64

### ISSUE THREAD

**Issue by jovington** [ClementTsang/bottom#736]
Hello
I am trying to install Bottom on linux bulleyes and it gives me the following error.
so when I do sudo apt install -y ./bottom.deb the error is
`The following packages have unmet dependencies:
 bottom:amd64 : Depends: libc6:amd64 (>= 2.18) but it is not installable`

I have the following library installed but in a higher version
``
libc6/stable,now 2.31-13+rpt2+rpi1+deb11u2 arm64 [installed]
libc6/stable 2.31-13+rpt2+rpi1+deb11u2 armhf
``
Tanks in advance.. .

**Comment by ClementTsang** [comment]
The .deb file is created for x86, it looks like you're installing on a rpi?

I can start creating arm .deb files and I'll clarify in the README, my apologies.

**Comment by ClementTsang** [comment]
As a temporary workaround, installing via cargo should work fine for ARM.

**Comment by ClementTsang** [comment]
#739 adds armv7 and aarch64 gnu debian builds, and should be available shortly in [nightly releases](https://github.com/ClementTsang/bottom/releases/tag/nightly) (and eventually normal releases, probably starting from the next one). I've tested both of them on my Pis and they seem to install and work alright via `dpkg -i`

I might also add musl targets to avoid needing the glibc dependency.
