### ISSUE TITLE
[Debian] Question about dependencies

### ISSUE THREAD

**Issue by werdahias** [ClementTsang/bottom#787]
Hi, I'm in the process of packaging all the dependencies for bottom so we can get an official debian package. On crates.io it states `battery` as dependency. The current github includes `nvml-wrapper` and `starship-battery `instead. Will these be included in the next release (instead of battery)?

**Comment by ClementTsang** [comment]
@werdahias Yes, those would be included. `starship-battery` is the succeeding fork I'm using to somewhat abandoned `battery` crate (#724), and `nvml-wrapper` is used for Nvidia card details (#676).

On that note, I'm probably going to try and release a new stable version soon since it's been a while since the last release.

**Comment by werdahias** [comment]
Great, thanks. For debian, the only missing chunk is heim which will be a bit of work.

**Comment by ClementTsang** [comment]
If it's any consolation, I'm planning on eventually removing the heim dependency since it's not really maintained anymore.

**Comment by werdahias** [comment]
Will that make in in the new release? That would save me a lot of work

**Comment by ClementTsang** [comment]
Might take a look this weekend and get back to you. If it isn't too bad (I don't think it would be...) then maybe?

**Comment by werdahias** [comment]
Yeah no worries, take you time

**Comment by werdahias** [comment]
`starship-battery` is in debian, so the only thing "missing" would be `heim`

**Comment by werdahias** [comment]
all dependencies are in debian except `cargo-husky` and `heim`.  I guess I can patch out cargo-husky or package it.

**Comment by ClementTsang** [comment]
Yep, husky can be patched out if that's easier (it's mostly just for dev purposes), and I'm working on removing heim.

**Comment by ClementTsang** [comment]
Closing this as heim is now removed; from 0.9.0 onward I think the only problematic thing is husky, which shouldn't be too hard hopefully to patch out if needed.
