### ISSUE TITLE
Fish completion seems not generated 「Fedora」

### ISSUE THREAD

**Issue by Jedsek** [ClementTsang/bottom#790]
See title.
I installed bottom from copr.

**Comment by Jedsek** [comment]
My Fedora is 36, and there is no `btm.fish` in `/usr/share/fish/completions`

**Comment by ClementTsang** [comment]
Just a heads up, I don't handle the COPR distribution of bottom, that's managed by @tim77. I've mentioned them here for visibility, but in general I don't handle stuff like this outside of certain distribution channels I personally manage.

In the meantime, I suppose you can download the [fish completions](https://github.com/ClementTsang/bottom/releases/download/0.6.8/completion.tar.gz) from the [releases page](https://github.com/ClementTsang/bottom/releases/tag/0.6.8).

You also might have some luck commenting on the [copr page itself](https://copr.fedorainfracloud.org/coprs/atim/bottom/), I guess.

**Comment by tim77** [comment]
Should work now. New `bottom` build with completion https://copr.fedorainfracloud.org/coprs/atim/bottom/build/4763763/. Please test.
