### ISSUE TITLE
It's super easy to read temperatures on aarch/arm64 on FreeBSD

### ISSUE THREAD

**Issue by dmilith** [ClementTsang/bottom#797]
I noticed that FreeBSD support is in the master. Congratulations :)

I'm using RockPro64 board from Pine64, and on systems with full support (FreeBSD 13.1 in my case), I can do:

```bash
sysctl hw.temperature
hw.temperature.CPU: 47.5C
hw.temperature.GPU: 45.6C
```

to read CPU and GPU temperature. It could be rendered in "Sensors" window of the Bottom.

**Comment by ClementTsang** [comment]
Hm. From looking online, this seems to be more of a RockPro64 thing rather than a general one - I'll still gladly add support for it, but I can't test it.

**Comment by ClementTsang** [comment]
@dmilith if it's not too much trouble, can you try the `support_freebsd_rockpro64_temps` branch and see if this works?

**Comment by ClementTsang** [comment]
Merged the change into the master branch. Feel free to test it, and if there are problems, let me know or reopen the issue.
