### ISSUE TITLE
[Bug]: "kinfo_getfile(): No such process" should be silenced

### ISSUE THREAD

**Issue by dmilith** [ClementTsang/bottom#798]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

One screenshot instead of 100 words: https://s.verknowsys.com/47a2bdcc2adb3e2aa29030340b65eec3.png

The problem is related to the sysinfo crate, the process list fetching routine to be precise. When one of probed process is short lived/ killed/ interrupted or finished when kinfo_getfile() reads info from the process file descriptor.

Details about the syscall: https://www.freebsd.org/cgi/man.cgi?apropos=0&sektion=3&query=kinfo_getfile&manpath=FreeBSD+7.0-current&format=html

A possible solution may be to take control over default error out (/dev/stderr on UNIX*-like) while Bottom is running.

### What operating system are you using?

Other (please specify in description)

### What architecture are you using?

Other (please specify in description)

### What terminal(s) are you running `bottom` on?

Wezterm

### What version of `bottom` are you running?

master (0.6.x)

### How did you install `bottom`?

from git

### How can we reproduce this?

Forget that bottom runs in the background on a busy system :)

### Additional information

It happens on all architectures but likely only *BSD have this syscall.

**Comment by plasmoduck** [comment]
I also have the same problem on FreeBSD. Keep getting terminal errors over Bottom. Would be nice to see this fixed.

**Comment by ClementTsang** [comment]
Might try to take a look when I have some time, the tricky part is I don't really have a FreeBSD system to develop and test on so I would have to set something up to replicate.

**Comment by plasmoduck** [comment]
Virtualbox?

**Comment by ClementTsang** [comment]
Yeah, a VM would probably work.

**Comment by plasmoduck** [comment]
This is how it looks.
![screen-221115-1951-03](https://user-images.githubusercontent.com/38978656/201874039-29146f68-d010-41cd-9ffb-beb0962db803.png)

**Comment by plasmoduck** [comment]
Sounds good.

**Comment by ClementTsang** [comment]
Quick question - do these stderr messages continuously occur as bottom runs? Or does it only appear on startup? I'm only able to get the messages on startup but I'm not sure if that's because my VM right now is very simple.

**Comment by plasmoduck** [comment]
It usually happens a few minutes after start up and I think it keeps
happening now and then.

**Comment by ClementTsang** [comment]
Upstream issue filed here: https://github.com/GuillaumeGomez/sysinfo/issues/875

**Comment by ClementTsang** [comment]
Pushed a patch that should band-aid the issue. If possible, please let me know if it fixes the issue (you can grab the FreeBSD binary directly [here](https://github.com/ClementTsang/bottom/releases/download/nightly/bottom_x86_64-unknown-freebsd.tar.gz)). If it's still busted feel free to re-open.

EDIT (2026-07-20): https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228432 - we should be able to skip this hack now

**Comment by plasmoduck** [comment]
That binary doesnt work. I get:
` ld-elf.so.1: /lib/libc.so.7: version FBSD_1.7 required by /usr/home/cjg/dl/btm not found`

**Comment by ClementTsang** [comment]
It's built on 13, so that's probably why

**Comment by ClementTsang** [comment]
@plasmoduck FreeBSD 12 binaries can be found [here](https://github.com/ClementTsang/bottom/releases/download/nightly/bottom_x86_64-unknown-freebsd-12-3.tar.gz) now.
