### ISSUE TITLE
[Bug]: On machines with Hybrid Graphics, bottom keeps the dedicated GPU awake

### ISSUE THREAD

**Issue by DianaNites** [ClementTsang/bottom#803]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

On machines, such as laptops, that have and can switch between two graphics devices, powering one off wen not in use, bottom keeps the dedicated device awake and consuming power

The way I usually use bottom is within a quake-style terminal, always running, usually on desktop machines, but this problem makes that infeasible to do on my laptop, since it seems to force the GPU to always be in ACPI D0, instead of D3cold (`/sys/class/drm/card0/device/power_state`) (documented [here](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-power_state) and [here](https://www.kernel.org/doc/html/latest/power/pci.html#native-pci-power-management))

### What operating system are you using?

Linux

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

Konsole

### What version of `bottom` are you running?

0.6.8

### How did you install `bottom`?

cargo

### How can we reproduce this?

1. Run `cat /sys/class/drm/card0/device/power_state`, observe it in ACPI D3cold
2. Run `btm`
3. Run `cat /sys/class/drm/card0/device/power_state`, observe it in ACPI D0, where it will remain until `btm` is closed (give or take a few seconds)

### Additional information

My laptop is the ASUS ROG G15 Advantage Edition (2021) G513QY

This laptop does not have a hardware MUX switch

Based on my own research this may be a limitation of querying temperature, running `sensors` also triggers the GPU to wake up. There may be a way to do this without waking it up, but `sensors` doesnt do it.

Perhaps theres a way to exclude the dGPU if its not in use, and avoid waking it up? Or exclude all GPUs?

Configuration option to require temperature sensors to be manually refreshed? Or disabled? Enable/disable without re-opening bottom?

**Comment by ClementTsang** [comment]
Interesting, never considered this. I'll definitely look into seeing if disabling GPU checking is possible at the very least.

**Comment by ClementTsang** [comment]
Took a quick look at sysinfo documentation (which I plan on moving most stuff to), it *might* be doable to be able to ignore certain components via the config file (fingers crossed what I have in mind works)?

Might take a bit to get working though as I have to do some other blocking work first, but when I do I might also need some help with testing the fix since I don't have a laptop with hybrid graphics where I am right now.

**Comment by DianaNites** [comment]
Would be happy to test potential fixes if/when available, thank you!

**Comment by DianaNites** [comment]
As usual, the Arch Wiki seems to have the answers

https://wiki.archlinux.org/title/AMDGPU#Manually lists the sysfs methods for getting GPU temp, at least on amdgpu, and while checking them *does* wake the GPU, that could be conditional on `power_state`, displaying the values as N/A when its D3cold? Querying the *label* does no awaken the GPU

No idea about nvidia though, maybe it plays nicely with sysfs interfaces and this works for both?

I'm also just noticing, bottom has no way to distinguish *which* GPU a sensor is referring to.

On my device, the iGPU only has the edge sensor, but the dGPU has mem, edge, and junction. This results in bottom listing "amdgpu: edge" twice, which isnt very informative. Instead of listing the driver name, it should probably list the GPU name, or something like `GPU N`?

But yeah seems this is entirely resolvable through sysfs and an if statement, on at least amdgpu

**Comment by DianaNites** [comment]
Update, `autosuspend_delay_ms` from [here](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-power) seems to control when it suspends and thus enters D3cold, and this can be configured. The default value seems to be 5 seconds

Thats still too long for properly monitoring temperatures, but combined with a load check, takes out the guesswork?

**Comment by DianaNites** [comment]
I made a PR, #805, that (mostly) replaces heim with manual sysfs reads, and then does whats needed to avoid waking the GPU

This partially fixes it for me, and shouldnt change anything else
