### ISSUE TITLE
[Bug]: Kill selected process hotkeys don't work when in tree mode on the master branch

### ISSUE THREAD

**Issue by DianaNites** [ClementTsang/bottom#815]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

On the master branch, using either the `dd` or `F9` hotkeys while in tree mode does nothing. They work normally when not in tree mode.

This works as expected on the latest crates.io release

### What operating system are you using?

Linux

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

Konsole

### What version of `bottom` are you running?

0.6.8 and commit 3d2c40ce2f999e2d25030014cfae745591fd9d5e

### How did you install `bottom`?

cargo, crates.io and locally, rustc 1.63

### How can we reproduce this?

1. Enable tree mode
2. Push `dd` or `F9`
3. Nothing happens

### Additional information

All other hotkeys seem to work as expected in tree mode

**Comment by ClementTsang** [comment]
Found the issue, might take a bit to fix - I might end up just fixing it while refactoring a bunch of other stuff related to drawing tables.
