### ISSUE TITLE
Ability to launch a specific widget already maximized, without having to press "e" manually

### ISSUE THREAD

**Issue by alexleduc76** [ClementTsang/bottom#822]
### Pretty much as the title says

Ability to launch a specific widget already maximized, without having to press "e" manually after selecting one of the widgets.

I see that -e is not an existing command line option, so you could make it so that the following command would load Bottom's CPU widget:

btm -e cpu

As you can see in the screenshot, I like to run 3 instances of Bottom in one Konsole window that is split vertically into 3 transparent terminals (I have configured it so that I can hide the title bar with a keyboard shortcut). I'd like to automate loading these as much as I can, so being able to load Bottom widgets directly from the command line would be a great help.

![Screenshot_20221002_113359](https://user-images.githubusercontent.com/13103140/193462454-07379f0c-a23c-4fae-8dd0-fb80c53bdffc.png)

And apart form my own silly UI customizations, I'm sure other users would benefit from it.

**Comment by sou-chon** [comment]
I can have a look at this if no one else is
