### ISSUE TITLE
[Bug] Panic on index out of range - v0.6.8

### ISSUE THREAD

**Issue by twilfredo** [ClementTsang/bottom#895]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

UPDATE: I tried building from source on `<b2c301b1fe435daf41cbd15b4dab3bd5a003f4af>`, and I can no longer reproduce this error. So this looks to have been fixed on the master branch,  but not updated in the COPR for Fedora (latest build was 2 months ago)?  

To reproduce:

```
$ btm
```
then click on `Motherboard` in temperature section, the scroll all the way down in the temperature section, once you hit the end, keep scrolling and it will panic on the following error. 

Log:
```
thread '<unnamed>' panicked at 'range start index 4 out of range for slice of length 1', library/core/src/slice/index.rs:52:5
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: __libc_start_call_main
  20: __libc_start_main@GLIBC_2.2.5
  21: <unknown>
```

### What operating system are you using?

Fedora 36

### What architecture are you using?

x86

### What terminal(s) are you running `bottom` on?

kitty 0.26.4

fish shell

### What version of `bottom` are you running?

0.6.8

### How did you install `bottom`?

installed through the official fedora guide (dnf)

### How can we reproduce this?

To reproduce:

```
$ btm
```
then click on `Motherboard` in temperature section, the scroll all the way down in the temperature section, once you hit the end, keep scrolling and it will panic on the following error.

**Comment by ClementTsang** [comment]
This should be fixed in the master branch, if possible, can you try to replicate on [nightly](https://github.com/ClementTsang/bottom/releases/tag/nightly)?

**Comment by twilfredo** [comment]
> This should be fixed in the master branch. If possible, can you try to replicate on [nightly](https://github.com/ClementTsang/bottom/releases/tag/nightly)?

Hey,
Yep I just tried this, and it is fixed in master (build from source), just need to update the build in COPR for fedora I think?

**Comment by ClementTsang** [comment]
I assume the maintainer in COPR will update whenever I get around to releasing a new stable version, which should hopefully be not too long from now.

**Comment by twilfredo** [comment]
> I assume the maintainer in COPR will update whenever I get around to releasing a new stable version, which should hopefully be not too long from now.

Sounds good, thanks for the quick reply. 

Closing
