### ISSUE TITLE
WSL ubuntu: thread '<unnamed>' panicked at 'index out of bounds

### ISSUE THREAD

**Issue by Macfly** [ClementTsang/bottom#90]
## Describe the bug

run btm and got this error:
thread '<unnamed>' panicked at 'index out of bounds: the len is 1170 but the index is 4611686018427387991', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/slice/mod.rs:2812:14
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: __libc_start_main
  13: <unknown>

## To reproduce

install the .deb as written in the doc then run btm

## Platform

**Operating System:**
windows 10 with  WSL Ubuntu 18.04 

**Terminal:**
Windows Terminal 0.10.761.0

**Shell:**
ZSH

**Comment by ClementTsang** [comment]
Thanks for the report, I'll look into it and see if I can replicate + fix the problem.

**Comment by ClementTsang** [comment]
Alright, able to replicate this.  Going to fix asap.

**Comment by ClementTsang** [comment]
After taking a look at it, seems like it's already fixed in the upcoming 0.3.0 release (unable to replicate using master).  Going to mark as closed.
