### ISSUE TITLE
typo fails build with yay

### ISSUE THREAD

**Issue by nuisanthon** [ClementTsang/bottom#92]
## Question
installing using yay throws an error due to a character that gets included in a link 
error:  failed to get 200 response from `https://crates.io/api/v1/crates/regex/1.3.5/download`, got 502
please remove the "`" next update for qol

**Comment by ClementTsang** [comment]
Hmm... I don't seem to be able to replicate this.  I'm using yay as well to download and I build fine.

**Comment by nuisanthon** [comment]
turns out, im hasty and inadequate. this was client side issue. please disregard
