### ISSUE TITLE
[Bug] thread panicked at 'Event flag 3 does not exist.'

### ISSUE THREAD

**Issue by Sedorikku1949** [ClementTsang/bottom#920]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

Hello, I discovered the background and I wanted to test it on my windows computer.

I launched the executable and it started to display, I clicked on the temperature box, and then I got this error:
```
thread '<unnamed>' panicked at 'Event flag 3 does not exist.', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.6.2\src\structs\input.rs:200:18
   0: <unknown>
   1: <unknown>
   2: <unknown>                                                                                                                                        
   3: <unknown>                                                                                                                                                                           
   4: <unknown>                                                                                                                                     
   5: <unknown>           
   6: <unknown> 
   7: <unknown>
   8: <unknown>          
   9: <unknown>
  10: <unknown>  
  11: <unknown> 
  12: BaseThreadInitThunk 
  13: RtlUserThreadStart
```
I don't know why `bottom` can't find any temperature sensors (I have two temperature sensors on my motherboard and one in my graphics card), so when I click on "temp", or sometimes on "No Sensors Found" (when "No Sensors Found" is already selected), the thread panics.

### What operating system and version are you using?

Windows 11 22000.1281

### What architecture are you using?

x86

### What terminal(s) are you running `bottom` on?

Windows Terminal

### What version of `bottom` are you running?

0.6.9

### How did you install `bottom`?

Installed bottom through the official github release page

### How can we reproduce this?

1. Start btm.exe on a Windows 11 computer
2. Wait for the process to start drawing some curves

-- Two possibilies --
3. Select the cpu box, and then click on the text "temp"
3. Select the cpu box, and then click on "No Sensors Found" (try many times, the bug doesn't appear sometimes)

### Additional information

I don't know why, but somehow I clicked on the network box and the SAME problem appeared.

It seems to be a bad event that windows is sending to btm.exe or that btm.exe is handling an event that doesn't/cannot (or shouldn't) be handled :O

**Comment by Sedorikku1949** [comment]
Update: the bug appear some time when i click anywhere on the terminal with my mouse

**Comment by ClementTsang** [comment]
This should already be resolved in the master branch, if you could try it that would be great.

**Comment by ClementTsang** [comment]
Also as for:

> I don't know why `bottom` can't find any temperature sensors

It's a [known](https://clementtsang.github.io/bottom/nightly/troubleshooting/?h=temperature#why-cant-i-see-all-my-temperature-sensors-on-windows) potential permissions issue with how `bottom` (and the libraries we use) grab sensor data, unfortunately.

**Comment by ClementTsang** [comment]
Closing this for now as I'm pretty sure this should be resolved, and if not, it needs more info. Feel free to reopen if you encounter this issue again.
