### ISSUE TITLE
[Bug] Resizing to small window crashed Bottom.

### ISSUE THREAD

**Issue by rokejulianlockhart** [ClementTsang/bottom#921]
### Checklist

- [ ] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

```
PS /home/BEEDELLROKEJULIANLOCKHART> btm
thread '<unnamed>' panicked at 'range start index 4 out of range for slice of length 1', library/core/src/slice/index.rs:52:5
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: __libc_start_call_main
  20: __libc_start_main@GLIBC_2.2.5
  21: <unknown>
PS /home/BEEDELLROKEJULIANLOCKHART>
```
![This depicts the problem.](https://user-images.githubusercontent.com/42837531/205331271-2cbe9225-64bd-45f1-9ef9-84ba96282433.png)

### What operating system and version are you using?

Linux beedell.rokejulianlockhart.1669806072 6.0.10-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Nov 26 16:53:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

`konsole`

### What version of `bottom` are you running?

0.6.8

### How did you install `bottom`?

Installed via the official Fedora repository.

### How can we reproduce this?

This solely occurred 1 time, and is not reproducible.

**Comment by ClementTsang** [comment]
Interesting, thought this would be solved by https://github.com/ClementTsang/bottom/pull/665 but I'll take a look.

**Comment by rokejulianlockhart** [comment]
@ClementTsang, because [this does not appear to be possible for me to reproduce](https://github.com/ClementTsang/bottom/issues/921#:~:text=this%20solely%20occurred%201%20time%2C%20and%20is%20not%20reproducible), I am not certain that what you propose shall yield results, but I certainly shall try.

**Comment by ClementTsang** [comment]
No problem, if it happens again feel free to let me know. Otherwise, I might close this since it might be fixed in master and I can't really reproduce it in any way to test if that's the case.

**Comment by rokejulianlockhart** [comment]
Good idea. I'll close this until I manage to reproduce it.
