### ISSUE TITLE
[Bug] CPU graph looks way too big and does not respect `dot_marker` anymore

### ISSUE THREAD

**Issue by hasezoey** [ClementTsang/bottom#933]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

Since the last month (or specifically some time since 4f00434210a20109f4b9ca27c1b1856f376499b5) the CPU graph looks WAY to big in the lines

before (at 4f00434210a20109f4b9ca27c1b1856f376499b5):
![old](https://user-images.githubusercontent.com/10911626/208938454-8a485dc4-a46e-4056-847c-4048a9a8d773.png)

currently (at d8da12ffabf849d4080370f3cf00d376a0a71ab9):
![new](https://user-images.githubusercontent.com/10911626/208938480-5764133c-3ff4-4256-8814-5a03220f2f53.png)

### What operating system and version are you using?

Manjaro 22.0.0

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

konsole 22.12.0 with zsh

### What version of `bottom` are you running?

bottom 0.6.9

### How did you install `bottom`?

git self compile

### How can we reproduce this?

1. download / checkout bottom at the mentioned commit(s)
2. run `cargo build --release` (at least i did it in release)
3. run with `./target/release/btm`
4. observe output

### Additional information

already tried to reset the config at `~/.config/bottom/bottom.toml`
also already tried to set config option `dot_marker = true` and `dot_marker = false` which did not change the output (which is weird by itself) in the latest commit (the older commit still changes the output)

rustc: `rustc 1.66.0 (69f9c33d7 2022-12-12)`

**Comment by ClementTsang** [comment]
Regarding the "big" part, that's intentional, though if it's really bothering people that much then I'll revert it, even though it greatly reduces cpu time on draw.

Regarding the dot marker breaking, I'll look into it.

**Comment by hasezoey** [comment]
> though if it's really bothering people that much then I'll revert it, even though it greatly reduces cpu time on draw.

personally i did like the output where it is not so big, because the big one makes it (at least for me) not easy to discern what core is doing what and just being one big blob to me.
maybe put it behind a config option instead of fully reverting?

**Comment by ClementTsang** [comment]
Mm, I'll see. I might be able to make it work if I manually implement some of the draw logic, but if not then yeah I'll likely add an option.

**Comment by ClementTsang** [comment]
Dot marker bug should be fixed by #934, while old chart drawing behaviour should be returned by #937, while retaining the improved CPU usage. Feel free to reopen if you find any issues.

**Comment by hasezoey** [comment]
can confirm that the latest master (efcf2bde2961d9b820609b56ddc77c666cb3b5bb) looks "thin" again
