### ISSUE TITLE
Add customization to network range in Y-axis

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#96]
## Describe the feature request

_Why should we consider this feature request? Describe why, and/or how you think this feature will solve the issue, or overall improve the application:_

For things like CPU% or mem%, it's easy to range from 0 - 100.

It's a bit harder for networking - maybe someone is using 1Gbit+ on the regular.  Or maybe they'll never hit it and are more concerned with lower levels.  Furthermore, then maybe the whole logarithmic scale of networking isn't needed!

Adding custom ranges, the ability to use log scale or not, and maybe even automatic changing of the Y-scale (toggleable) would be a good idea.

## Additional context/details

_Provide any additional context or details here. What needs to be done, why, etc:_

- [ ] Config option to set what points to track on Y-axis of network
- [x] Ability to disable or enable log scaling
- [x] Automatic scaling... maybe?

**Comment by vimalaguti** [comment]
I would really appreciate a linear Y scale. Any news about this feature?

**Comment by ClementTsang** [comment]
It wouldn't be hard to add, but I haven't had much time to work on much for the past few weeks due to school and job hunting.

I'll probably add this and some other low hanging fruit in a few weeks when I have a break.

**Comment by int3l** [comment]
This feature will be very neat and if I can add something more - network equipment uses units like 10/100/1000 Mbps | Gbps | Tbps (Megabits/Gigabits/Terabits). I guess that this will be very useful as a separate setting/flag `network_units` like the `temperature_type`.
