### ISSUE TITLE
-b flag not available in 0.2.2

### ISSUE THREAD

**Issue by kaushalyap** [ClementTsang/bottom#98]
## Describe the bug

_A clear and concise description of what the bug is and what the expected behaviour was. If applicable, add screenshots to help explain your problem:_

## To reproduce

1. Download the 0.2.2 binary and place it in your path
2. type `btm -b` in terminal
3. will see following error

> error: Found argument '-b' which wasn't expected, or isn't valid in this context
> 
> USAGE:
>     btm [FLAGS] [OPTIONS]
> 
> For more information try --help

## Platform

**Operating System:** Fedora 31

**Terminal:** # GNOME Terminal 3.34.2 using VTE 0.58.3 +BIDI +GNUTLS

**Shell:** GNU bash, version 5.0.11(1)-release (x86_64-redhat-linux-gnu)

**Comment by ClementTsang** [comment]
The basic flag is for the upcoming 0.3 release.  It's not out yet.

I'll be more clear in the future, sorry!
