### ISSUE TITLE
[Bug] Text color regression?

### ISSUE THREAD

**Issue by alexleduc76** [ClementTsang/bottom#993]
### Checklist

- [X] I've looked through [troubleshooting](https://clementtsang.github.io/bottom/nightly/troubleshooting), [known problems](https://clementtsang.github.io/bottom/nightly/support/official/#known-problems), and  [existing open issues](https://github.com/ClementTsang/bottom/issues?q=is%3Aopen+is%3Aissue) for similar issues.

### Describe the issue

I compiled and installed version 0.7.1 and the text color around the X and Y axis of the graphs is green, regardless of which theme that is used (default, nord, gruvbox, etc.)

What it looks like now:
![Screenshot_20230120_123528](https://user-images.githubusercontent.com/13103140/213766621-1eed8d8e-6c62-46ce-9651-49c1295e2fad.png)

What I expect it to look like:
![Screenshot_20230120_124115](https://user-images.githubusercontent.com/13103140/213767600-1b6d4744-39e7-45b0-9376-286ed319a822.png)

### What operating system and version are you using?

Manjaro Linux 5.15.85-1

### What architecture are you using?

x86_64 / AMD64

### What terminal(s) are you running `bottom` on?

konsole 22.12.0

### What version of `bottom` are you running?

0.7.1

### How did you install `bottom`?

Installed by building the master branch (commit id: d8da12f)

### How can we reproduce this?

rustup update stable

cargo install bottom --locked

**Comment by ClementTsang** [comment]
Interesting, I'll take a look in a bit.

**Comment by alexleduc76** [comment]
I just realized that it's one of the commits after 0.7.1 was released that I compiled.

Commit d8da12ffabf849d4080370f3cf00d376a0a71ab9 (the latest one on the master branch right now)

**Comment by ClementTsang** [comment]
Hmm, maybe. Most of the changes since 0.7.1 released has been admin stuff though (CI, docs) or small non-interface stuff, so I would assume it was something in 0.7.x - especially since I did make changes to how graphs are rendered in 0.7.0 (though it shouldn't have affected the axis label colours of all things, I might have just done an oopsie somewhere).

**Comment by ClementTsang** [comment]
Yep, seems like I'm not setting the axis colouring at all - though I don't know why it's giving you green text. I'll fix the colouring issue in a bit.

**Comment by alexleduc76** [comment]
I only experience the issue in Konsole. Alacrity and Kitty render with the right colors. 0.6.8 works fine in Konsole though

**Comment by alexleduc76** [comment]
It looks like the green comes from the default color I picked for the Konsole theme. I suppose it makes sense (from a konsole point of view, but not from a bottom theme point of view), since you were not explicitly setting that axis color yourself, that it would use the default color.  It's just strange that it did not do that on previous version of bottom.

![image](https://user-images.githubusercontent.com/13103140/213808795-ef021d2e-a156-4e75-b1bf-79cc7ede04de.png)

**Comment by ClementTsang** [comment]
Haha, I was just about to ask "would your konsole settings happen to have a green colour", but you answered me before I even asked.

Good to know this adds up with what I found when I quickly checked my source code, I'm just not setting *any* colour for the axis text so I guess it just defaults to whatever the default colours are... which I guess I missed during testing since I default to white text, and it looks close enough that I didn't spot it.

I'll add a fix in a bit today, and probably aim for a stable release with the fix and some various other stuff this weekend or so.

**Comment by ClementTsang** [comment]
Should be fixed in master, and shortly in the nightly release if you don't want to build it manually.

**Comment by alexleduc76** [comment]
Thanks you!

**Comment by alexleduc76** [comment]
I built the nightly and it still has the issue. I suspect the issue was never with the bottom code, but with one of its dependencies. Otherwise, the colour issue would occur when I run 0.6.8. It looks like figuring this out might be a lot of work for something that only occurs in konsole. So no pressure. I can just use a konsole colour theme that has white as it's default colour as a workaround.

**Comment by ClementTsang** [comment]
Hm... I had tried it on konsole and it had fixed the issue.

**Comment by ClementTsang** [comment]
Yeah, as of 0.8.0, I cannot reproduce this anymore. Are you sure you're building off of either the latest version of master, or 0.8.0?

**Comment by alexleduc76** [comment]
Yes, it's the latest commit (commit message: "docs: update README section for unofficial support"). Since you can't reproduce it, it might be a one-off thing that's specific to something I customized on my system. It might be worth looking into it again if others report the same issue.

**Comment by ClementTsang** [comment]
That isn't the latest commit, but that shouldn't matter I guess, it's after the patch. How are you building and running it?

**Comment by alexleduc76** [comment]
I must have done something wrong because I just rebuilt it, and it said something like "replacing 0.7.1 to 0.8.0" at the end of compilation. Everything works as expected now. Thanks again.
